/* GENERATED by taskgraph/codegen/strobes.py — DO NOT EDIT.
 *
 * Regenerate with `taskgraph codegen`; `taskgraph codegen --check` fails CI when
 * this file is stale. Every code below comes from schema/strobe_vocab.v1.json.
 *
 * APPEND-ONLY. A code is never repurposed, never renumbered, never deleted:
 * downstream analysis is keyed on these numbers and historical comparability is a
 * hard requirement. Adding one means taking the next free number from that file's
 * `free_ranges`.
 *
 * These do NOT replace BehaviorBox.h's BF_* defines. That header belongs to the
 * reference repo and its numbers are fixed by four years of recorded sessions;
 * this is the same registry under a distinct prefix, so code in THIS repo can name
 * a strobe without writing a number down twice.
 */

#ifndef TG_STROBES_H
#define TG_STROBES_H

#define TG_VOCAB_VERSION_DECLARED 1

#define TG_STROBE_ODOR_1_ON             101  // entry to a sampling HOLD bound to odor line 1
#define TG_STROBE_ODOR_2_ON             102  // entry to a sampling HOLD bound to odor line 2
#define TG_STROBE_ODOR_3_ON             103  // entry to a sampling HOLD bound to odor line 3
#define TG_STROBE_ODOR_4_ON             104  // entry to a sampling HOLD bound to odor line 4
#define TG_STROBE_ODOR_5_ON             105  // entry to a sampling HOLD bound to odor line 5
#define TG_STROBE_ODOR_6_ON             106  // entry to a sampling HOLD bound to odor line 6
#define TG_STROBE_START_SESSION         221  // session entry, timestamp 0
#define TG_STROBE_LIGHTS_ON             222  // entry to the engagement window (trial cue on)
#define TG_STROBE_LAZY_RAT              223  // entry to the no-engagement penalty
#define TG_STROBE_ODOR_POKE             224  // entry to the commitment hold
#define TG_STROBE_ODOR_UNPOKE_EARLY     225  // entry to the broken-hold penalty
#define TG_STROBE_ODOR_UNPOKE           226  // entry to the response window, after a complete sample
#define TG_STROBE_LIGHTS_OFF            233  // entry to a zero-duration node that clears the trial light
#define TG_STROBE_INVALID_TRIAL         234  // entry to the invalid terminal
#define TG_STROBE_END_CORRECT_ITI       242  // entry to the correct terminal
#define TG_STROBE_END_INCORRECT_ITI     243  // entry to the incorrect terminal
#define TG_STROBE_END_SESSION           246  // session exit
#define TG_STROBE_ODOR_OFF              247  // entry to the sampling-release WAIT_EXIT, and to an inter-stimulus gap
#define TG_STROBE_WATER_POKE_L          248  // entry to the response branch node, left channel
#define TG_STROBE_WATER_POKE_R          249  // entry to the response branch node, right channel
#define TG_STROBE_WATER_UNPOKE_EARLY_L  250  // entry to the response-hold-failure penalty, left
#define TG_STROBE_WATER_UNPOKE_EARLY_R  251  // entry to the response-hold-failure penalty, right
#define TG_STROBE_FLUID_L               252  // entry to the left reward PULSE
#define TG_STROBE_FLUID_R               253  // entry to the right reward PULSE
#define TG_STROBE_WATER_UNPOKE_L        254  // entry to the ITI delay, after leaving the left well
#define TG_STROBE_WATER_UNPOKE_R        255  // entry to the ITI delay, after leaving the right well
#define TG_STROBE_WATER_POKE_NONE       256  // entry to the correct terminal path on a withhold trial
#define TG_STROBE_WATER_POKE_ERROR_L    257  // entry to the wrong-port penalty, left
#define TG_STROBE_WATER_POKE_ERROR_R    258  // entry to the wrong-port penalty, right
#define TG_STROBE_RETENTION_ON          260  // entry to the unfilled retention delay
#define TG_STROBE_INTERSTIM_GAP_ON      261  // entry to the gap between chained stimuli
#define TG_STROBE_RESP_OMIT             262  // entry to the omission penalty
#define TG_STROBE_WATCHDOG_FAULT        263  // a state exceeding its maximum dwell; the session then ends
#define TG_STROBE_STOP_FLUID_G_R        357  // entry to the right consumption WAIT_EXIT
#define TG_STROBE_STOP_FLUID_G_L        369  // entry to the left consumption WAIT_EXIT

/*  RETIRED — emitted by firmware this repository no longer contains, and
 *  MUST NOT be reused. Listed rather than omitted: a gap in the numbering
 *  looks free, and reissuing one of these would silently merge two
 *  unrelated event types in any analysis spanning the boundary. */
// #define TG_STROBE_DUMMY_SOLENOID_CLICK_1 110  // RETIRED
// #define TG_STROBE_DUMMY_SOLENOID_CLICK_2 111  // RETIRED
// #define TG_STROBE_DUMMY_SOLENOID_CLICK_3 112  // RETIRED
// #define TG_STROBE_DUMMY_SOLENOID_CLICK_4 113  // RETIRED

#endif  /* TG_STROBES_H */
