/* GENERATED by taskgraph/codegen/wire.py — DO NOT EDIT.
 *
 * Regenerate with `taskgraph codegen`; `taskgraph codegen --check` fails CI when
 * this file is stale.
 *
 * The byte layout of an uploaded table. taskgraph/emit/pack.py is where these are
 * decided and why; this file is how the firmware reads them without restating a
 * single number.
 *
 * LITTLE-ENDIAN, and every multi-byte field is read a byte at a time. Both ends
 * are little-endian AVR/x86/ARM, so this costs nothing -- but it is written down
 * rather than assumed, and reading byte-wise means no field's alignment is the
 * compiler's decision. That is the same hazard TgTimingSet already demonstrated:
 * 3 bytes on avr-g++, 4 on clang++, clean on both.
 */

#ifndef TG_WIRE_H
#define TG_WIRE_H

#include <stdint.h>

/*  First bytes on the wire. A board handed anything else -- the tail of an
 *  abandoned upload, a stray START line -- says so, instead of parsing
 *  whatever arrived as a node array. */
#define TG_TABLE_MAGIC "TGTB"
#define TG_MAGIC_0 0x54
#define TG_MAGIC_1 0x47
#define TG_MAGIC_2 0x54
#define TG_MAGIC_3 0x42

/*  The version of the BYTE LAYOUT, distinct from spec/vocab/template versions.
 *  Bumped when a section moves, is added, or changes width. A board refuses a
 *  format it does not know rather than guessing at offsets. */
#define TG_WIRE_FORMAT 1

#define TG_HDR_SIZE 24
#define TG_CRC_SIZE 4
#define TG_WATCH_SLOTS 8

/*  Upload framing. TG_CHUNK_BYTES is what the host SHOULD send per line;
 *  the board processes whatever arrives and only requires that a line fit
 *  in TG_RX_LINE_MAX. Announced in CAP so the host does not have to
 *  compile its own copy -- the mirroring pattern this project keeps
 *  finding. */
#define TG_CHUNK_BYTES 64
#define TG_RX_LINE_MAX 192

/*  Header field offsets, in bytes from the start of the table. */
#define TG_HDR_WIRE_FORMAT 4  /* u8 */
#define TG_HDR_SPEC_VERSION 5  /* u8 */
#define TG_HDR_VOCAB_VERSION 6  /* u8 */
#define TG_HDR_TEMPLATE_VERSION 7  /* u8 */
#define TG_HDR_SPEC_HASH 8  /* u32 */
#define TG_HDR_N_NODES 12  /* u8 */
#define TG_HDR_N_EDGES 13  /* u8 */
#define TG_HDR_N_TIMING 14  /* u8 */
#define TG_HDR_N_ACTIONS 15  /* u8 */
#define TG_HDR_N_TRIAL_TYPES 16  /* u8 */
#define TG_HDR_N_PORTS 17  /* u8 */
#define TG_HDR_N_STIMULI 18  /* u8 */
#define TG_HDR_N_WATCH 19  /* u8 */
#define TG_HDR_N_STAGE_ROWS 20  /* u8 */
#define TG_HDR_N_TIMING_SETS 21  /* u8 */

/*  Section order in the body, immediately after the header. THE RECEIVER MUST
 *  PARSE IN THIS ORDER. Listed as an enum so a reordering here is a compile
 *  error there rather than a table that loads and means something else. */
enum TgWireSection {
  TG_SEC_NODES = 0,
  TG_SEC_EDGES = 1,
  TG_SEC_TIMING = 2,
  TG_SEC_ACTIONS = 3,
  TG_SEC_TRIAL_TYPES = 4,
  TG_SEC_PORTS = 5,
  TG_SEC_STIMULI = 6,
  TG_SEC_STAGE_ROWS = 7,
  TG_SEC_TIMING_SETS = 8,
  TG_SEC_MAX_DWELL = 9,
  TG_SEC_WATCH_PIN = 10,
  TG_SEC_WATCH_PORT = 11,
  TG_SEC_COUNT = 12
};

/*  Read a little-endian field out of a byte buffer. Byte-wise on purpose:
 *  a cast would make the offset's alignment the compiler's problem. */
static inline uint16_t tgRdU16(const uint8_t *b, uint16_t off)
{
  return (uint16_t)((uint16_t)b[off] | ((uint16_t)b[off + 1] << 8));
}

static inline uint32_t tgRdU32(const uint8_t *b, uint16_t off)
{
  return (uint32_t)b[off] | ((uint32_t)b[off + 1] << 8) |
         ((uint32_t)b[off + 2] << 16) | ((uint32_t)b[off + 3] << 24);
}

#endif  /* TG_WIRE_H */