/*
  strobe_fixture.h -- strobe codes for the HOST TESTS ONLY.

  The real codes are generated by Ephymeris into each sketch's TaskPins.h
  (BoxStrobes.h explains why none are written here). These numbers are
  deliberately NOT the lab's vocabulary: 1..N in name order. If a host test
  passes with them, nothing in the library depends on what a code's number is
  -- which is the property that lets a vocabulary be edited without touching
  the firmware. A test that starts asserting a specific number has stopped
  testing the library and started mirroring the vocabulary.

  Lists every BF_* name the library and the bundled sketches emit by name.
  Include before <BehaviorBox.h>.
*/
#ifndef STROBE_FIXTURE_H
#define STROBE_FIXTURE_H

#define BF_END_CORRECT_ITI 1
#define BF_END_INCORRECT_ITI 2
#define BF_END_SESSION 3
#define BF_FLUID_L 4
#define BF_FLUID_R 5
#define BF_INVALID_TRIAL 6
#define BF_LAZY_RAT 7
#define BF_LIGHTS_OFF 8
#define BF_LIGHTS_ON 9
#define BF_ODOR_1_ON 10
#define BF_ODOR_3_ON 11
#define BF_ODOR_OFF 12
#define BF_ODOR_POKE 13
#define BF_ODOR_UNPOKE 14
#define BF_ODOR_UNPOKE_EARLY 15
#define BF_RESP_OMIT 16
#define BF_START_SESSION 17
#define BF_STOP_FLUID_G_L 18
#define BF_STOP_FLUID_G_R 19
#define BF_WATER_POKE_ERROR_L 20
#define BF_WATER_POKE_ERROR_R 21
#define BF_WATER_POKE_L 22
#define BF_WATER_POKE_NONE 23
#define BF_WATER_POKE_R 24
#define BF_WATER_UNPOKE_EARLY_L 25
#define BF_WATER_UNPOKE_EARLY_R 26
#define BF_WATER_UNPOKE_L 27
#define BF_WATER_UNPOKE_R 28

#endif // STROBE_FIXTURE_H
