/*
  utility_fixture.h -- a channel table for the HOST TEST of BoxUtility.h only.

  The real table is generated by Ephymeris from the Rig page into each built
  BOX_Utility folder (UtilityChannels.h). This one describes a deliberately
  SMALLER box than the lab's -- three stimulus lines, two reward lines -- so a
  test that passes here proves the engine reads the table rather than knowing
  the lab's box by heart.
*/
#ifndef UTILITY_FIXTURE_H
#define UTILITY_FIXTURE_H

#define BOX_UTILITY_NUM_OUTPUTS 7
#define BOX_UTILITY_OUTPUTS { \
  {"odor_line_1", "Odor 1", 22, BOX_UTIL_EMITTER}, \
  {"odor_line_2", "Odor 2", 24, BOX_UTIL_EMITTER}, \
  {"odor_line_3", "Odor 3", 26, BOX_UTIL_EMITTER}, \
  {"fluid_0", "Left reward", 42, BOX_UTIL_REWARD}, \
  {"fluid_1", "Right reward", 44, BOX_UTIL_REWARD}, \
  {"trial_light", "Trial light", 36, BOX_UTIL_CUE}, \
  {"vacuum", "Vacuum", 40, BOX_UTIL_VACUUM} }
#define BOX_UTILITY_NUM_INPUTS 3
#define BOX_UTILITY_INPUTS { \
  {"odor_port", "odor port", 2}, \
  {"left_well", "left well", 4}, \
  {"right_well", "right well", 3} }
#define BOX_UTILITY_STATUS_BYTES 320

#endif // UTILITY_FIXTURE_H
