"""The record layout — Python owns it, C++ asserts conformance.

THE PROBLEM THIS SOLVES IS LIVE, NOT HYPOTHETICAL. `TgTimingSet` was declared as
`{uint8 idx; uint16 ms;}` and measured, by compiling, at **3 bytes under
avr-g++ -mmcu=atmega2560 and 4 under clang++** -- because AVR has no alignment
requirement for uint16 while x86/ARM want it 2-byte aligned. Reordering the fields
does not help (still 3/4). It was also the only record with no static_assert.

That is precisely the hazard TaskTable.h's own header comment warns about: "a
layout that differs between the host build and the AVR build would corrupt every
uploaded table while compiling cleanly on both."

The fix has two halves and needs both:

  1. An explicit pad byte, so the record is 4 bytes under both toolchains. Padding
     rather than __attribute__((packed)): packed would give 3 bytes everywhere but
     makes every field access unaligned on the host, and the byte it saves is not
     worth a permanent performance footgun in the trial loop.
  2. GENERATED assertions, compiled under both toolchains. A hand-written
     static_assert is exactly what was missing on the one record that diverged,
     and hand-written assertions are only ever added to records someone already
     suspected.
"""

from __future__ import annotations

from dataclasses import dataclass

U8, U16, U32 = 1, 2, 4


@dataclass(frozen=True)
class Field:
    name: str
    width: int
    note: str = ""


@dataclass(frozen=True)
class Record:
    name: str
    fields: tuple[Field, ...]
    size: int
    note: str = ""

    def offsets(self) -> list[tuple[str, int]]:
        """Byte offsets, assuming natural alignment and explicit padding.

        Every record below is laid out so this simple model is correct on BOTH
        toolchains -- that is the whole design constraint. If a record ever needs a
        cleverer model, it needs a pad byte instead.
        """
        out, off = [], 0
        for f in self.fields:
            if f.width == U16 and off % 2:
                raise AssertionError(
                    f"{self.name}.{f.name} is uint16 at odd offset {off}. AVR would pack it "
                    f"and the host would pad it -- add an explicit pad byte before it."
                )
            out.append((f.name, off))
            off += f.width
        if off != self.size:
            raise AssertionError(f"{self.name} fields sum to {off}, declared {self.size}")
        return out


#: THE layout. Mirrors Arduino/libraries/TaskInterpreter/TaskTable.h field for
#: field; the generated header asserts that the mirror holds.
RECORDS: tuple[Record, ...] = (
    Record(
        "TgNode",
        (
            Field("type", U8),
            Field("durIdx", U8),
            Field("strobe", U16, "uint16: five real codes exceed a byte"),
            Field("watchMask", U8),
            Field("actionIdx", U8),
            Field("actionCount", U8),
            Field("edgeIdx", U8),
        ),
        size=8,
    ),
    Record(
        "TgEdge",
        (Field("trigger", U8), Field("guard", U8), Field("target", U8), Field("effect", U8)),
        size=4,
    ),
    Record("TgAction", (Field("channel", U8), Field("op", U8)), size=2),
    Record(
        "TgTrialType",
        (
            Field("stimulus0", U8), Field("stimulus1", U8),
            Field("stimulus2", U8), Field("stimulus3", U8),
            Field("target", U8), Field("weight", U8),
            Field("rewardLine", U8), Field("rewardDurIdx", U8),
        ),
        size=8,
    ),
    Record(
        "TgStageRow",
        (Field("atTrial", U16), Field("count", U8), Field("firstIdx", U8)),
        size=4,
    ),
    Record(
        "TgPort",
        (
            Field("channel", U8), Field("rewardLine", U8),
            Field("enterCode", U16), Field("errorCode", U16),
            Field("breakCode", U16), Field("exitCode", U16),
            Field("rewardCode", U16), Field("rewardStopCode", U16),
            Field("rewardDurIdx", U8),
            Field("_pad", U8, "keeps the record even and the uint16s aligned"),
        ),
        size=16,
    ),
    Record(
        "TgStimulus",
        (
            Field("emitter", U8),
            Field("_pad", U8, "explicit: onCode is uint16 and must land even"),
            Field("onCode", U16),
        ),
        size=4,
    ),
    Record(
        "TgTimingSet",
        (
            Field("idx", U8),
            Field("_pad", U8, "explicit: without it this is 3 bytes on AVR and 4 on the host"),
            Field("ms", U16),
        ),
        size=4,
        note="The record that proved the hazard. See this module's docstring.",
    ),
)

BY_NAME = {r.name: r for r in RECORDS}

BANNER = """/* GENERATED by taskgraph/codegen/layout.py — DO NOT EDIT.
 *
 * Regenerate with `taskgraph codegen`; `taskgraph codegen --check` fails CI when
 * this file is stale.
 *
 * WHY THIS FILE EXISTS. TgTimingSet was {uint8 idx; uint16 ms;} and measured 3
 * bytes under avr-g++ and 4 under clang++ -- AVR has no alignment requirement for
 * uint16. Reordering the fields does not fix it. A layout that differs between the
 * host build and the AVR build corrupts every uploaded table while compiling
 * cleanly on both, which is the failure TaskTable.h's own header warns about.
 *
 * These assertions are the only construction that catches it, because they compile
 * under BOTH toolchains. Include this from the host tests and from any AVR build.
 */
"""


def emit_header() -> str:
    out = [BANNER, "#ifndef TG_LAYOUT_ASSERT_H", "#define TG_LAYOUT_ASSERT_H", ""]
    out.append("#include <stddef.h>  /* offsetof */")
    out.append('#include "TaskTable.h"')
    out.append("")
    out.append("#if __cplusplus >= 201103L")
    out.append("")
    for r in RECORDS:
        if r.note:
            out.append(f"/* {r.note} */")
        out.append(f'static_assert(sizeof({r.name}) == {r.size}, "{r.name} must be {r.size} bytes");')
        for fname, off in r.offsets():
            out.append(
                f'static_assert(offsetof({r.name}, {fname}) == {off}, '
                f'"{r.name}.{fname} must be at byte {off}");'
            )
        out.append("")
    out.append("#endif  /* __cplusplus >= 201103L */")
    out.append("")
    out.append("#endif  /* TG_LAYOUT_ASSERT_H */")
    return "\n".join(out)
