/*
  BoxStrobes.h
  ============
  THE STROBE VOCABULARY IS NOT HERE, and that is the point of this file.

  Every BF_* code is defined in the generated `TaskPins.h` that Ephymeris writes
  beside each sketch it builds, from the ONE vocabulary document the app keeps
  per machine (Ephymeris docs/TASKS.md#strobe-vocabulary). This file used to
  hold a hand-written copy of those numbers, held in step with the app's copy
  and each sketch's task.json by a test -- three copies of facts that four
  years of recorded sessions depend on. Codes are added, retired and removed in
  the app now, and the firmware gets them the only way it can no longer get
  them wrong: generated.

  So a sketch must `#include "TaskPins.h"` BEFORE <BehaviorBox.h>, and compile
  from the folder Ephymeris generated. A bare checkout, or a sketch that skips
  the include, stops here with an error rather than strobing numbers the app
  would decode under different names.

  Never compute a code from an index: the odor onsets run 101-109 and then
  114-116, because 110-113 are retired codes recorded sessions contain.
*/

#ifndef BOX_STROBES_H
#define BOX_STROBES_H

#ifndef BF_START_SESSION
#error "No strobe codes: they are generated by Ephymeris into TaskPins.h. Include \"TaskPins.h\" before <BehaviorBox.h> and build from the folder the app generated (docs/TASKS.md#strobe-vocabulary)."
#endif

#endif // BOX_STROBES_H
