"""Generate both wire-protocol mirrors from `schema.py`.

    python protocol/generate.py            # (re)write both mirrors
    python protocol/generate.py --check    # exit 1 if either committed mirror is stale

Emits:
    sidecar/ephymeris_sidecar/protocol.py  — names, envelope builders, runtime
                                             shape specs + validator
    src/lib/ws/protocol.ts                 — names, payload types, per-command
                                             args/result maps, envelope types

Stdlib-only on purpose: this must run from a bare interpreter (≥ 3.9) so the
frontend build can invoke it without the sidecar venv existing yet.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from wire_dsl import (  # noqa: E402
    Command,
    Event,
    Field,
    ListOf,
    Lit,
    MapOf,
    Obj,
    Prim,
    Protocol,
    Ref,
    Shape,
    Ty,
    UnionOf,
)
from schema import PROTOCOL  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
PY_OUT = REPO_ROOT / "sidecar" / "ephymeris_sidecar" / "protocol.py"
TS_OUT = REPO_ROOT / "src" / "lib" / "ws" / "protocol.ts"

GENERATED_NOTE = (
    "GENERATED by protocol/generate.py from protocol/schema.py — DO NOT EDIT.\n"
    "Regenerate with `npm run gen:protocol` (or `python protocol/generate.py`)."
)


# --- TypeScript emission ----------------------------------------------------


def ts_type(ty: Ty) -> str:
    if isinstance(ty, Prim):
        return {
            "str": "string",
            "int": "number",
            "float": "number",
            "bool": "boolean",
            "any": "unknown",
            "null": "null",
        }[ty.kind]
    if isinstance(ty, Lit):
        return " | ".join(f'"{v}"' for v in ty.values)
    if isinstance(ty, ListOf):
        item = ts_type(ty.item)
        return f"{item}[]" if " " not in item else f"Array<{item}>"
    if isinstance(ty, MapOf):
        return f"Record<string, {ts_type(ty.value)}>"
    if isinstance(ty, UnionOf):
        return " | ".join(ts_type(o) for o in ty.options)
    if isinstance(ty, Ref):
        return ty.name
    if isinstance(ty, Obj):
        parts = []
        for fld in ty.fields:
            opt = "?" if fld.optional else ""
            parts.append(f"{fld.name}{opt}: {ts_type(fld.ty)}")
        return "{ " + "; ".join(parts) + " }" if parts else "Record<string, never>"
    raise TypeError(f"unknown type node: {ty!r}")


def _ts_doc(doc: str, indent: str = "") -> list[str]:
    if len(doc) <= 96 - len(indent):
        return [f"{indent}/** {doc} */"]
    lines = [f"{indent}/**"]
    words, line = doc.split(), f"{indent} *"
    for word in words:
        if len(line) + len(word) + 1 > 98:
            lines.append(line)
            line = f"{indent} * {word}"
        else:
            line += f" {word}"
    lines.append(line)
    lines.append(f"{indent} */")
    return lines


def _ts_shape(shape: Shape) -> list[str]:
    out: list[str] = []
    if shape.doc:
        out.extend(_ts_doc(shape.doc))
    if isinstance(shape.ty, Obj):
        out.append(f"export interface {shape.name} {{")
        for fld in shape.ty.fields:
            if fld.doc:
                out.extend(_ts_doc(fld.doc, "  "))
            opt = "?" if fld.optional else ""
            out.append(f"  {fld.name}{opt}: {ts_type(fld.ty)};")
        out.append("}")
    else:
        out.append(f"export type {shape.name} = {ts_type(shape.ty)};")
    out.append("")
    return out


def emit_ts(protocol: Protocol) -> str:
    lines: list[str] = []
    push = lines.append

    push("/**")
    push(" * Canonical wire protocol between this frontend and the Python sidecar.")
    push(" *")
    for note_line in GENERATED_NOTE.split("\n"):
        push(f" * {note_line}")
    push(" *")
    push(" * `docs/websocket-protocol.md` carries the prose (rationale, lifecycle,")
    push(" * invariants); `protocol/schema.py` is the shape authority this file and")
    push(" * `sidecar/ephymeris_sidecar/protocol.py` are generated from.")
    push(" */")
    push("")
    push(f"export const PROTOCOL_VERSION = {protocol.version};")
    push("")

    push("// --- Commands (client -> server) -------------------------------------------")
    push("")
    push("export const CMD = {")
    for cmd in protocol.commands:
        if cmd.section:
            if lines[-1] != "export const CMD = {":
                push("")
            push(f"  // {cmd.section}")
        push(f'  {cmd.const}: "{cmd.name}",')
    push("} as const;")
    push("")
    push("export type CommandName = (typeof CMD)[keyof typeof CMD];")
    push("")

    push("// --- Events (server -> client) ---------------------------------------------")
    push("")
    push("export const EVT = {")
    for evt in protocol.events:
        push(f'  {evt.const}: "{evt.name}",')
    push("} as const;")
    push("")
    push("export type EventName = (typeof EVT)[keyof typeof EVT];")
    push("")

    push("// --- Error codes -----------------------------------------------------------")
    push("")
    push("export const ERR = {")
    for err in protocol.errors:
        push(f'  {err.name}: "{err.name}",')
    push("} as const;")
    push("")
    push("export type ErrorCode = (typeof ERR)[keyof typeof ERR];")
    push("")

    push("// --- Payload shapes --------------------------------------------------------")
    push("")
    for shape in protocol.shapes:
        lines.extend(_ts_shape(shape))

    push("// --- Per-command and per-event payload maps --------------------------------")
    push("")
    push("/** Args each command takes; `Record<string, never>` = none. */")
    push("export interface CommandArgsMap {")
    for cmd in protocol.commands:
        args = ts_type(cmd.args) if cmd.args is not None else "Record<string, never>"
        push(f'  "{cmd.name}": {args};')
    push("}")
    push("")
    push("/** The `result` field of each command's ok-reply. */")
    push("export interface CommandResultMap {")
    for cmd in protocol.commands:
        push(f'  "{cmd.name}": {ts_type(cmd.result)};')
    push("}")
    push("")
    push("/** The `data` field of each event. */")
    push("export interface EventDataMap {")
    for evt in protocol.events:
        push(f'  "{evt.name}": {ts_type(evt.data)};')
    push("}")
    push("")

    push(TS_STATIC_TAIL.rstrip("\n"))
    push("")
    return "\n".join(lines)


TS_STATIC_TAIL = """\
// --- Envelopes -------------------------------------------------------------

export interface CommandMessage {
  v: number;
  id: string;
  cmd: string;
  args: Record<string, unknown>;
}

export interface ProtocolError {
  code: ErrorCode | string;
  message: string;
  detail?: unknown;
}

export interface ReplyOk {
  v: number;
  corr: string;
  ok: true;
  result: unknown;
}

export interface ReplyErr {
  v: number;
  corr: string;
  ok: false;
  error: ProtocolError;
}

export type Reply = ReplyOk | ReplyErr;

export interface EventMessage {
  v: number;
  evt: string;
  ts: number;
  data: unknown;
  corr?: string;
}

export type ServerMessage = Reply | EventMessage;

export function isEvent(msg: ServerMessage): msg is EventMessage {
  return "evt" in msg;
}

export function isReply(msg: ServerMessage): msg is Reply {
  return "corr" in msg && "ok" in msg;
}

/** Thrown by `SidecarClient.call` when the sidecar rejects a command. */
export class SidecarCommandError extends Error {
  readonly code: string;
  readonly detail: unknown;

  constructor(error: ProtocolError) {
    super(error.message);
    this.name = "SidecarCommandError";
    this.code = error.code;
    this.detail = error.detail;
  }
}
"""


# --- Python emission --------------------------------------------------------


def py_spec(ty: Ty):
    """The runtime spec encoding `validate()` walks — nested tuples/strings."""
    if isinstance(ty, Prim):
        return ty.kind
    if isinstance(ty, Lit):
        return ("lit", tuple(ty.values))
    if isinstance(ty, ListOf):
        return ("list", py_spec(ty.item))
    if isinstance(ty, MapOf):
        return ("map", py_spec(ty.value))
    if isinstance(ty, UnionOf):
        return ("union", tuple(py_spec(o) for o in ty.options))
    if isinstance(ty, Ref):
        return ("ref", ty.name)
    if isinstance(ty, Obj):
        return ("obj", tuple((fld.name, py_spec(fld.ty), fld.optional) for fld in ty.fields))
    raise TypeError(f"unknown type node: {ty!r}")


def emit_py(protocol: Protocol) -> str:
    lines: list[str] = []
    push = lines.append

    push('"""Canonical wire protocol between the frontend and this sidecar.')
    push("")
    for note_line in GENERATED_NOTE.split("\n"):
        push(note_line)
    push("")
    push("`docs/websocket-protocol.md` carries the prose (rationale, lifecycle,")
    push("invariants); `protocol/schema.py` is the shape authority this module and")
    push("`src/lib/ws/protocol.ts` are generated from.")
    push("")
    push("Envelope shapes:")
    push("")
    push('    client -> server   {"v", "id", "cmd", "args"}')
    push('    server -> client   {"v", "corr", "ok": true,  "result"}      (reply)')
    push('                       {"v", "corr", "ok": false, "error"}       (reply)')
    push('                       {"v", "evt", "ts", "data", "corr"?}       (event)')
    push('"""')
    push("")
    push("from __future__ import annotations")
    push("")
    push("import os")
    push("import time")
    push("from typing import Any, Final")
    push("")
    push(f"PROTOCOL_VERSION: Final = {protocol.version}")
    push("")
    push("")
    push("# --- Commands (client -> server) ------------------------------------------")
    push("")
    push("class Cmd:")
    first = True
    for cmd in protocol.commands:
        if cmd.section:
            if not first:
                push("")
            push(f"    # {cmd.section}")
        push(f'    {cmd.const}: Final = "{cmd.name}"')
        first = False
    push("")
    push("")
    push("ALL_COMMANDS: Final[frozenset[str]] = frozenset(")
    push('    v for k, v in vars(Cmd).items() if not k.startswith("_") and isinstance(v, str)')
    push(")")
    push("")
    push("")
    push("# --- Events (server -> client) --------------------------------------------")
    push("")
    push("class Evt:")
    for evt in protocol.events:
        push(f'    {evt.const}: Final = "{evt.name}"')
    push("")
    push("")
    push("ALL_EVENTS: Final[frozenset[str]] = frozenset(")
    push('    v for k, v in vars(Evt).items() if not k.startswith("_") and isinstance(v, str)')
    push(")")
    push("")
    push("")
    push("# --- Error codes ----------------------------------------------------------")
    push("")
    push("class ErrCode:")
    for err in protocol.errors:
        push(f'    {err.name}: Final = "{err.name}"')
    push("")
    push("")
    push("ALL_ERROR_CODES: Final[frozenset[str]] = frozenset(")
    push('    v for k, v in vars(ErrCode).items() if not k.startswith("_") and isinstance(v, str)')
    push(")")
    push("")
    push("")
    push("# --- Payload shape specs --------------------------------------------------")
    push("#")
    push("# Runtime data for `validate()`. Encoding: a primitive is its name; every")
    push('# composite is a ("tag", ...) tuple — ("lit", values), ("list", item),')
    push('# ("map", value), ("union", options), ("ref", shape_name), and')
    push('# ("obj", ((field, spec, optional), ...)).')
    push("")
    push("SHAPES: Final[dict[str, Any]] = {")
    for shape in protocol.shapes:
        push(f'    "{shape.name}": {py_spec(shape.ty)!r},')
    push("}")
    push("")
    push("COMMAND_ARGS: Final[dict[str, Any]] = {")
    for cmd in protocol.commands:
        spec = py_spec(cmd.args) if cmd.args is not None else ("obj", ())
        push(f'    "{cmd.name}": {spec!r},')
    push("}")
    push("")
    push("COMMAND_RESULTS: Final[dict[str, Any]] = {")
    for cmd in protocol.commands:
        push(f'    "{cmd.name}": {py_spec(cmd.result)!r},')
    push("}")
    push("")
    push("EVENT_DATA: Final[dict[str, Any]] = {")
    for evt in protocol.events:
        push(f'    "{evt.name}": {py_spec(evt.data)!r},')
    push("}")
    push("")
    push("")
    push(PY_STATIC_TAIL.rstrip("\n"))
    push("")
    return "\n".join(lines)


PY_STATIC_TAIL = '''\
# --- Shape validation -------------------------------------------------------

class WireShapeError(AssertionError):
    """A payload does not match the shape `protocol/schema.py` declares."""


def wire_validation_enabled() -> bool:
    """Opt-in via EPHYMERIS_WIRE_VALIDATE=1 — the test suite turns it on.

    Off by default in production: a benign schema lag must never take down a
    live session over a payload the frontend would have rendered fine.
    """
    return os.environ.get("EPHYMERIS_WIRE_VALIDATE") == "1"


def validate(spec: Any, value: Any, path: str = "$") -> list[str]:
    """Structural check of `value` against a spec; returns problems, [] if ok.

    Deliberately strict in both directions: a *missing* required field and an
    *unknown* field are both errors, because either one is exactly the
    one-sided drift this exists to catch (TODO item 8).
    """
    errors: list[str] = []
    _check(spec, value, path, errors)
    return errors


def validate_command_args(cmd: str, args: Any) -> list[str]:
    spec = COMMAND_ARGS.get(cmd)
    if spec is None:
        return [f"unknown command: {cmd}"]
    return validate(spec, args if args is not None else {}, f"{cmd}.args")


def validate_command_result(cmd: str, result: Any) -> list[str]:
    spec = COMMAND_RESULTS.get(cmd)
    if spec is None:
        return [f"unknown command: {cmd}"]
    return validate(spec, result, f"{cmd}.result")


def validate_event_data(name: str, data: Any) -> list[str]:
    spec = EVENT_DATA.get(name)
    if spec is None:
        return [f"unknown event: {name}"]
    return validate(spec, data, f"{name}.data")


def _describe(value: Any) -> str:
    return "null" if value is None else type(value).__name__


def _check(spec: Any, value: Any, path: str, errors: list[str]) -> None:
    if isinstance(spec, str):
        if spec == "any":
            return
        ok = {
            "null": value is None,
            "str": isinstance(value, str),
            "bool": isinstance(value, bool),
            # bool is an int subclass, and a True on the wire where a count
            # belongs is exactly the sort of bug worth failing on.
            "int": isinstance(value, int) and not isinstance(value, bool),
            "float": isinstance(value, (int, float)) and not isinstance(value, bool),
        }[spec]
        if not ok:
            errors.append(f"{path}: expected {spec}, got {_describe(value)}")
        return

    tag = spec[0]
    if tag == "lit":
        if value not in spec[1]:
            errors.append(f"{path}: {value!r} not one of {list(spec[1])}")
    elif tag == "list":
        if not isinstance(value, list):
            errors.append(f"{path}: expected list, got {_describe(value)}")
            return
        for index, item in enumerate(value):
            _check(spec[1], item, f"{path}[{index}]", errors)
    elif tag == "map":
        if not isinstance(value, dict):
            errors.append(f"{path}: expected object, got {_describe(value)}")
            return
        for key, item in value.items():
            if not isinstance(key, str):
                errors.append(f"{path}: non-string key {key!r}")
                continue
            _check(spec[1], item, f"{path}.{key}", errors)
    elif tag == "union":
        # Valid if any arm accepts; report the closest-fitting arm's problems.
        best: list[str] | None = None
        for option in spec[1]:
            attempt: list[str] = []
            _check(option, value, path, attempt)
            if not attempt:
                return
            if best is None or len(attempt) < len(best):
                best = attempt
        errors.extend(best or [f"{path}: matches no union arm"])
    elif tag == "ref":
        _check(SHAPES[spec[1]], value, path, errors)
    elif tag == "obj":
        if not isinstance(value, dict):
            errors.append(f"{path}: expected object, got {_describe(value)}")
            return
        fields = {name: (field_spec, optional) for name, field_spec, optional in spec[1]}
        for name, (field_spec, optional) in fields.items():
            if name not in value:
                if not optional:
                    errors.append(f"{path}: missing required field `{name}`")
                continue
            _check(field_spec, value[name], f"{path}.{name}", errors)
        for name in value:
            if name not in fields:
                errors.append(f"{path}: unknown field `{name}`")
    else:  # pragma: no cover - unreachable with generated specs
        errors.append(f"{path}: malformed spec {spec!r}")


# --- Envelope builders ----------------------------------------------------

def reply_ok(corr: str, result: Any = None) -> dict[str, Any]:
    return {"v": PROTOCOL_VERSION, "corr": corr, "ok": True, "result": result}


def reply_err(
    corr: str, code: str, message: str, detail: Any = None
) -> dict[str, Any]:
    return {
        "v": PROTOCOL_VERSION,
        "corr": corr,
        "ok": False,
        "error": {"code": code, "message": message, "detail": detail},
    }


def event(name: str, data: Any = None, corr: str | None = None) -> dict[str, Any]:
    if wire_validation_enabled():
        problems = validate_event_data(name, data)
        if problems:
            raise WireShapeError(
                f"event `{name}` payload violates protocol/schema.py:\\n  "
                + "\\n  ".join(problems)
            )
    msg: dict[str, Any] = {
        "v": PROTOCOL_VERSION,
        "evt": name,
        "ts": time.time(),
        "data": data,
    }
    if corr is not None:
        msg["corr"] = corr
    return msg
'''


# --- CLI -------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed mirrors match the schema instead of writing",
    )
    options = parser.parse_args()

    outputs = {
        PY_OUT: emit_py(PROTOCOL),
        TS_OUT: emit_ts(PROTOCOL),
    }

    if options.check:
        stale = []
        for path, wanted in outputs.items():
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current != wanted:
                stale.append(path)
        if stale:
            names = ", ".join(str(p.relative_to(REPO_ROOT)) for p in stale)
            print(
                f"stale generated mirror(s): {names}\n"
                "run `npm run gen:protocol` (or `python protocol/generate.py`) "
                "and commit the result",
                file=sys.stderr,
            )
            return 1
        print("protocol mirrors are current")
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
