/* GENERATED by taskgraph/emit/c_table.py — DO NOT EDIT.
 *
 * spec:     grgl_2odor_asbuilt
 * hash:     12ac3c2d5b188003
 * template: four_epoch v1 (1321191e6c93f7b8)
 *
 * The equivalence gate needs both implementations walking the same table.
 * Hand-transcribing it into the test would be a third copy that can drift,
 * and a drift there looks exactly like an interpreter bug.
 */

#include <TgInterpret.h>

/*  Timing indices by name. A harness that rewrites a ramped entry -- which is
 *  how the stage schedule and the abstention escalator both work -- should
 *  address it by name. A magic number here would silently point at the wrong
 *  duration the moment a spec adds a timing entry above it. */
#define TG_IDX_ZERO 0
#define TG_IDX_ARM 1
#define TG_IDX_ENGAGE_WIN 2
#define TG_IDX_COMMIT_HOLD 3
#define TG_IDX_SAMPLE_HOLD 4
#define TG_IDX_RESP_WIN 5
#define TG_IDX_RESP_HOLD 6
#define TG_IDX_REWARD_L 7
#define TG_IDX_REWARD_R 8
#define TG_IDX_ITI_CORRECT 9
#define TG_IDX_PEN_ERROR 10
#define TG_IDX_PEN_BREAK 11
#define TG_IDX_PEN_NOENGAGE 12
#define TG_IDX_POLL_INTERVAL 13

static const TgTable TG_TABLE = {
  /* nodes */ {
    {0, 1, 0xFFFF, 0, 0, 1, 0},  /* S00 arm & pre-load */
    {1, 2, 0x00DE, 1, 1, 1, 1},  /* S01 engagement window */
    {0, 0, 0x00E9, 0, 2, 2, 3},  /* S02 cue off */
    {0, 12, 0x00DF, 0, 4, 0, 4},  /* S03 no engage */
    {5, 0, 0x00EA, 0, 4, 0, 5},  /* S04 TRIAL_REPEAT */
    {0, 0, 0x00E9, 0, 4, 3, 7},  /* S05 cue off */
    {0, 11, 0x00E1, 0, 7, 0, 8},  /* S06 hold break */
    {2, 3, 0x00E0, 1, 7, 0, 9},  /* S07 commitment hold */
    {2, 4, 0xFF00, 1, 7, 1, 11},  /* S08 present stimulus */
    {3, 0, 0x00F7, 1, 8, 2, 13},  /* S09 sampling release */
    {0, 0, 0x00E2, 0, 10, 0, 14},  /* S10 withdrawal */
    {0, 0, 0x00E9, 0, 10, 1, 15},  /* S11 cue off */
    {1, 5, 0xFFFF, 6, 11, 0, 16},  /* S12 response window */
    {0, 0, 0xFF04, 0, 11, 0, 19},  /* S13 response registered */
    {0, 10, 0xFFFF, 0, 11, 0, 21},  /* S14 omission */
    {0, 0, 0x00F3, 0, 11, 0, 22},  /* S15 incorrect — scored */
    {5, 0, 0xFFFF, 0, 11, 0, 24},  /* S16 TRIAL_ADVANCE */
    {2, 6, 0xFFFF, 0, 11, 0, 26},  /* S17 response hold */
    {0, 10, 0xFF05, 0, 11, 0, 28},  /* S18 wrong */
    {0, 11, 0xFF06, 0, 11, 0, 29},  /* S19 hold fail */
    {4, 255, 0xFF08, 0, 11, 1, 30},  /* S20 reward delivery */
    {3, 0, 0xFF09, 0, 12, 1, 31},  /* S21 consumption */
    {0, 9, 0xFF0A, 0, 13, 0, 32},  /* S22 correct */
    {0, 0, 0x00F2, 0, 13, 0, 33},  /* S23 correct — scored */
  },
  /* edges */ {
    {0, 0, 1, 0},  /*  0: TIMEOUT -> S01 */
    {1, 0, 7, 0},  /*  1: ENTER -> S07 */
    {0, 0, 2, 0},  /*  2: TIMEOUT -> S02 */
    {0, 0, 3, 0},  /*  3: TIMEOUT -> S03 */
    {0, 0, 4, 0},  /*  4: TIMEOUT -> S04 */
    {6, 0, 0, 0},  /*  5: ADVANCE -> S00 */
    {7, 0, 0, 0},  /*  6: REPEAT -> S00 */
    {0, 0, 6, 0},  /*  7: TIMEOUT -> S06 */
    {0, 0, 4, 0},  /*  8: TIMEOUT -> S04 */
    {2, 0, 8, 0},  /*  9: HELD -> S08 */
    {3, 0, 5, 0},  /* 10: BROKEN -> S05 */
    {3, 0, 5, 0},  /* 11: BROKEN -> S05 */
    {2, 0, 9, 0},  /* 12: HELD -> S09 */
    {4, 0, 10, 0},  /* 13: EXIT -> S10 */
    {0, 0, 11, 0},  /* 14: TIMEOUT -> S11 */
    {0, 0, 12, 0},  /* 15: TIMEOUT -> S12 */
    {1, 0, 13, 0},  /* 16: ENTER -> S13 */
    {1, 0, 13, 0},  /* 17: ENTER -> S13 */
    {0, 0, 14, 0},  /* 18: TIMEOUT -> S14 */
    {0, 1, 17, 0},  /* 19: TIMEOUT [ch == @target] -> S17 */
    {0, 0, 18, 0},  /* 20: TIMEOUT -> S18 */
    {0, 0, 15, 0},  /* 21: TIMEOUT -> S15 */
    {0, 2, 4, 2},  /* 22: TIMEOUT [correction budget] -> S04 */
    {0, 0, 16, 1},  /* 23: TIMEOUT -> S16 */
    {6, 0, 0, 0},  /* 24: ADVANCE -> S00 */
    {7, 0, 0, 0},  /* 25: REPEAT -> S00 */
    {3, 0, 19, 0},  /* 26: BROKEN -> S19 */
    {2, 0, 20, 0},  /* 27: HELD -> S20 */
    {0, 0, 15, 0},  /* 28: TIMEOUT -> S15 */
    {0, 0, 15, 0},  /* 29: TIMEOUT -> S15 */
    {5, 0, 21, 0},  /* 30: DONE -> S21 */
    {4, 0, 22, 0},  /* 31: EXIT -> S22 */
    {0, 0, 23, 0},  /* 32: TIMEOUT -> S23 */
    {0, 0, 16, 1},  /* 33: TIMEOUT -> S16 */
  },
  /* timing */ {0, 1000, 4000, 500, 500, 2000, 200, 100, 100, 4000, 20000, 10000, 6000, 5},
  /* actions */ {
    {240, 1},  /* set @stim[0].emitter */
    {36, 1},  /* set trial_light */
    {36, 0},  /* clear trial_light */
    {240, 0},  /* clear @stim[0].emitter */
    {36, 0},  /* clear trial_light */
    {40, 0},  /* clear vacuum */
    {245, 0},  /* clear @stim[$stage].emitter */
    {40, 1},  /* set vacuum */
    {40, 0},  /* clear vacuum */
    {240, 0},  /* clear @stim[0].emitter */
    {36, 0},  /* clear trial_light */
    {244, 1},  /* set @target.reward_line */
    {244, 0},  /* clear @target.reward_line */
  },
  /* trialTypes */ {
    {0, 255, 255, 255, 1, 1, 46, 8},  /* go_right */
    {1, 255, 255, 255, 0, 1, 42, 7},  /* go_left */
  },
  /* ports */ {
    {4, 42, 248, 257, 250, 254, 252, 369, 7, 0},  /* left_well */
    {3, 46, 249, 258, 251, 255, 253, 357, 8, 0},  /* right_well */
  },
  /* stimuli */ {
    {22, 0, 101},  /* odor1 */
    {26, 0, 103},  /* odor3 */
  },
  /* watchPin  */ {2, 3, 4, 255, 255, 255, 255, 255},
  /* watchPort */ {255, 1, 0, 255, 255, 255, 255, 255},
  24, 34, 14, 13,
  2, 2, 2, 3,
};
