/* GENERATED by taskgraph/emit/c_table.py — DO NOT EDIT.
 *
 * spec:     two_afc
 * hash:     f0408f3db39d71e9
 * template: four_epoch v2 (f0760c460092ddb3)
 *
 * The equivalence gate needs both implementations walking the same table.
 * Hand-transcribing it into the test would be a third copy that can drift,
 * and a drift there looks exactly like an interpreter bug.
 */

#include <TgInterpret.h>

/*  Timing indices by name. A harness that rewrites a ramped entry -- which is
 *  how the stage schedule and the abstention escalator both work -- should
 *  address it by name. A magic number here would silently point at the wrong
 *  duration the moment a spec adds a timing entry above it. */
#define TG_IDX_ZERO 0
#define TG_IDX_ARM 1
#define TG_IDX_ENGAGE_WIN 2
#define TG_IDX_POLL_INTERVAL 3
#define TG_IDX_COMMIT_HOLD 4
#define TG_IDX_SAMPLE_HOLD 5
#define TG_IDX_RESP_WIN 6
#define TG_IDX_RESP_HOLD 7
#define TG_IDX_ITI_CORRECT 8
#define TG_IDX_PEN_BREAK 9
#define TG_IDX_PEN_NOENGAGE 10
#define TG_IDX_PEN_ERROR 11
#define TG_IDX_REWARD_RIGHT 12
#define TG_IDX_REWARD_LEFT 13

static const TgTable TG_TABLE = {
  /* nodes */ {
    {0, 1, 0xFFFF, 0, 0, 1, 0},  /* S00 arm & pre-load */
    {1, 2, 0x00DE, 1, 1, 1, 1},  /* S01 engagement window */
    {0, 0, 0x00DF, 0, 2, 0, 3},  /* S02 no engage */
    {0, 0, 0x00E9, 0, 2, 2, 4},  /* S03 cue off */
    {0, 10, 0xFFFF, 0, 4, 0, 5},  /* S04 no engage penalty */
    {5, 0, 0x00EA, 0, 4, 0, 6},  /* S05 TRIAL_REPEAT */
    {2, 4, 0x00E0, 1, 4, 0, 8},  /* S06 commitment hold */
    {0, 0, 0x00E1, 0, 4, 0, 10},  /* S07 hold break */
    {0, 0, 0x00E9, 0, 4, 3, 11},  /* S08 cue off */
    {0, 9, 0xFFFF, 0, 7, 0, 12},  /* S09 hold break penalty */
    {2, 5, 0xFF00, 1, 7, 1, 13},  /* S10 present stimulus */
    {3, 0, 0x00F7, 1, 8, 2, 15},  /* S11 sampling release */
    {0, 0, 0x00E2, 0, 10, 0, 16},  /* S12 withdrawal */
    {0, 0, 0x00E9, 0, 10, 1, 17},  /* S13 cue off */
    {1, 6, 0xFFFF, 6, 11, 0, 18},  /* S14 response window */
    {0, 0, 0xFF04, 0, 11, 0, 21},  /* S15 response registered */
    {0, 11, 0x0106, 0, 11, 0, 23},  /* S16 omission */
    {0, 0, 0x00F3, 0, 11, 0, 24},  /* S17 incorrect — scored */
    {5, 0, 0xFFFF, 0, 11, 0, 26},  /* S18 TRIAL_ADVANCE */
    {2, 7, 0xFFFF, 0, 11, 0, 28},  /* S19 response hold */
    {0, 11, 0xFF05, 0, 11, 0, 30},  /* S20 wrong */
    {0, 9, 0xFF06, 0, 11, 0, 31},  /* S21 hold fail */
    {4, 255, 0xFF08, 0, 11, 1, 32},  /* S22 reward delivery */
    {3, 0, 0xFF09, 0, 12, 1, 33},  /* S23 consumption */
    {0, 8, 0xFF0A, 0, 13, 0, 34},  /* S24 correct */
    {0, 0, 0x00F2, 0, 13, 0, 35},  /* S25 correct — scored */
  },
  /* edges */ {
    {0, 0, 1, 0},  /*  0: TIMEOUT -> S01 */
    {1, 0, 6, 0},  /*  1: ENTER -> S06 */
    {0, 0, 2, 0},  /*  2: TIMEOUT -> S02 */
    {0, 0, 3, 0},  /*  3: TIMEOUT -> S03 */
    {0, 0, 4, 0},  /*  4: TIMEOUT -> S04 */
    {0, 0, 5, 0},  /*  5: TIMEOUT -> S05 */
    {6, 0, 0, 0},  /*  6: ADVANCE -> S00 */
    {7, 0, 0, 0},  /*  7: REPEAT -> S00 */
    {2, 0, 10, 0},  /*  8: HELD -> S10 */
    {3, 0, 7, 0},  /*  9: BROKEN -> S07 */
    {0, 0, 8, 0},  /* 10: TIMEOUT -> S08 */
    {0, 0, 9, 0},  /* 11: TIMEOUT -> S09 */
    {0, 0, 5, 0},  /* 12: TIMEOUT -> S05 */
    {3, 0, 7, 0},  /* 13: BROKEN -> S07 */
    {2, 0, 11, 0},  /* 14: HELD -> S11 */
    {4, 0, 12, 0},  /* 15: EXIT -> S12 */
    {0, 0, 13, 0},  /* 16: TIMEOUT -> S13 */
    {0, 0, 14, 0},  /* 17: TIMEOUT -> S14 */
    {1, 0, 15, 0},  /* 18: ENTER -> S15 */
    {1, 0, 15, 0},  /* 19: ENTER -> S15 */
    {0, 0, 16, 0},  /* 20: TIMEOUT -> S16 */
    {0, 1, 19, 0},  /* 21: TIMEOUT [ch == @target] -> S19 */
    {0, 0, 20, 0},  /* 22: TIMEOUT -> S20 */
    {0, 0, 17, 0},  /* 23: TIMEOUT -> S17 */
    {0, 2, 5, 2},  /* 24: TIMEOUT [correction budget] -> S05 */
    {0, 0, 18, 1},  /* 25: TIMEOUT -> S18 */
    {6, 0, 0, 0},  /* 26: ADVANCE -> S00 */
    {7, 0, 0, 0},  /* 27: REPEAT -> S00 */
    {3, 0, 21, 0},  /* 28: BROKEN -> S21 */
    {2, 0, 22, 0},  /* 29: HELD -> S22 */
    {0, 0, 17, 0},  /* 30: TIMEOUT -> S17 */
    {0, 0, 17, 0},  /* 31: TIMEOUT -> S17 */
    {5, 0, 23, 0},  /* 32: DONE -> S23 */
    {4, 0, 24, 0},  /* 33: EXIT -> S24 */
    {0, 0, 25, 0},  /* 34: TIMEOUT -> S25 */
    {0, 0, 18, 1},  /* 35: TIMEOUT -> S18 */
  },
  /* timing */ {0, 1000, 4000, 5, 500, 500, 2000, 200, 4000, 10000, 6000, 20000, 100, 100},
  /* actions */ {
    {240, 1},  /* set @stim[0].emitter */
    {36, 1},  /* set trial_light */
    {36, 0},  /* clear trial_light */
    {240, 0},  /* clear @stim[0].emitter */
    {36, 0},  /* clear trial_light */
    {40, 0},  /* clear vacuum */
    {245, 0},  /* clear @stim[$stage].emitter */
    {40, 1},  /* set vacuum */
    {40, 0},  /* clear vacuum */
    {240, 0},  /* clear @stim[0].emitter */
    {36, 0},  /* clear trial_light */
    {244, 1},  /* set @target.reward_line */
    {244, 0},  /* clear @target.reward_line */
  },
  /* trialTypes */ {
    {0, 255, 255, 255, 0, 1, 46, 12},  /* tt_odor1_right_well */
    {1, 255, 255, 255, 1, 1, 42, 13},  /* tt_odor2_left_well */
  },
  /* ports */ {
    {3, 46, 249, 258, 251, 255, 253, 357, 12, 0},  /* right_well */
    {4, 42, 248, 257, 250, 254, 252, 369, 13, 0},  /* left_well */
  },
  /* stimuli */ {
    {22, 0, 101},  /* odor1 */
    {24, 0, 102},  /* odor2 */
  },
  /* stageRows */ {
  },
  /* timingSets */ {
  },
  /* maxDwell */ {1000, 4000, 0, 0, 6000, 0, 500, 0, 0, 10000, 500, 0, 0, 0, 2000, 0, 20000, 0, 0, 200, 20000, 10000, 100, 0, 4000, 0},
  /* watchPin  */ {2, 3, 4, 255, 255, 255, 255, 255},
  /* watchPort */ {255, 0, 1, 255, 255, 255, 255, 255},
  /* specHash */ 0xF0408F3D, /* tableCrc */ 0,
  26, 36, 14, 13,
  2, 2, 2, 3,
  0, 0,
  /* valid */ true, /* _pad */ 0,
};
