"""A task definition + this rig's wiring -> a compilable sketch folder.

Four files, and which of them a value lands in is decided by whether it fits on
a `START` line (`TASKS.md#two-places-a-value-can-come-from`):

    <name>.ino      the root GRGL sketch, copied verbatim from the bundle
    TaskPins.h      pins, strobe codes, counts, selection mode  (preprocessor)
    TaskTrials.h    the trial table                             (needs TrialType)
    task.json       the profile the app itself reads

NOTHING HERE INVENTS A VALUE. Every pin comes from the composed channel map,
every strobe code from the vocabulary, every field label from `fields.py`, and
every number from the definition or that catalogue's default. A defaults table
in this file would be a second answer to a question the registries already
answer, which is exactly the mirroring the whole arrangement exists to end.

THE GENERATED FOLDER IS A BUILD OUTPUT. It is rewritten whole on every save and
on every `hardware.save`, because a wiring change moves pins the headers carry.
Nothing may be hand-edited there and survive.
"""

from __future__ import annotations

import json
from typing import Any

from ..rig import registry
from ..tasks import profile as task_profile
from . import fields
from .model import TaskDefinition, TrialTypeDef

#: `TrialType`'s no-go sentinel, mirrored from BehaviorBox.h. A no-go type has
#: no correct port and no reward index, and -1 is what the runner tests against.
SENTINEL = "SENTINEL"

_GENERATED_BANNER = (
    "/*  GENERATED by Ephymeris -- do not edit.\n"
    "\n"
    "    Rewritten whole every time this task profile is saved, and again\n"
    "    whenever the rig's wiring changes, because the pin numbers below come\n"
    "    from that wiring. Edit the profile on the Task tab, or the wiring on\n"
    "    the Rig tab; an edit here is lost at the next save without a word.\n"
    "\n"
    "    Task:    {name}\n"
    "    Wiring:  {pinout} ({pinout_hash})\n"
    "*/\n"
)


# --------------------------------------------------------------------------- #
# The generated profile (task.json)
# --------------------------------------------------------------------------- #


def profile_json(definition: TaskDefinition) -> dict[str, Any]:
    """The `task.json` this profile compiles to.

    Assembled from the field catalogue, the definition's values, and the strobe
    vocabulary. The three count-dependent families are expanded here because
    only the definition knows how many of each there are: one ramp group per
    stage row, one pool weight per trial type, one reward volume per go trial
    type.
    """
    channels = registry.channels()
    vocab = registry.vocabulary()

    config: list[dict[str, Any]] = []
    for raw in fields.SCALAR_FIELDS:
        field = dict(raw)
        if field["metadataKey"] == "lazy_escalation_stage":
            # Offering stage 4 on a two-row ramp offers two rows that cannot
            # engage, and the firmware clamps the value back without saying so.
            field["max"] = max(0, definition.stage_count - 1)
        config.append(_with_value(field, definition))

    config.extend(_reward_fields(definition))
    config.extend(_pool_fields(definition))
    config.extend(_stage_fields(definition))

    strobes = _strobe_map(definition, channels, vocab)
    return {
        "taskName": definition.name,
        "kind": "behavior",
        "config": config,
        "strobes": strobes,
        "liveMetrics": _live_metrics(definition, channels, vocab),
        "legacyNames": list(definition.legacy_names),
    }


def build_profile(definition: TaskDefinition) -> task_profile.TaskProfile:
    """The generated profile, parsed by the same code that reads a sketch's own.

    Round-tripping through `parse_profile` rather than constructing a
    `TaskProfile` directly is deliberate: it means a generated profile is
    subject to every check an authored one is — duplicate wire keys, a reserved
    key, a default of the wrong type — instead of trusting this file to be
    right.
    """
    return task_profile.parse_profile(profile_json(definition))


def _with_value(field: dict[str, Any], definition: TaskDefinition) -> dict[str, Any]:
    """Apply the profile's own value, leaving the catalogue's as the fallback.

    `params` holds only what diverges, so a field the operator never touched
    tracks the catalogue — which is what lets a help-text or range change reach
    every saved profile.
    """
    key = field["metadataKey"]
    if key in definition.params:
        field = dict(field)
        field["default"] = definition.params[key]
    return field


def _reward_fields(definition: TaskDefinition) -> list[dict[str, Any]]:
    """One reward volume per GO trial type, in table order.

    THE SAME CONTRACT AS THE POOL WEIGHTS: slot i is `rewardTimes[i]` is wire
    key RW<i+1> is `kTrials[i]`, and the value lives on the row rather than in
    `params` for the same reason — it is a property of that condition. So the
    default here is read off the row, never merged through `_with_value`: a
    `params` entry for a reward key could outlive the row it described, and the
    row is the one place the editor lets it be typed.

    A no-go row pays nothing and gets no field. Its slot still has a wire key
    in `TaskPins.h`, so the key list pairs with `BOX_MAX_TRIAL_TYPES` exactly
    like the pool list; a key that is never sent simply leaves the compiled 0.
    """
    out: list[dict[str, Any]] = []
    for i, trial in enumerate(definition.trials):
        if not trial.is_go:
            continue
        label = trial.label or f"{trial.odor_channel.replace('_', ' ')}"
        out.append({
            "metadataKey": f"reward_time_{i + 1}",
            "wireKey": f"{fields.REWARD_WIRE_KEY}{i + 1}",
            "label": f"Reward — {label}",
            "type": "int",
            "default": trial.reward_time,
            "group": "Reward volume",
            "unit": "ms",
            "min": 0,
            "max": 5000,
            "step": 10,
            "help": (
                "Solenoid open time when this condition is answered correctly — "
                "its reward volume. Overrides the trial-table row for this run."
            ),
        })
    return out


def _pool_fields(definition: TaskDefinition) -> list[dict[str, Any]]:
    """One weight per trial type, in table order.

    THE ORDER IS THE CONTRACT: slot i is `poolWeights[i]` is wire key PW<i+1> is
    `kTrials[i]`. Reordering the table silently re-weights a pool task, so the
    generator emits the weights and the table from one loop over the same list.

    The weight lives on the trial type rather than in `params` because it is a
    property of that row — deleting a trial type must take its weight with it,
    and a `params` entry would outlive the row it described.
    """
    out: list[dict[str, Any]] = []
    # Plain anti-bias draws a side and weights nothing; the other two modes
    # read the weights. Only where they are read are they worth a front-row
    # field -- under anti-bias they fold behind the advanced disclosure so the
    # quick-tune strip does not promote a knob that does nothing.
    ignored = definition.selection_mode == "antibias"
    if ignored:
        help_text = (
            "Relative share of trials presenting this type. "
            "Ignored while anti-bias selection is on."
        )
    elif definition.selection_mode == "weighted":
        help_text = (
            "This type's share of the trials on ITS side — anti-bias still "
            "balances the sides. Raise it for a stimulus the animal is still "
            "learning; lower it again once learned."
        )
    else:
        help_text = "Relative share of trials presenting this type."
    for i, trial in enumerate(definition.trials):
        label = trial.label or f"{trial.odor_channel.replace('_', ' ')}"
        field: dict[str, Any] = {
            "metadataKey": f"pool_weight_{i + 1}",
            "wireKey": f"{fields.POOL_WIRE_KEY}{i + 1}",
            "label": f"Weight — {label}",
            "type": "int",
            "default": trial.weight,
            "group": "Trial pool",
            "min": 0,
            "max": 100,
            "step": 1,
            "help": help_text,
        }
        if ignored:
            field["advanced"] = True
        out.append(field)
    return out


def _stage_fields(definition: TaskDefinition) -> list[dict[str, Any]]:
    """The ramp, as one group per row.

    A single field per ramped value would appear to work and then be silently
    overwritten at the first stage boundary — the firmware rewrites all four
    from `stage[]` on every completed trial. So each row is declared in full.

    Row 0 keeps the plain metadata keys (`odor_poke_hold`) and omits its `T`
    field: it is live from trial 0 by construction, and `liveStage()` never
    reads its count. A one-row profile therefore declares exactly the four holds
    and calls the group "Holds & windows" rather than "Stage 0", because there
    is no stage to distinguish.
    """
    out: list[dict[str, Any]] = []
    ramped = len(definition.stages) > 1

    for index, stage in enumerate(definition.stages):
        group = f"Stage {index}" if ramped else "Holds & windows"
        suffix = f"_{index}" if index > 0 else ""

        if index > 0:
            row = dict(fields.STAGE_TRIALS_FIELD)
            row["metadataKey"] = f"stage_trials{suffix}"
            row["wireKey"] = f"S{index}T"
            row["group"] = group
            row["default"] = stage.trials
            out.append(row)

        for spec in fields.RAMPED_FIELDS:
            row = dict(spec)
            key = spec["metadataKey"]
            row["metadataKey"] = f"{key}{suffix}"
            row["wireKey"] = f"S{index}{spec['wireKey']}"
            row["group"] = group
            row["default"] = getattr(stage, _STAGE_ATTR[key])
            out.append(row)
    return out


_STAGE_ATTR = {
    "odor_poke_hold": "odor_poke_hold",
    "fluid_well_hold": "fluid_well_hold",
    "fluid_well_poll": "fluid_well_poll",
    "odor_port_timeout": "odor_port_timeout",
}


def _strobe_map(definition, channels, vocab) -> dict[str, str]:
    """`code -> name` for everything this task can emit.

    THE STRUCTURAL CODES ARE ALWAYS DECLARED, whether or not this particular
    task reaches them: the trial runner emits them unconditionally, and a code
    the profile omits arrives as an unlabelled number. What varies is the
    stimulus onsets (one per declared trial type) and the per-port families
    (resolved through each response port's SLOT, never through its name).
    """
    out: dict[str, str] = {}

    for name in _STRUCTURAL_STROBES:
        entry = vocab.get(name)
        if entry is not None:
            out[str(entry.code)] = name

    for trial in definition.trials:
        entry = vocab.get(trial.onset_strobe)
        if entry is not None:
            out[str(entry.code)] = trial.onset_strobe

    # Every response port the rig HAS, not only the ones this task answers at:
    # a wrong-well poke on an unused port is still recorded, and an unlabelled
    # error code is the hardest kind to read back.
    for port in channels.of_kind("response"):
        slot = vocab.port_slot(port.port_slot) if port.port_slot else None
        if not slot:
            continue
        for code_name in slot.values():
            entry = vocab.get(code_name)
            if entry is not None:
                out[str(entry.code)] = code_name

    return dict(sorted(out.items(), key=lambda kv: int(kv[0])))


#: Emitted by `runTrial()` and the session loop regardless of the trial table.
_STRUCTURAL_STROBES: tuple[str, ...] = (
    "START_SESSION", "LIGHTS_ON", "LAZY_RAT", "ODOR_POKE", "ODOR_UNPOKE_EARLY",
    "ODOR_UNPOKE", "LIGHTS_OFF", "INVALID_TRIAL", "END_CORRECT_ITI",
    "END_INCORRECT_ITI", "END_SESSION", "ODOR_OFF", "WATER_POKE_NONE",
    "RESP_OMIT",
)


def _live_metrics(definition, channels, vocab) -> list[dict[str, Any]]:
    """One rolling P(correct | stimulus) per go trial type.

    ALSO THE GATE ON THE STATE-MACHINE DRAWING. `topology.ts` gives a stimulus
    an arm only when a live metric scores it, precisely so that a profile
    declaring twelve odor codes and presenting two draws two branches rather
    than twelve. So this is not only the charts — it is what makes the diagram
    describe the task rather than the vocabulary.

    A no-go type is scored against `WATER_POKE_NONE`, which is the same
    arrangement: the withhold arm appears only when something scores it.
    """
    out: list[dict[str, Any]] = []
    for i, trial in enumerate(definition.trials):
        onset = vocab.get(trial.onset_strobe)
        if onset is None:
            continue
        # The operator's name for the condition, which TSK110 requires them to
        # give: it is what titles the sparkline, the learning curve and the
        # strategy axis. The channel fallback survives only so a half-finished
        # definition still compiles for the preview — a saved one carries a name.
        stimulus = trial.label.strip() or trial.odor_channel.replace("_", " ")

        if not trial.is_go:
            withheld = vocab.get("WATER_POKE_NONE")
            if withheld is None:
                continue
            # The alternate is "answered at all", and any port will do: the
            # trial is already wrong the moment one is chosen.
            answered = _first_enter_code(channels, vocab)
            if answered is None:
                continue
            out.append({
                "id": f"p_withhold_{i + 1}",
                "label": f"P(withhold | {stimulus})",
                "triggerCode": onset.code,
                "successCode": withheld.code,
                "alternateCode": answered,
                "windowSize": 20,
            })
            continue

        port = channels.get(trial.response_channel) if trial.response_channel else None
        slot = vocab.port_slot(port.port_slot) if port and port.port_slot else None
        if not slot:
            continue
        success = vocab.get(slot["enter_code"])
        alternate = _other_enter_code(channels, vocab, port.name)
        if success is None or alternate is None:
            continue
        out.append({
            "id": f"p_correct_{i + 1}",
            "label": f"P({port.name.replace('_', ' ')} | {stimulus})",
            "triggerCode": onset.code,
            "successCode": success.code,
            "alternateCode": alternate,
            "windowSize": 20,
        })
    return out


def _first_enter_code(channels, vocab) -> int | None:
    for port in channels.of_kind("response"):
        slot = vocab.port_slot(port.port_slot) if port.port_slot else None
        entry = vocab.get(slot["enter_code"]) if slot else None
        if entry is not None:
            return entry.code
    return None


def _other_enter_code(channels, vocab, exclude: str) -> int | None:
    """The poke that means "went somewhere else".

    A metric needs a boundary: without an alternate, an unanswered trial is
    never resolved and the rolling window silently stops advancing.
    """
    for port in channels.of_kind("response"):
        if port.name == exclude:
            continue
        slot = vocab.port_slot(port.port_slot) if port.port_slot else None
        entry = vocab.get(slot["enter_code"]) if slot else None
        if entry is not None:
            return entry.code
    return None


# --------------------------------------------------------------------------- #
# The generated firmware
# --------------------------------------------------------------------------- #


def bundled_pins_h(sketch_name: str) -> str:
    """This rig's pins, for a BUNDLED sketch that asked to be rebuilt.

    Pins only. A bundled sketch has no trial table, no ramp and no selection
    mode — those are what a task PROFILE adds — and emitting counts it does not
    use would be inventing a shape for it.

    NO STROBE OVERRIDES EITHER, though `task_pins_h` emits them. A profile can
    reference a code the app added after the firmware was built; a bundled
    sketch only ever references codes its own `BoxStrobes.h` defines, and those
    two are pinned to each other by `tests/test_taskdef.py`. A second source for
    the same numbers would buy nothing and could disagree.
    """
    channels = registry.channels()
    lines = [
        "/*  GENERATED by Ephymeris -- do not edit.",
        "",
        "    A rebuild of the bundled sketch against THIS RIG'S wiring, served in",
        "    place of the one that ships. Rewritten whenever the wiring changes;",
        "    an edit here is lost at the next change without a word.",
        "",
        f"    Sketch:  {sketch_name}",
        f"    Wiring:  {channels.pinout_id} ({channels.content_hash()})",
        "*/",
        "",
        "#ifndef TASK_PINS_H",
        "#define TASK_PINS_H",
        "",
        "/*  Every one of these overrides a guarded default in BoxPins.h. A channel",
        "    the rig does not declare is simply not mentioned and keeps the shipped",
        "    number, so a partial wiring document degrades one pin at a time. */",
    ]
    for name, macro in _PIN_MACROS:
        channel = channels.get(name)
        if channel is not None:
            lines.append(f"#define {macro} {channel.index}")
    lines += _sync_lines(channels)

    # Declaration order, not pin order: `Odors[i]` is odor line i+1 and the pins
    # are not monotonic past line 6. See `declared_of_kind`.
    emitters = channels.declared_of_kind("emitter")
    rewards = channels.declared_of_kind("reward")
    if emitters:
        lines.append(f"#define BOX_NUM_ODORS {len(emitters)}")
        lines.append(
            "#define BOX_ODOR_PINS {" + ", ".join(str(c.index) for c in emitters) + "}"
        )
    if rewards:
        lines.append(f"#define BOX_NUM_FLUIDS {len(rewards)}")
        lines.append(
            "#define BOX_FLUID_PINS {" + ", ".join(str(c.index) for c in rewards) + "}"
        )

    lines += ["", "#endif // TASK_PINS_H", ""]
    return "\n".join(lines)


def task_pins_h(definition: TaskDefinition) -> str:
    """The preprocessor half: pins, strobe codes, counts, selection mode.

    Included BEFORE `<BehaviorBox.h>`, whose `BoxPins.h`/`BoxStrobes.h` guard
    every definition — so what is written here wins and everything unmentioned
    falls back to the box as built. It may not name a type: at the point it is
    read, `TrialType` does not exist yet.
    """
    channels = registry.channels()
    vocab = registry.vocabulary()
    lines: list[str] = [_banner(definition), "", "#ifndef TASK_PINS_H", "#define TASK_PINS_H", ""]

    lines += [
        "/*  This rig's wiring. Every one of these overrides a guarded default in",
        "    BoxPins.h; a channel the rig does not declare is simply not mentioned",
        "    and keeps the shipped number. */",
    ]
    for name, macro in _PIN_MACROS:
        channel = channels.get(name)
        if channel is not None:
            lines.append(f"#define {macro} {channel.index}")
    lines += _sync_lines(channels)

    # DECLARATION order, not pin order. `Odors[i]` is odor line i+1, and the
    # pins are not monotonic past line 6 -- sorting by pin would put line 7
    # second and silently swap ten of the twelve lines.
    emitters = channels.declared_of_kind("emitter")
    rewards = channels.declared_of_kind("reward")
    if emitters:
        lines.append(f"#define BOX_NUM_ODORS {len(emitters)}")
        lines.append(
            "#define BOX_ODOR_PINS {" + ", ".join(str(c.index) for c in emitters) + "}"
        )
    if rewards:
        lines.append(f"#define BOX_NUM_FLUIDS {len(rewards)}")
        lines.append(
            "#define BOX_FLUID_PINS {" + ", ".join(str(c.index) for c in rewards) + "}"
        )

    lines += [
        "",
        "/*  The onset code each declared stimulus announces itself with, taken",
        "    from the app's append-only vocabulary and named by that vocabulary's",
        "    own name. BoxStrobes.h ships the same numbers, so these normally",
        "    agree exactly; emitting them anyway is what carries a code ADDED in",
        "    the app to firmware that predates it. Never derived from an odor",
        "    index -- the onsets run 101-109 and then 114-116, because 110-113",
        "    are retired codes a recorded session contains. */",
    ]
    for name in sorted({t.onset_strobe for t in definition.trials}):
        entry = vocab.get(name)
        if entry is not None:
            lines.append(f"#define BF_{name} {entry.code}")

    stage_keys = " ".join(f"P_STAGE({i})" for i in range(definition.stage_count))
    lines += [
        "",
        "/*  How many ramp rows exist, and which of them the START grammar can",
        "    reach. The two must agree: a key list longer than the count writes",
        "    past the end of stage[]. */",
        f"#define NUM_STAGES {definition.stage_count}",
        f"#define BOX_STAGE_KEY_LIST {stage_keys}",
        "",
        "/*  How many trial types the table declares, and the two per-type key",
        "    lists -- pool weights and reward volumes, one of each per slot.",
        "    Same pairing rule as the ramp: the count sizes both arrays. */",
        f"#define BOX_MAX_TRIAL_TYPES {max(1, definition.trial_count)}",
    ]
    pool_keys = [
        f'P_INT("PW{i + 1}", poolWeights[{i}])' for i in range(definition.trial_count)
    ]
    # Every slot, go and no-go alike, so the list pairs with the count exactly
    # as the pool list does. task.json declares a field only for go rows; a
    # slot the line never names keeps the 0 compiled into its TrialType.
    reward_keys = [
        f'P_INT("{fields.REWARD_WIRE_KEY}{i + 1}", rewardTimes[{i}])'
        for i in range(definition.trial_count)
    ]
    if pool_keys:
        lines.append("#define BOX_POOL_KEY_LIST " + " ".join(pool_keys))
        lines.append("#define BOX_REWARD_KEY_LIST " + " ".join(reward_keys))
    else:
        # An empty macro rather than none: both lists are referenced
        # unconditionally by TASK_PARAM_LIST, and leaving them to the guarded
        # defaults would declare four slots for a table with no rows.
        lines.append("#define BOX_POOL_KEY_LIST")
        lines.append("#define BOX_REWARD_KEY_LIST")

    mode = _SELECTION_MACRO[definition.selection_mode]
    lines += [
        "",
        "/*  Which selector the loop runs. Anti-bias draws a side against the",
        "    animal's recent expressed bias and then a type from that side",
        "    uniformly; weighted draws the side the same way and the type by",
        "    poolWeights; the pool draws a block-shuffled sequence from the",
        "    weights at START. BehaviorBox.h guards the same three values. */",
        "#define BOX_SELECT_ANTIBIAS 0",
        "#define BOX_SELECT_POOL 1",
        "#define BOX_SELECT_WEIGHTED 2",
        f"#define BOX_SELECTION_MODE {mode}",
        "",
        "#endif // TASK_PINS_H",
        "",
    ]
    return "\n".join(lines)


#: Definition mode -> the firmware macro. A dict rather than a ternary so an
#: unknown mode is a KeyError here, not a silent fall-through to anti-bias.
_SELECTION_MACRO: dict[str, str] = {
    "antibias": "BOX_SELECT_ANTIBIAS",
    "pool": "BOX_SELECT_POOL",
    "weighted": "BOX_SELECT_WEIGHTED",
}


#: Channel name -> the guarded macro in BoxPins.h. Resolution is by KIND for the
#: structural three, so a rig may rename them; the two response ports are named
#: because the trial runner has a left and a right and nothing else.
_PIN_MACROS: tuple[tuple[str, str], ...] = (
    ("odor_port", "BOX_PIN_ODOR_PORT"),
    ("right_well", "BOX_PIN_RIGHT_WELL"),
    ("left_well", "BOX_PIN_LEFT_WELL"),
    ("trial_light", "BOX_PIN_TRIAL_LIGHT"),
    ("vacuum", "BOX_PIN_VACUUM"),
)


def _sync_lines(channels: Any) -> list[str]:
    """`BOX_PIN_SYNC_OUT`, which is the one pin that is ALWAYS emitted.

    Every other pin that the rig does not declare is left unmentioned and keeps
    the number in BoxPins.h, so a partial document degrades one pin at a time.
    That rule is wrong for this line. The shipped default would pulse pin 49 on
    a rig whose operator never declared a sync channel -- and may have put
    something else there -- while the app, reading the same document, reports
    that the box has no sync line. So absence is stated: -1 compiles the pulse
    out, and the header and the app cannot disagree.

    Resolved by KIND, like the engagement port: it is a structural fact of the
    box and no task names it. Two sync channels (RIG105) resolve to none.
    """
    sync = channels.unique_of_kind("sync")
    return [
        "/*  One pulse per strobe, into a recording controller's digital input.",
        "    -1 = this rig declares no sync channel; the pulse is compiled out. */",
        f"#define BOX_PIN_SYNC_OUT {sync.index if sync is not None else -1}",
    ]


def _onset_macro(trial: TrialTypeDef) -> str:
    """The C name for this type's onset code.

    A straight `BF_` + the vocabulary's own name, with no arithmetic anywhere.
    An earlier version derived `BF_ODOR_<n>_ON` from the emitter's position and
    was wrong twice over: the position came from a pin-sorted list, and the
    codes are not contiguous anyway -- the onsets run 101-109 and then 114-116,
    with four retired numbers in the gap. What the operator picked is a NAME;
    this passes it through.
    """
    return f"BF_{trial.onset_strobe}"


def task_trials_h(definition: TaskDefinition) -> str:
    """The trial table, constructing `TrialType`. Included AFTER BehaviorBox.h."""
    channels = registry.channels()
    vocab = registry.vocabulary()

    lines: list[str] = [
        _banner(definition),
        "",
        "#ifndef TASK_TRIALS_H",
        "#define TASK_TRIALS_H",
        "",
        "/*  THE ORDER IS THE CONTRACT: slot i is poolWeights[i] (wire key PW<i+1>)",
        "    and rewardTimes[i] (wire key RW<i+1>). Reordering silently re-weights",
        "    a pool task and re-pays every condition, so the app emits this table",
        "    and both key lists from one pass over one list.",
        "",
        "    NOT const: each row's last argument is its reward volume, the",
        "    profile's default, and applyRewardTimes() overwrites it from the",
        "    START line before the first trial. */",
        "static TrialType kTrials[] = {",
    ]

    # Declaration order, matching BOX_ODOR_PINS above: slot i of that table is
    # `Odors[i]`, so the two must be built from the same list.
    emitters = channels.declared_of_kind("emitter")
    for trial in definition.trials:
        odor_index = next(
            (i for i, c in enumerate(emitters) if c.name == trial.odor_channel), None
        )
        onset = _onset_macro(trial)
        if odor_index is None or trial.onset_strobe not in vocab:
            continue

        if trial.is_go:
            port = channels.get(trial.response_channel) if trial.response_channel else None
            reward_index = _reward_index(channels, trial.reward_channel)
            slot = vocab.port_slot(port.port_slot) if port and port.port_slot else None
            if port is None or reward_index is None or not slot:
                continue
            well = "rightWell" if port.name == "right_well" else "leftWell"
            fluid_code = f"BF_{slot['reward_code']}"
            stop_code = f"BF_{slot['reward_stop_code']}"
            label = trial.label or f"{trial.odor_channel} -> {port.name}"
            lines += [
                f"    /* {label} */",
                "    TrialType(true, "
                f"Odors[{odor_index}], {well}, {reward_index}, "
                f"{onset}, {fluid_code}, {stop_code}, {trial.reward_time}),",
            ]
        else:
            label = trial.label or f"{trial.odor_channel} -> withhold"
            lines += [
                f"    /* {label} (no-go: no correct port, no reward) */",
                "    TrialType(false, "
                f"Odors[{odor_index}], {SENTINEL}, {SENTINEL}, {onset}, 0, 0, 0),",
            ]

    lines += [
        "};",
        "",
        "static const int kTrialCount = (int)(sizeof(kTrials) / sizeof(kTrials[0]));",
        "",
        "/*  The table cannot outgrow the arrays that index it -- poolWeights[] and",
        "    the selector's side lists are both BOX_MAX_TRIAL_TYPES long. Emitted",
        "    together, so this only fires on a hand edit; it fires at build time,",
        "    which is the point. */",
        "static_assert(kTrialCount <= BOX_MAX_TRIAL_TYPES,",
        '              "more trial types than BOX_MAX_TRIAL_TYPES");',
        "",
        "#endif // TASK_TRIALS_H",
        "",
    ]
    return "\n".join(lines)


def _reward_index(channels, name: str | None) -> int | None:
    """Position in the DECLARED reward list — the index into `Fluids[]`.

    The same order `BOX_FLUID_PINS` is emitted in, so index and pin describe one
    line by construction rather than by agreement. Declaration order rather than
    pin order for the reason `declared_of_kind` gives: these happen to ascend
    today, and relying on that is how the odor table went wrong.
    """
    if name is None:
        return None
    for i, channel in enumerate(channels.declared_of_kind("reward")):
        if channel.name == name:
            return i
    return None


def _banner(definition: TaskDefinition) -> str:
    channels = registry.channels()
    return _GENERATED_BANNER.format(
        name=definition.name,
        pinout=channels.pinout_id,
        pinout_hash=channels.content_hash(),
    )


def generated_files(definition: TaskDefinition, sketch_source: str) -> dict[str, str]:
    """Everything the sketch folder holds, keyed by filename.

    `sketch_source` is the root `GRGL.ino` read from the bundled library — copied
    rather than templated, so there is one trial runner and one session loop in
    the world and a profile cannot fork them.
    """
    name = definition.name
    return {
        f"{name}.ino": sketch_source,
        "TaskPins.h": task_pins_h(definition),
        "TaskTrials.h": task_trials_h(definition),
        "task.json": json.dumps(profile_json(definition), indent=2) + "\n",
    }
