"""The box utility, generated from the rig — `TASKS.md#the-box-utility`.

`BOX_Utility` used to be a hand-written sketch that knew this lab's box by
heart: twelve odor lines called O1..O12, four fluid lines F1..F4, three beams
called odor port / left well / right well, and a `task.json` whose Debug Mode
grids listed exactly those. A rig with a relabelled line drove the right pin
under the wrong name; a rig with a different count did not fit at all.

Now the logic lives once in the firmware library (`BoxUtility.h`, host-tested)
and everything it knows about THIS box is generated here from the composed
channel map, in two halves that must agree and so are written together:

* `UtilityChannels.h` — one row per output and per beam: the channel name (the
  command token and STATUS key), the Rig page's label, the pin, the kind.
* `task.json` — the sketch folder's own rig-independent profile (buttons, the
  pulse-width select, legacy names) with the rig half merged in: one Debug Mode
  grid row per output, a telemetry field per beam, and the identify pair.

A sketch opts in by including `UtilityChannels.h`, exactly as one opts into
rig pins by including `TaskPins.h` (`taskdef/bundled.py`), and is rebuilt on
the same triggers: every start, every wiring change, every vocabulary edit.
"""

from __future__ import annotations

import copy
from pathlib import Path
from typing import Any

from ..rig import registry

#: The header a sketch includes to declare it is a box utility.
UTILITY_HEADER = "UtilityChannels.h"

#: Output kinds the utility drives, in the order its grids and self-test take
#: them, with the `BoxUtilKind` each becomes. `sync` is deliberately absent: a
#: pulse on it is an edge in a recording, and the trial runner owns that line.
OUTPUT_KINDS: tuple[tuple[str, str], ...] = (
    ("emitter", "BOX_UTIL_EMITTER"),
    ("reward", "BOX_UTIL_REWARD"),
    ("cue", "BOX_UTIL_CUE"),
    ("vacuum", "BOX_UTIL_VACUUM"),
)

#: Input kinds the self-test checks, engagement port first.
INPUT_KINDS: tuple[str, ...] = ("engagement", "response")

#: Debug Mode grids: id, label, the kinds they hold. `fluids` keeps its id
#: because Prime finds the reward grid by it (`UtilityControls.tsx`).
GRIDS: tuple[tuple[str, str, tuple[str, ...]], ...] = (
    ("fluids", "Reward lines", ("reward",)),
    ("aux", "Cues & vacuum", ("cue", "vacuum")),
    ("emitters", "Stimulus lines", ("emitter",)),
)


def wants_utility(sketch_dir: Path) -> bool:
    """Whether this sketch is a box utility to be generated for the rig.

    Read from the `.ino` itself, for the reason `bundled.wants_pinning` gives:
    a manifest would be a second declaration of the same thing.
    """
    ino = Path(sketch_dir) / f"{Path(sketch_dir).name}.ino"
    try:
        return f'#include "{UTILITY_HEADER}"' in ino.read_text(encoding="utf-8")
    except OSError:
        return False


def outputs(channels: registry.ChannelMap) -> list[registry.Channel]:
    """Every output the utility drives, grouped by kind, in DECLARATION order
    within a kind — the order the Rig page lists them."""
    return [c for kind, _ in OUTPUT_KINDS for c in channels.declared_of_kind(kind)]


def inputs(channels: registry.ChannelMap) -> list[registry.Channel]:
    return [c for kind in INPUT_KINDS for c in channels.declared_of_kind(kind)]


def row_label(channel: registry.Channel) -> str:
    """The Rig page's label, with the well a reward line serves when known —
    "which well does fluid 2 feed?" is the question priming is for."""
    if channel.kind == "reward" and channel.well:
        return f"{channel.label} · {channel.well.replace('_', ' ')}"
    return channel.label


def utility_channels_h(sketch_name: str) -> str:
    """The channel table for `BoxUtility.h`, from the rig in force."""
    channels = registry.channels()
    outs = outputs(channels)
    ins = inputs(channels)
    kind_macro = dict(OUTPUT_KINDS)

    out_rows = [
        f'  {{{_c(c.name)}, {_c(row_label(c))}, {c.index}, {kind_macro[c.kind]}}}'
        for c in outs
    ]
    in_rows = [f"  {{{_c(c.name)}, {_c(c.label)}, {c.index}}}" for c in ins]
    if not in_rows:
        # A zero-length array is not C++; the engine reads NUM_INPUTS, not this.
        in_rows = ['  {"", "", -1}']
    # Every key, its "=0" and a space, plus the fixed tail, with room to spare:
    # a STATUS line truncated mid-key would light the wrong row.
    status_bytes = 96 + sum(len(c.name) + 4 for c in outs + ins)

    lines = [
        "/*  GENERATED by Ephymeris -- do not edit.",
        "",
        "    The box utility's channel table, from THIS RIG'S wiring and labels",
        "    (docs/TASKS.md#the-box-utility). Rewritten whenever the wiring changes;",
        "    an edit here is lost at the next change without a word.",
        "",
        f"    Sketch:  {sketch_name}",
        f"    Wiring:  {channels.pinout_id} ({channels.content_hash()})",
        "*/",
        "",
        "#ifndef UTILITY_CHANNELS_H",
        "#define UTILITY_CHANNELS_H",
        "",
        f"#define BOX_UTILITY_NUM_OUTPUTS {len(outs)}",
        "#define BOX_UTILITY_OUTPUTS { \\",
        *(row + (", \\" if i < len(out_rows) - 1 else " \\") for i, row in enumerate(out_rows)),
        "}",
        f"#define BOX_UTILITY_NUM_INPUTS {len(ins)}",
        "#define BOX_UTILITY_INPUTS { \\",
        *(row + (", \\" if i < len(in_rows) - 1 else " \\") for i, row in enumerate(in_rows)),
        "}",
        f"#define BOX_UTILITY_STATUS_BYTES {status_bytes}",
        "",
        "#endif // UTILITY_CHANNELS_H",
        "",
    ]
    return "\n".join(lines)


def utility_profile(template: dict[str, Any]) -> dict[str, Any]:
    """The sketch folder's own `task.json`, with the rig half merged in.

    The template keeps what does not depend on the box (buttons, the pulse
    select, legacy names, the common telemetry fields); this adds a grid per
    group of outputs, a telemetry field per beam, and an identify pair on the
    first cue. Grids the template already declares under the same id are
    replaced, so regenerating is idempotent.
    """
    channels = registry.channels()
    profile = copy.deepcopy(template)
    grid_ids = {grid_id for grid_id, _, _ in GRIDS}
    controls = [c for c in profile.get("controls", []) if c.get("id") not in grid_ids]

    outs = outputs(channels)
    for grid_id, label, kinds in GRIDS:
        rows = [
            {
                "label": row_label(c),
                "state": c.name,
                "toggle": f"TOGGLE {c.name}",
                "pulse": f"PULSE {c.name}",
                "kind": c.kind,
            }
            for c in outs
            if c.kind in kinds
        ]
        if rows:
            controls.append({"id": grid_id, "type": "grid", "label": label, "channels": rows})
    profile["controls"] = controls

    telemetry = profile.setdefault("telemetry", {"match": "STATUS", "fields": []})
    beam_keys = {c.name for c in inputs(channels)}
    fields = [f for f in telemetry.get("fields", []) if f.get("key") not in beam_keys]
    fields += [{"key": c.name, "label": f"{c.label} beam"} for c in inputs(channels)]
    telemetry["fields"] = fields

    cue = next((c for c in outs if c.kind == "cue"), None)
    if cue is not None:
        profile["identify"] = {"on": f"ON {cue.name}", "off": f"OFF {cue.name}"}
    else:
        profile.pop("identify", None)
    return profile


def _c(text: str) -> str:
    """A C string literal for `text`: UTF-8 bytes, quotes and backslashes
    escaped, anything unprintable as a three-digit octal escape (always three
    digits, so a following digit can never be read into it)."""
    out = []
    for byte in text.encode("utf-8"):
        ch = chr(byte)
        if ch in '"\\':
            out.append("\\" + ch)
        elif 32 <= byte < 127:
            out.append(ch)
        else:
            out.append(f"\\{byte:03o}")
    return '"' + "".join(out) + '"'
