/**
 * Canonical wire protocol between this frontend and the Python sidecar.
 *
 * GENERATED by protocol/generate.py from protocol/schema.py — DO NOT EDIT.
 * Regenerate with `npm run gen:protocol` (or `python protocol/generate.py`).
 *
 * `docs/websocket-protocol.md` carries the prose (rationale, lifecycle,
 * invariants); `protocol/schema.py` is the shape authority this file and
 * `sidecar/ephymeris_sidecar/protocol.py` are generated from.
 */

export const PROTOCOL_VERSION = 1;

// --- Commands (client -> server) -------------------------------------------

export const CMD = {
  // Connection & hardware
  AUTH: "auth",
  SETTINGS_PUSH: "settings.push",
  SKETCHES_REFRESH: "sketches.refresh",
  PORT_PASSTHROUGH_OPEN: "port.passthrough.open",
  PORT_PASSTHROUGH_CLOSE: "port.passthrough.close",
  PORT_SEND: "port.send",
  PORT_SEND_START: "port.sendStart",
  PORT_FLASH: "port.flash",
  PORT_RESET: "port.reset",
  PORT_ERROR_ACK: "port.error.ack",
  UTILITY_ENSURE: "utility.ensure",
  UTILITY_IDENTIFY: "utility.identify",

  // Cohorts (cohorts.md)
  COHORTS_LIST: "cohorts.list",
  COHORTS_GET: "cohorts.get",
  COHORTS_CREATE: "cohorts.create",
  COHORTS_UPDATE: "cohorts.update",
  COHORTS_ARCHIVE: "cohorts.archive",
  COHORTS_RESTORE: "cohorts.restore",
  COHORTS_DELETE: "cohorts.delete",
  COHORTS_SET_DATA_FOLDER: "cohorts.setDataFolder",
  COHORTS_SUGGEST_GROUPS: "cohorts.suggestGroups",

  // Prefixes, Task Profiles & sessions
  PREFIXES_LIST: "prefixes.list",
  PREFIXES_CREATE: "prefixes.create",
  PREFIXES_DELETE: "prefixes.delete",
  TASKS_GET_PROFILE: "tasks.getProfile",

  // Task profiles (tasks.md §11)
  TASKS_LIST: "tasks.list",
  TASKS_GET: "tasks.get",
  TASKS_PREVIEW: "tasks.preview",
  TASKS_SAVE: "tasks.save",
  TASKS_DELETE: "tasks.delete",

  // Strobe vocabulary (tasks.md §3.3)
  RIG_STROBES: "rig.strobes",
  SESSIONS_SUGGEST_NUMBER: "sessions.suggestNumber",
  SESSIONS_CREATE: "sessions.create",
  SESSIONS_ABANDON: "sessions.abandon",
  SESSIONS_CONFIRM_MAPPING: "sessions.confirmMapping",
  SESSIONS_STATUS: "sessions.status",
  SESSIONS_START_ALL: "sessions.startAll",
  SESSIONS_END_GROUP: "sessions.endGroup",
  SESSIONS_RESUME: "sessions.resume",
  SESSIONS_END: "sessions.end",
  SESSIONS_ACTIVE: "sessions.active",
  PORT_START_SESSION: "port.startSession",
  PORT_STOP_SESSION: "port.stopSession",

  // Backup (data.md §7)
  BACKUP_SYNC_NOW: "backup.syncNow",

  // Analytics (websocket-protocol.md §3.4)
  SESSIONS_LIST: "sessions.list",
  ANALYTICS_SUMMARY: "analytics.summary",
  ANALYTICS_SERIES: "analytics.series",
  ANALYTICS_RESCAN: "analytics.rescan",
  ANALYTICS_RECENT_SESSIONS: "analytics.recentSessions",

  // Crash recovery (data.md §12, §11)
  SESSIONS_RECOVER: "sessions.recover",
  SESSIONS_TIDY: "sessions.tidy",
  HARDWARE_GET: "hardware.get",
  HARDWARE_PREVIEW: "hardware.preview",
  HARDWARE_SAVE: "hardware.save",
  HARDWARE_RESET: "hardware.reset",

  // Intan recording (recording.md)
  INTAN_STATUS: "intan.status",
  INTAN_CONNECT: "intan.connect",
  INTAN_DISCONNECT: "intan.disconnect",
  INTAN_CONFIGURE: "intan.configure",
  INTAN_PARSE_PROBE_MAP: "intan.parseProbeMap",
  INTAN_PROBE_MAP: "intan.probeMap",
  INTAN_SET_THRESHOLD: "intan.setThreshold",
  INTAN_SCOPE_OPEN: "intan.scope.open",
  INTAN_SCOPE_UPDATE: "intan.scope.update",
  INTAN_SCOPE_CLOSE: "intan.scope.close",
  INTAN_FORCE_STOP: "intan.forceStop",
} as const;

export type CommandName = (typeof CMD)[keyof typeof CMD];

// --- Events (server -> client) ---------------------------------------------

export const EVT = {
  SERVER_HELLO: "server.hello",
  PORT_STATE: "port.state",
  PORT_OUTPUT: "port.output",
  PORT_TELEMETRY: "port.telemetry",
  BOARDS_PRESENCE: "boards.presence",
  FLASH_PROGRESS: "flash.progress",
  SKETCHES_UPDATED: "sketches.updated",
  COHORTS_UPDATED: "cohorts.updated",
  PREFIXES_UPDATED: "prefixes.updated",
  SESSION_TELEMETRY: "session.telemetry",
  SESSION_ANIMAL_ENDED: "session.animalEnded",
  SESSION_LIFECYCLE: "session.lifecycle",
  HARDWARE_UPDATED: "hardware.updated",
  UTILITY_UPDATED: "utility.updated",
  BACKUP_STATUS: "backup.status",
  ANALYTICS_PROGRESS: "analytics.progress",
  SIDECAR_ERROR: "sidecar.error",
  TASKS_UPDATED: "tasks.updated",
  INTAN_STATUS: "intan.status",
  INTAN_SCOPE_DATA: "intan.scope.data",
} as const;

export type EventName = (typeof EVT)[keyof typeof EVT];

// --- Error codes -----------------------------------------------------------

export const ERR = {
  BAD_MESSAGE: "BAD_MESSAGE",
  UNKNOWN_COMMAND: "UNKNOWN_COMMAND",
  UNAUTHORIZED: "UNAUTHORIZED",
  PROTOCOL_VERSION_MISMATCH: "PROTOCOL_VERSION_MISMATCH",
  ILLEGAL_TRANSITION: "ILLEGAL_TRANSITION",
  SEND_NOT_PASSTHROUGH: "SEND_NOT_PASSTHROUGH",
  PORT_NOT_BOUND: "PORT_NOT_BOUND",
  PORT_OPEN_FAILED: "PORT_OPEN_FAILED",
  FLASH_FAILED: "FLASH_FAILED",
  SKETCH_UNKNOWN: "SKETCH_UNKNOWN",
  COHORT_NOT_FOUND: "COHORT_NOT_FOUND",
  COHORT_NAME_TAKEN: "COHORT_NAME_TAKEN",
  COHORT_INVALID: "COHORT_INVALID",
  COHORT_NOT_ARCHIVED: "COHORT_NOT_ARCHIVED",
  DATA_FOLDER_INVALID: "DATA_FOLDER_INVALID",
  PREFIX_NAME_TAKEN: "PREFIX_NAME_TAKEN",
  SESSION_INVALID: "SESSION_INVALID",
  SESSION_NOT_READY: "SESSION_NOT_READY",
  TASK_PROFILE_INVALID: "TASK_PROFILE_INVALID",
  BACKUP_UNAVAILABLE: "BACKUP_UNAVAILABLE",
  UTILITY_UNAVAILABLE: "UTILITY_UNAVAILABLE",
  RIG_INVALID: "RIG_INVALID",
  RIG_WOULD_BREAK_TASKS: "RIG_WOULD_BREAK_TASKS",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  TASK_INVALID: "TASK_INVALID",
  INTAN_UNAVAILABLE: "INTAN_UNAVAILABLE",
  INTAN_NOT_READY: "INTAN_NOT_READY",
  INTAN_COMMAND_FAILED: "INTAN_COMMAND_FAILED",
  INTERNAL: "INTERNAL",
} as const;

export type ErrorCode = (typeof ERR)[keyof typeof ERR];

// --- Payload shapes --------------------------------------------------------

/**
 * Per-port state machine names (`dashboard.md` §5.1). One owner at a time: FLASHING, RESETTING
 * and IN_SESSION are each exclusive, and the first two force-release PASSTHROUGH and auto-resume
 * it afterward.
 */
export type PortStateName = "IDLE" | "PASSTHROUGH" | "FLASHING" | "RESETTING" | "IN_SESSION" | "ERROR";

/** One passthrough console line. Debug output, never persisted (§5.4). */
export interface OutputLine {
  /** Sent commands interleave as `tx` (§5.3). */
  dir: "rx" | "tx";
  text: string;
  ts: number;
}

/** A board the out-of-band `arduino-cli board list` poll has seen. */
export interface DetectedBoard {
  hardwareId: string;
  address: string;
  fqbn: string | null;
  /** `null` for a board no box is bound to. */
  boxId: number | null;
}

/**
 * The three bundled-sketch-library states of `tasks.md` §2.4. There is no `not_configured`:
 * sketches ship with the app, so there is nothing to configure and no first-run state to be in.
 */
export type LibraryState = "ok" | "empty" | "damaged";

/**
 * Every non-ok state means a broken or partial INSTALL rather than a wrong setting, which is why
 * the messages point at reinstalling and not at a picker.
 */
export interface SketchLibraryStatus {
  state: LibraryState;
  path: string | null;
  /** Populated when state != "ok". */
  message: string | null;
  /**
   * `override` when $EPHYMERIS_SKETCH_LIBRARY points elsewhere — a developer facility, never
   * reachable from the UI.
   */
  source: "bundled" | "override";
}

export interface SketchEntry {
  category: string;
  name: string;
  path: string;
}

/** Carried in full so a missing sketch is inspectable, not silent. */
export interface SkippedEntry {
  path: string;
  reason: string;
}

/** The full result of a bundled-library scan (`tasks.md` §2.3). */
export interface SketchDiscovery {
  library: SketchLibraryStatus;
  sketches: SketchEntry[];
  skipped: SkippedEntry[];
  /** Drives the "Partial" note (`tasks.md` §2.4). */
  skippedCount: number;
  libraries: string[];
  librariesPath: string | null;
}

export interface BoxBinding {
  box: number;
  /** USB serial number — stable across COM renumbering. */
  hardwareId: string | null;
  label: string;
  /**
   * Which of the recording controller's digital inputs this box's sync line is wired to, 1–16
   * (`recording.md` §3). Null = the box is not wired for recording. A binding like `hardwareId`,
   * and for the same reason a setting rather than part of the rig document: it describes a cable
   * between two instruments, not the box.
   */
  intanDigitalIn?: number | null;
}

/**
 * Where Intan RHX's three TCP servers listen. The host is not a setting: Ephymeris only ever
 * talks to an RHX on this machine.
 */
export interface IntanSettings {
  commandPort: number;
  waveformPort: number;
  spikePort: number;
}

/**
 * The Tauri-side store's schema. The sidecar reads the keys it needs and ignores the rest, so
 * adding a setting is deliberately a non-event.
 */
export interface EphymerisSettings {
  dataDirectory: string | null;
  backupDirectory: string | null;
  arduinoCliPath: string | null;
  /**
   * The hardware utility sketch every idle box is returned to (`settings.md` §8). Null turns the
   * baseline off. Keyed by sketch FOLDER NAME rather than by path, matching `taskDefaults` — the
   * path moved when sketches began shipping with the app, and the name is what a session file
   * already records.
   */
  utilitySketchName: string | null;
  defaultBaud: number;
  boxes: BoxBinding[];
  /**
   * Absent on a store written before recording existed; both ends fall back to RHX's defaults
   * (5000/5001/5002).
   */
  intan?: IntanSettings;
  /**
   * The last recording setup the operator confirmed, offered as the next one's starting point.
   * Shell-only.
   */
  recordingDefaults?: Record<string, unknown>;
  reducedMotion: boolean;
  /**
   * Zodiac layout id for the box-status constellation; null = the legacy fixed layout. Shell-only
   * — the sidecar ignores it.
   */
  constellation: string | null;
  /** Box number (string key, JSON) → star index in the chosen constellation. Shell-only. */
  constellationSlots: Record<string, number>;
  /**
   * Sketch folder name → this rig's default task parameters for it, keyed by `metadataKey`
   * (`tasks.md` §6.1). Keyed by NAME, not path: the two lab machines keep their Arduino
   * Directories in different places, and the name is what the session file already records.
   * Shell-only — the frontend merges these under the profile's own defaults and sends the result
   * at `sessions.confirmMapping`, so the sidecar never reads them.
   */
  taskDefaults: Record<string, Record<string, unknown>>;
}

/**
 * What the sidecar believes about one box's baseline firmware. `busy` (the port has another
 * owner), `held` (a confirmed session mapping owns the rig) and `pinned` (the operator flashed
 * another sketch here from Debug Mode, and it stays until they ask for the baseline back) are all
 * 'not now' rather than 'not working' — the distinction is the whole reason a restore never
 * fights the user.
 */
export type UtilityBaselineState = "unknown" | "restoring" | "ready" | "busy" | "held" | "pinned" | "unavailable" | "failed";

export interface UtilityBoxState {
  box: number;
  state: UtilityBaselineState;
  /** Why, when the state isn't `ready`. */
  detail: string | null;
  /** This box is currently lit by utility.identify. */
  identifying: boolean;
}

/**
 * The whole baseline picture — one snapshot, shared by the command and the event, so a client
 * never merges two shapes.
 */
export interface UtilityStatus {
  configured: boolean;
  /**
   * Resolved from the name against the bundled library — an install-specific fact, informational
   * only.
   */
  sketchPath: string | null;
  sketchName: string | null;
  /**
   * The configured sketch's profile declares an `identify` pair. False means placement can still
   * run, just without lights.
   */
  canIdentify: boolean;
  /**
   * Restores are suspended because a confirmed session mapping owns the boxes — reflashing then
   * would erase the task sketch.
   */
  held: boolean;
  /**
   * Why the baseline isn't operating at all (unset sketch, a path no longer in the Arduino
   * Directory, a non-utility profile).
   */
  message: string | null;
  boxes: UtilityBoxState[];
}

/**
 * `pending` = directory set but no pass has completed yet — a fresh unreachable network path must
 * not read as healthy for its first 10 s.
 */
export type BackupState = "disabled" | "pending" | "ok" | "failed";

export interface BackupStatus {
  configured: boolean;
  directory: string | null;
  state: BackupState;
  /** Finalized files queued for their one-shot copy. */
  pending: number;
  /** Live .tsv files mirrored each pass. */
  tracking: number;
  /** Copies made this sidecar lifetime. */
  mirroredFiles: number;
  lastSuccessAt: string | null;
  lastError: string | null;
  /** A backup.syncNow walk is running. */
  syncing: boolean;
  intervalSeconds: number;
}

export interface SyncResult {
  copied: number;
  /** Already current — not an error. */
  skipped: number;
  failed: number;
  errors: string[];
  directory: string;
}

export type Sex = "M" | "F" | "unknown";

export interface Group {
  id: string;
  name: string;
  /** Run order for consecutive execution. */
  order: number;
}

export interface Animal {
  id: string;
  name: string;
  /** Exactly one group. */
  groupId: string;
  /** Abstract slot 1–6, never a live port. */
  boxNumber: number | null;
  /**
   * Home-cage number — cagemates share one. A grouping label validated as ≥ 1 and nothing else;
   * null means unassigned.
   */
  cage: number | null;
  sex: Sex | null;
  idNumber: string | null;
  notes: string | null;
}

/**
 * How a cohort's world looks (cohorts.md §5). **Null is the normal state**: an untouched cohort
 * derives every field from a hash of its `id`, so it already has a stable, distinct planet and
 * the column that stores this carries no data for it.
 */
export interface CohortAppearance {
  /**
   * `rocky` | `gas` | `ice` | `ocean` | `lava`. Selects which surface the planet shader draws;
   * unknown values fall back to `rocky` rather than rendering nothing.
   */
  type: string;
  /** 0–360. Rotates the palette, nothing else. */
  hue: number;
  ring: boolean;
  /**
   * Shifts the noise field and only that — a re-roll changes the world's weather, never its type,
   * hue or size.
   */
  seed: number;
}

/** The full record, fetched only when a cohort is opened. */
export interface Cohort {
  id: string;
  name: string;
  /** Resolved once at creation, persisted verbatim (§8). */
  dataFolder: string;
  animals: Animal[];
  /** Always ≥ 1 — a default group always exists. */
  groups: Group[];
  archivedAt: string | null;
  createdAt: string;
  updatedAt: string;
  /**
   * Null until the operator tunes it, and null is not a gap: the whole record is derived from
   * `id` when absent.
   */
  appearance: CohortAppearance | null;
}

/** Enough for the cohort browser and the dashboard tile, no per-animal detail. */
export interface CohortSummary {
  id: string;
  name: string;
  animalCount: number;
  groupCount: number;
  /**
   * Distinct box numbers this cohort's animals hold. Animal detail the summary carries so the
   * browser can flag a cohort whose boxes no longer exist on this machine without fetching every
   * cohort in full.
   */
  assignedBoxes: number[];
  /**
   * Distinct home cages, and the second piece of animal detail the summary carries, on the same
   * argument: the cohort browser draws one orbiting ship per cage, and deriving that from the
   * roster would cost a full `cohorts.get` per planet on every route mount. A count, not the
   * numbers — which animals share a cage is the editor's business.
   */
  cageCount: number;
  archived: boolean;
  createdAt: string;
  updatedAt: string;
  appearance: CohortAppearance | null;
}

export interface CohortPatch {
  name?: string;
  /** Replaced wholesale. */
  animals?: Animal[];
  /** Replaced wholesale. */
  groups?: Group[];
  /** Replaced wholesale. Explicit null resets the world to the one derived from the cohort's id. */
  appearance?: CohortAppearance | null;
}

export interface ProposedAnimal {
  animalId: string;
  boxNumber: number;
}

export interface ProposedGroup {
  name: string;
  order: number;
  animals: ProposedAnimal[];
}

export interface GroupRejection {
  reason: string;
  /** The minimum viable count, so the user can accept it. */
  minimumGroups: number;
}

/** An Auto-Balance preview. Nothing is written; apply via cohorts.update. */
export interface GroupProposal {
  groups: ProposedGroup[];
  /**
   * Set when the request would break the six-per-group constraint (§7.2) — guidance rather than a
   * failure, so not an error reply.
   */
  rejected: GroupRejection | null;
}

/** Global — shared across cohorts. */
export interface Prefix {
  id: string;
  name: string;
}

export type SessionStatus = "configuring" | "running" | "completed" | "aborted";

export interface GroupRun {
  groupId: string;
  order: number;
  startedAt: string;
  endedAt: string | null;
}

export interface Session {
  id: string;
  cohortId: string;
  prefixId: string;
  prefixName: string;
  /** Free text, not strictly numeric (§10). */
  sessionNumber: string;
  /** ISO `YYYY-MM-DD`. */
  date: string;
  startedAt: string;
  endedAt: string | null;
  status: SessionStatus;
  folderPath: string;
  groupRuns: GroupRun[];
  /**
   * Per-box time limit: the sidecar sends STOP to a box this many minutes after that box's own
   * start. Null means no limit.
   */
  durationMinutes: number | null;
  /**
   * Set when the session is also an Intan recording (`recording.md` §6). Null = behavior only,
   * which is every session from before recording existed.
   */
  recording: SessionRecording | null;
}

export type ConfigFieldType = "int" | "float" | "bool" | "string";

/**
 * One operator-tunable parameter. Everything past `default` is presentation metadata and optional
 * — a profile that declares none renders exactly as it did before these keys existed.
 */
export interface ConfigField {
  /** The `.json`/`.mat` field name the form collects under. */
  metadataKey: string;
  /** The `START` command token (§6.3). */
  wireKey: string;
  label: string;
  type: ConfigFieldType;
  default: unknown;
  /**
   * Section heading the form files this field under. Absent = ungrouped, which is how every
   * pre-existing profile renders.
   */
  group?: string;
  /** Suffix shown after the input, e.g. "ms". */
  unit?: string;
  /** Inclusive bound the form clamps to. */
  min?: number;
  /** Inclusive bound the form clamps to. */
  max?: number;
  /** Stepper increment; presentation only. */
  step?: number;
  /** One-line explanation shown with the field. */
  help?: string;
  /** Collapsed behind a disclosure by default. For fields a session should rarely need to touch. */
  advanced?: boolean;
}

export interface LiveMetric {
  id: string;
  label: string;
  triggerCode: number;
  successCode: number;
  alternateCode: number;
  windowSize: number;
}

/** A scored IN_SESSION task, or a PASSTHROUGH tool (§6.2). */
export type ProfileKind = "behavior" | "utility";

export interface ControlOption {
  label: string;
  command: string;
}

/**
 * One row of a `grid` control — a named piece of hardware with its own commands and its own live
 * state key.
 */
export interface ControlChannel {
  label: string;
  /** Telemetry key whose 0/1 value lights this row's indicator. */
  state?: string;
  /** Command that latches this channel. */
  toggle?: string;
  /** Command that pulses this channel. */
  pulse?: string;
}

/** A utility control rendered in Debug Mode (§6.6); sends over port.send. */
export interface Control {
  id: string;
  label: string;
  type: "button" | "select" | "grid";
  /** `button` controls only. */
  command?: string;
  /** `select` controls only. */
  options?: ControlOption[];
  /**
   * `grid` controls only — one row per channel. Exists because a box has 18 controllable outputs,
   * and 36 flat buttons is not a control surface.
   */
  channels?: ControlChannel[];
}

export interface TelemetryField {
  key: string;
  label: string;
}

/**
 * How to parse a utility sketch's non-persisted STATUS lines out of port.output (§6.6). Parsed
 * client-side — nothing here is stored.
 */
export interface TelemetrySpec {
  match: string;
  fields: TelemetryField[];
}

/**
 * The two commands that make a box announce itself — a trial light, a buzzer, whatever the rig
 * has (`settings.md` §8.3). Declared by the sketch so the app never has to know that a Hart-lab
 * box says `ON LIGHT`.
 */
export interface IdentifySpec {
  on: string;
  off: string;
}

/**
 * Parsed from the sketch's task.json sibling (§6.1); passed through verbatim — the sidecar
 * validates shape but doesn't reinterpret.
 */
export interface TaskProfile {
  taskName: string;
  kind: ProfileKind;
  config: ConfigField[];
  /**
   * code → name, string-keyed to match the authored task.json. Display/debug only — metrics use
   * raw codes.
   */
  strobes: Record<string, string>;
  liveMetrics: LiveMetric[];
  /** Utility profiles only. */
  controls: Control[];
  /**
   * Names older software wrote for this same task, so the archive walk can decode historical runs
   * (`tasks.md` §3.7). Declared, never inferred.
   */
  legacyNames: string[];
  /** Utility profiles only. */
  telemetry?: TelemetrySpec;
  /**
   * Utility profiles only — absent means this sketch can't be asked to point at its own box,
   * which the placement walk degrades around rather than refusing.
   */
  identify?: IdentifySpec;
}

/** One box's session-local mapping + task config (`dashboard.md` §7.3). */
export interface SessionBoxMapping {
  box: number;
  animalId: string;
  sketchPath: string;
  /** Keyed by `metadataKey`, per the Task Profile. */
  config: Record<string, unknown>;
}

/** One box as the runner sees it — the source Mission Control renders (§5). */
export interface SessionBox {
  box: number;
  animalId: string;
  animalName: string;
  sketchName: string;
  sketchPath: string;
  running: boolean;
  /**
   * When this box's current run began; null unless running. What lets a reloaded Mission Control
   * resume its elapsed clocks.
   */
  startedAt: string | null;
}

export interface TelemetryMetric {
  id: string;
  /** P(hit) over the rolling window; null until a trial counts. */
  value: number | null;
  /** Counted (hit-or-miss) trials in the window — a window length, not a trial count. */
  n: number;
}

export interface BoxTelemetry {
  box: number;
  animalId: string;
  metrics: TelemetryMetric[];
}

/**
 * Debug Mode's counterpart to `BoxTelemetry`. No `animalId`: a task started by hand from the
 * console is nobody's run and records nothing.
 */
export interface PortTelemetry {
  box: number;
  /**
   * A task started with `port.sendStart` is still running. Goes false when the board emits its
   * `END_SESSION` strobe or the port leaves PASSTHROUGH — observed by the sidecar, never assumed.
   */
  running: boolean;
  metrics: TelemetryMetric[];
}

export interface AnimalEnded {
  box: number;
  animalId: string;
  /** `dashboard.md` §10.4's stop-reason set. */
  stopReason: string;
  filePath: string | null;
}

/** The runner-held session — the same shape a sessions.status reply carries. */
export interface RunnerSession {
  session: Session;
  /** Null only before any mapping was confirmed. */
  groupId: string | null;
  boxes: SessionBox[];
}

/**
 * Everything unfinished, discoverable with no prior knowledge of ids. Also the session.lifecycle
 * payload — one shape, one emitter.
 */
export interface ActiveSessions {
  /**
   * Keyed off the live runner, never a bare DB status query — a 'running' row with no live runner
   * is a crash orphan. A held session with `groupId: null` and no boxes is BETWEEN GROUPS,
   * awaiting a choice.
   */
  running: RunnerSession | null;
  /** Setup never finished; legitimately resumable into the mapping flow. */
  configuring: Session[];
  /**
   * DB says 'running' but no runner holds them — a crash or a closed app. The .tsv on disk is the
   * record; a same-day one can be continued with another group (`sessions.resume`), never
   * mid-group.
   */
  stale: Session[];
}

/** One session, from sessions.list or inside a summary. */
export interface SessionListItem {
  id: string;
  cohortId: string;
  prefixName: string;
  sessionNumber: string;
  date: string;
  startedAt: string;
  endedAt: string | null;
  status: SessionStatus;
  folderPath: string;
  /**
   * 1-based chronological position from (date, startedAt) — never from sessionNumber, which is
   * free text and would sort "10" before "9".
   */
  ordinal: number;
  runCount?: number;
  /**
   * Which groups ran, so Step 1 can offer to continue one of today's sessions with another group
   * (`sessions.resume`).
   */
  groupRuns: GroupRun[];
}

/**
 * One session folder found on disk, identified by name alone (`sessions/paths.py`). What the
 * archive can assert without opening a file: identity and date, never runs or animals.
 */
export interface DiskSession {
  cohortId: string;
  cohortName: string;
  prefixName: string;
  sessionNumber: string;
  /** ISO YYYY-MM-DD, parsed from the folder name — legacy spellings normalized. */
  date: string;
  folderPath: string;
  /**
   * True when this machine's database knows the folder — a session row, or adopted runs from a
   * rescan (§8.1 writes no session row on purpose). False only for a folder another Ephymeris
   * machine wrote that no rescan here has adopted.
   */
  recorded: boolean;
}

/** One metric's whole-session result (`data.md` §9.2, §3.5). */
export interface MetricSummary {
  id: string;
  label: string;
  /**
   * Whole-session P(hit) — what every panel plots. `null` means no trials scored, which is a
   * different claim from zero.
   */
  pSession: number | null;
  /**
   * Rolling P at the authored window, for continuity with Mission Control. Not interchangeable
   * with pSession.
   */
  pWindow: number | null;
  /**
   * Counted trials this metric scored a hit on. Present so two conditions can be POOLED exactly —
   * sum hits, sum counted — rather than by averaging their proportions, which would weight a
   * 20-trial condition like a 200-trial one.
   */
  hits: number;
  counted: number;
  triggered: number;
  excluded: number;
  windowSize: number;
  wilsonLow: number | null;
  wilsonHigh: number | null;
  lowConfidence: boolean;
  /**
   * Which answer this condition rewards, read off its metric's `successCode` (`tasks.md` §4.10).
   * Null whenever the profile cannot prove one — never guessed, and never taken from
   * `alternateCode`, which on a no-go metric means 'any port will do'. This is what lets the
   * strategy plane fold N conditions onto two axes without knowing anything about odors.
   */
  answerSide: AnswerSide | null;
}

/**
 * What actually happened per trial (`data.md` §9.8). Distinct from the declared metrics, which
 * are reward-*unconditional* — they score a detected poke whether or not the fluid hold cleared.
 */
export interface TrialOutcomes {
  /** Every trial boundary seen — one per odor onset. */
  trials: number;
  /**
   * Odor sampled to completion; the denominator for both accuracies. A trial the animal never
   * engaged with is not evidence about discrimination.
   */
  administered: number;
  /** Fluid actually delivered. */
  rewarded: number;
  /** Correct well reached, released before the hold cleared — the right choice, no drop earned. */
  holdFailed: number;
  wrongWell: number;
  /** Administered, but no well was ever answered. */
  noResponse: number;
  /** Never administered — odor port left early, or never poked. */
  aborted: number;
  /** rewarded / administered. Conservative: a hold failure counts against it. */
  pRewarded: number | null;
  /**
   * (rewarded + holdFailed) / administered — the correct side was chosen whether or not the hold
   * earned the drop. Always ≥ pRewarded; the gap between them is the consummatory hold-failure
   * rate.
   */
  pSide: number | null;
  rewardedLow: number | null;
  rewardedHigh: number | null;
  sideLow: number | null;
  sideHigh: number | null;
}

/**
 * How far each offered trial got before the animal dropped out (`data.md` §9.10). Delimited on
 * the trial light, not on odor onset — the firmware only strobes odor-on after the animal has
 * poked and held, so every other count in a run summary is silently conditioned on engagement and
 * none of them can measure it. A ladder, not a partition: presented >= poked >= odorDelivered by
 * construction.
 */
export interface TrialEngagement {
  /** Every trial the box offered — one per trial light. */
  presented: number;
  /** Of those, the ones the animal poked the odor port on. */
  poked: number;
  /**
   * Of those, the ones that reached odor delivery. Equals TrialOutcomes.trials on a well-formed
   * stream — the same trials counted from the other end.
   */
  odorDelivered: number;
  /**
   * presented - poked. The animal never engaged the odor port (LAZY_RAT), plus at most one window
   * a stop or drop truncated.
   */
  noPoke: number;
  /**
   * poked - odorDelivered. Engaged, then let go before the pre-odor hold cleared, so no odor was
   * ever delivered. Distinct from TrialOutcomes.aborted, which received odor and left during
   * sampling.
   */
  pokeAborted: number;
  /** poked / presented. */
  pEngaged: number | null;
  /** odorDelivered / presented. */
  pDelivered: number | null;
  engagedLow: number | null;
  engagedHigh: number | null;
}

/**
 * TrialOutcomes restricted to one declared condition (`data.md` §3.9), in authored liveMetrics
 * order. Answers 'how many trials of this kind were administered, and how many of those paid
 * out'.
 */
export interface ConditionOutcomes {
  metricId: string;
  label: string;
  /**
   * The code that opens this condition's trials — what splits the tally. Two metrics sharing one
   * legitimately cover the same trials.
   */
  triggerCode: number;
  outcomes: TrialOutcomes;
}

export type RunStatus = "ok" | "no-metrics" | "missing" | "unreadable";

/**
 * How much the decoding can be trusted (§8.2). Four states — `sketch-current` means the profile
 * may have changed since the run; `inferred` means no profile resolved at all and the conditions
 * were read out of the recorded stream itself, sound because the strobe registry is append-only
 * but blind to conditions the animal never met.
 */
export type ProfileSource = "snapshot" | "sketch-current" | "inferred" | "unavailable";

export interface RunSummary {
  runId: string;
  sessionId: string;
  animalId: string;
  /** Null for an adopted orphan (§8.1) — a filename carries no box. */
  boxNumber: number | null;
  startedAt: string;
  endedAt: string | null;
  sketchPath: string;
  /**
   * The program this run RECORDS having been run on — the `sketch` field of its own file, falling
   * back to the last segment of `sketchPath`. Not the same question as `sketchPath`, which is
   * where THIS machine found a `task.json` to decode with and is empty for a file copied from
   * another rig (`data.md` §8.2). Empty only when the file named no sketch at all.
   */
  sketchName: string;
  profileHash: string | null;
  /**
   * Hash of the task parameters this run used (`data.md` §6.9). Comparability is the PAIR with
   * `profileHash` — that one covers the profile declaration, which is identical across every run
   * of a sketch however it was tuned. Null for a run recorded before parameters were
   * operator-set.
   */
  paramsHash: string | null;
  profileSource: ProfileSource;
  /** The file is gone but this is its last known-good summary. */
  stale: boolean;
  status: RunStatus;
  metrics: MetricSummary[];
  /**
   * Accuracy pooled across every metric — the only single number that can tell learning from a
   * side bias (§3.7).
   */
  overall: MetricSummary | null;
  /**
   * Null when the profile declares no reward vocabulary (§3.8) — absent rather than zeroed, since
   * 'this task has no notion of a reward delivery' is not 'this animal earned nothing'.
   */
  outcomes: TrialOutcomes | null;
  /**
   * Empty — not null — whenever `outcomes` is null: there is no separate claim to make about a
   * task that can't express an outcome at all.
   */
  conditions: ConditionOutcomes[];
  /**
   * How many trials the box offered and how far each got (§3.10) — the layer above every other
   * count here. Null when the profile declares no trial light, on the same rule as `outcomes`: a
   * zeroed ladder would read as an animal that never engaged rather than as a task that can't
   * say.
   */
  engagement: TrialEngagement | null;
  totalEvents: number;
  durationMs: number | null;
  stopReason: string | null;
  clean: boolean;
  seed: number | null;
  detail: string | null;
  excludedByDefault: boolean;
}

export interface AnalyticsAnimal {
  id: string;
  name: string;
  groupId: string;
  boxNumber: number | null;
  /** Home-cage number, same field as Animal.cage. */
  cage: number | null;
}

/**
 * The kind of answer a condition rewards. `port` is a rig whose response ports carry no side in
 * their strobe names, so it keeps a slot number instead of being called left or right.
 */
export type AnswerSide = "left" | "right" | "withhold" | "port";

export interface ProfileMetricInfo {
  id: string;
  label: string;
  windowSize: number;
  /**
   * See `MetricSummary.answerSide`. Carried on the group as well so a panel can work out its axes
   * before opening a run.
   */
  answerSide: AnswerSide | null;
}

/** A comparability set: two runs share axes only if they share a hash (§4.3). */
export interface ProfileGroup {
  hash: string;
  taskName: string | null;
  kind: string | null;
  metrics: ProfileMetricInfo[];
  runCount: number;
}

export interface AnalyticsWarning {
  code: string;
  runId: string;
  message: string;
}

export interface AnalyticsCounts {
  runs: number;
  decoded: number;
  noProfile: number;
  missing: number;
  unreadable: number;
}

/** The whole cohort table in one call; selections filter it client-side. */
export interface AnalyticsSummary {
  cohortId: string;
  /**
   * The cohort's data folder, verbatim. The Observatory's open-folder button wants exactly this
   * string, and the handler has the cohort in hand already — fetching the full cohort (roster and
   * all) client-side for one path would be the wrong shape of call.
   */
  dataFolder: string;
  sessions: SessionListItem[];
  animals: AnalyticsAnimal[];
  groups: Group[];
  /** Flat, not a matrix — two runs really can share one (animal, session). */
  runs: RunSummary[];
  profileGroups: ProfileGroup[];
  counts: AnalyticsCounts;
  warnings: AnalyticsWarning[];
  minCountedTrials: number;
}

export interface MetricSeries {
  id: string;
  label: string;
  values: number[];
  /**
   * Sample size behind each point — the *window* length, capped at windowSize, not a cumulative
   * count. What a confidence band must use.
   */
  n: number[];
  windowSize: number;
}

/** One sample of the within-session strategy walk (`data.md` §11.1). */
export interface StrategyPoint {
  /**
   * Counted trials resolved across *both* conditions at this sample — the only shared clock the
   * two metrics have.
   */
  trial: number;
  x: number;
  y: number;
  /** The smaller of the two rolling window lengths. */
  n: number;
}

/**
 * One classified trial (`data.md` §9.11) — the same classification pass the outcome tallies come
 * from, kept as a sequence instead of being summed away.
 */
export interface TrialRecord {
  /** 0-based position in the stream's trial order. */
  index: number;
  /**
   * The condition code that opened this trial — one of `boundaries_for`'s union, so a
   * `ConditionOutcomes.triggerCode` matches it directly.
   */
  triggerCode: number;
  outcome: "rewarded" | "hold-failed" | "wrong-well" | "no-response" | "aborted";
  /**
   * Trial open, in ms from the run's first recorded timestamp. Null when the file carries no
   * usable clock.
   */
  atMs: number | null;
  /**
   * Trial open → the code that settled the outcome. Null for no-response/aborted trials, which
   * nothing settles.
   */
  latencyMs: number | null;
}

export interface RunSeries {
  runId: string;
  mode: "rolling" | "cumulative";
  metrics: MetricSeries[];
  /**
   * The joint walk through the strategy plane. Always rolling, whatever `mode` is — 'what
   * strategy is running right now' is a rolling question. Empty unless the profile declares
   * exactly two conditions. Cannot be assembled client-side from `metrics`: those are indexed by
   * each metric's own counted trials, which interleave.
   */
  trail: StrategyPoint[];
  /**
   * Every trial in stream order. Empty when the profile can't express outcomes, on the same rule
   * as `RunSummary.outcomes`. Tallying this list reproduces the run's `TrialOutcomes` and,
   * grouped by `triggerCode`, its `ConditionOutcomes` — pinned by test, so the tape and the
   * tallies can never disagree.
   */
  trials: TrialRecord[];
}

export interface SeriesResult {
  series: RunSeries[];
  warnings: AnalyticsWarning[];
}

export interface RescanOrphan {
  path: string;
  /** Matched by name, never guessed (§8.1). */
  animalId: string | null;
  /**
   * The animal name the *document* carries, reported as written even when it is what failed to
   * match.
   */
  animalName: string | null;
  /**
   * Which recording of the animal `animalId` came from. `filename` means the document's `rat`
   * field matched no animal and the file stem did — an exact match against the roster on a second
   * recording of the same fact, never a guess (§8.1). Null when the run is unattributed.
   */
  animalSource: "document" | "filename" | null;
  date: string | null;
  status: string;
  reason: string | null;
}

/**
 * What the rescan removed because the disk no longer has it (§8.6). Bookkeeping only — the rescan
 * never deletes a file.
 */
export interface RescanPruned {
  /** Recorded `session_animal_runs` rows dropped. */
  runs: number;
  /**
   * Sessions dropped once nothing was left pointing at them — their folder is gone and no run of
   * theirs survived.
   */
  sessions: number;
  /** `adopted_runs` rows dropped. */
  adopted: number;
}

export interface RescanResult {
  scanned: number;
  /**
   * What this scan **decided** — not how many adopted rows the cohort has. A file already adopted
   * from that same path and unchanged since is carried forward unread, so a rescan that changed
   * nothing reports 0 (§8.7).
   */
  adopted: number;
  /**
   * Records reconciled away. Only ever counts paths that are **reachable and absent** — a path
   * under an unreachable root is left alone, so an unplugged drive can't erase history (§8.6).
   */
  pruned: RescanPruned;
  /**
   * Extra copies of an already-seen run, skipped. A hand-managed archive often keeps a
   * consolidated copy beside the per-prefix originals; adopting both would double every animal
   * (§8.1).
   */
  duplicates: number;
  orphans: RescanOrphan[];
  cohortId: string;
  dataFolder: string;
  /**
   * The cohort's data folder isn't on disk — an unplugged drive or a re-lettered volume.
   * Distinguishes 'nothing there' from 'nowhere to look'.
   */
  folderMissing: boolean;
}

export interface AnalyticsProgress {
  cohortId: string;
  phase: "reading" | "walking";
  done: number;
  total: number;
}

/** One orphaned write-ahead log the crash-recovery backfill processed. */
export interface RecoveredTsv {
  tsvPath: string;
  /** Null when recovery failed. */
  jsonPath: string | null;
  status: "recovered" | "failed";
  /** Recomputed from the lines actually parsed, never copied from a footer. */
  nEvents: number;
  /**
   * The footer's recorded reason when the .tsv has one (a finalized run whose best-effort .json
   * write failed); 'recovered after crash' for a footer-less log. Null on failure.
   */
  stopReason: string | null;
  /** Why recovery failed, when it did. */
  reason: string | null;
}

export interface RecoverResult {
  /** Orphaned .tsv files found — write-ahead logs with no .json sibling. */
  scanned: number;
  recovered: number;
  failed: number;
  entries: RecoveredTsv[];
  cohortId: string;
  dataFolder: string;
  /** Same distinction as RescanResult's: 'nothing there' vs 'nowhere to look'. */
  folderMissing: boolean;
}

/** One session record as the tidy preview names it (data.md §8.8). */
export interface TidySession {
  sessionId: string;
  /** `<prefix>_<number>`, as the folder names it. */
  label: string;
  date: string;
  status: SessionStatus;
  startedAt: string;
  /**
   * Recorded runs plus recovered files attributed to it. On an applied merge's `keep`, the merged
   * day's total.
   */
  runCount: number;
  /** Its group runs, in order; a group may repeat. */
  groupIds: string[];
}

export interface TidyMerge {
  /** The earliest record holding data — the day's session. */
  keep: TidySession;
  /** Folded into `keep`: runs re-parented, rows deleted. */
  absorb: TidySession[];
}

export interface TidyEmpty {
  session: TidySession;
  /**
   * The folder exists and holds no file, so it is removed too. A folder with any file in it is
   * never touched.
   */
  removesFolder: boolean;
}

export interface TidySkipped {
  session: TidySession;
  reason: string;
}

export interface TidyPlan {
  cohortId: string;
  /** False for a preview; true once the changes are made. */
  applied: boolean;
  merges: TidyMerge[];
  empty: TidyEmpty[];
  /**
   * Records sharing a folder with the held session or a set-up started today — left whole, and
   * said so.
   */
  skipped: TidySkipped[];
}

export interface ServerHello {
  protocolVersion: number;
  sidecarVersion: string;
}

export interface PortStateData {
  box: number;
  state: PortStateName;
  prev: PortStateName;
  reason: string;
}

export interface PortOutputData {
  box: number;
  lines: OutputLine[];
}

export interface BoardsPresenceData {
  boards: DetectedBoard[];
}

export interface FlashProgressData {
  box: number;
  phase: "compile" | "upload";
  stream: "stdout" | "stderr";
  text: string;
}

export interface CohortsUpdatedData {
  cohorts: CohortSummary[];
}

export interface PrefixesUpdatedData {
  prefixes: Prefix[];
}

/** Failures with no command to attribute them to (§4). */
export interface SidecarErrorData {
  code: string;
  message: string;
  detail: unknown;
}

/**
 * One thing wrong with a wiring document, located. Every problem is reported rather than the
 * first, because fixing new wiring should be one pass rather than a game of whack-a-mole.
 */
export interface RigProblem {
  /** `channels.left_well.kind`, `pins.odor_port`, or a rule's registry file. */
  location: string;
  message: string;
  /**
   * The wiring rule, when one produced it — RIG101 through RIG105. Null for a schema violation,
   * which has no rule number because it is caught before the halves are composed.
   */
  code: string | null;
}

export interface RigStatus {
  /** False ⇒ this rig runs the wiring its build shipped with. */
  custom: boolean;
  /** The shipped pinout this document started as. */
  derivedFrom: string;
  board: string;
  editedAt: string | null;
  /**
   * The composed wiring's hash, over the fields that can change a compiled byte. Prose and pin
   * notes are excluded: it answers 'could these two produce different firmware?', so a reworded
   * rationale must not move it.
   */
  pinoutHash: string;
}

/**
 * The wiring, plus everything wrong with it. `document` is served even when `problems` is
 * non-empty: an editor that refused to show a broken document would be refusing to show the one
 * that needs fixing.
 */
export interface RigDocument {
  /**
   * The rig document itself — `{rig_version, channels, pins}`, validated against
   * rig/schema/rig_hardware.v1.json.
   */
  document: unknown;
  status: RigStatus;
  problems: RigProblem[];
}

/** A task this wiring change would break. Computed BEFORE the write. */
export interface RigImpact {
  specId: string;
  label: string | null;
  /**
   * What this wiring would newly break this task profile with. Empty when the profile was already
   * failing for its own reasons.
   */
  codes: string[];
}

export interface RigSaved {
  status: RigStatus;
  problems: RigProblem[];
  /**
   * Task profiles that generate today and would not after this change. Non-empty does NOT mean
   * the save was refused — see the command.
   */
  breaks: RigImpact[];
}

export interface TaskDiagnostic {
  /** `trials[1].rewardChannel`, `stages[2].trials`. */
  location: string;
  message: string;
  /**
   * TSK101–TSK111 and TSK113 from the sidecar; TSK112 is derived on the Task tab. Each names a
   * failure that is silent without it.
   */
  code: string;
}

/** A row in the profile list, and everything a task card states before the definition is opened. */
export interface TaskEntry {
  id: string;
  /** Also the generated sketch's folder name. */
  name: string;
  category: string;
  /** The generated sketch folder — what `port.flash` takes. */
  path: string;
  label: string;
  /** ISO-8601. */
  editedAt: string | null;
  /**
   * How many diagnostics it currently trips. A COUNT, not the list: this reply is drawn on every
   * route mount and would otherwise grow with the library.
   */
  problems: number;
  /** Rows in the trial table — how many conditions it presents. */
  trials: number;
  /** Rows in the shaping ramp. 1 means no ramp. */
  stages: number;
  /**
   * How the next trial is drawn: a side against recent bias then a type uniformly; a
   * block-shuffled weighted pool; or the side draw with a weighted pick within it.
   */
  selectionMode: "antibias" | "pool" | "weighted";
}

export interface TaskSaved {
  entry: TaskEntry;
  diagnostics: TaskDiagnostic[];
  /**
   * The generated folder, or null when the bundled root sketch could not be read — the profile is
   * stored either way and simply has nothing to flash yet.
   */
  sketchPath: string | null;
}

/** A pure compile of an unsaved definition. Writes nothing. */
export interface TaskPreview {
  diagnostics: TaskDiagnostic[];
  /** Bytes the built START line would occupy, seed included. */
  startLineLength: number;
  /**
   * The firmware's cap, so the editor can show headroom without hardcoding it. Over it is TSK107
   * and a refused generation — `readLineInto()` truncates in silence, so this is checked rather
   * than trusted.
   */
  startLineMax: number;
  /** What this definition compiles to. */
  profile: TaskProfile;
  /**
   * `metadataKey` → the value this field has with NO override, keyed the same way
   * `profile.config[].default` is. The editor needs both to know which values this profile
   * actually pins: a definition stores only divergences, so a value merely EQUAL to the
   * catalogue's must not be written into it — that would freeze it against a later correction to
   * the range or the default.
   */
  catalogueDefaults: Record<string, unknown>;
}

export interface TasksUpdatedData {
  tasks: TaskEntry[];
}

export interface StrobeCode {
  name: string;
  code: number;
  /** `firmware` (transcribed from BehaviorBox.h) or `ephymeris`. */
  origin: string;
  emittedOn?: string;
  rationale?: string;
}

/**
 * Emitted by firmware this repository no longer contains. Reserved forever: reissuing one would
 * merge two unrelated event types in any analysis spanning the change.
 */
export interface RetiredStrobe {
  name: string;
  code: number;
}

/**
 * The append-only strobe registry. Codes are never renumbered, never repurposed and never deleted
 * — four years of recorded sessions carry them.
 */
export interface StrobeVocabulary {
  version: number;
  codeMin: number;
  /** 999 — a wire-format limit. The host parser is ^\d{1,3}\t\d+$. */
  codeMax: number;
  /** Inclusive [lo, hi] pairs a new code may come from. */
  freeRanges: number[][];
  codes: StrobeCode[];
  retired: RetiredStrobe[];
  /** Slot number → its six per-port code names. */
  portSlots: Record<string, Record<string, string>>;
}

export interface RecordingBox {
  box: number;
  /** The controller input this box's sync line reaches, 1–16. */
  digitalIn: number;
  /** Headstage port letter, A–H. */
  port: string;
  /** Native channel names recorded for this box. */
  channels: string[];
  /** File name of the probe map copied beside the data. */
  probeMap: string | null;
}

/**
 * One group run's recording. A session records once per group, because the animals — and so the
 * ports and probes — change between groups.
 */
export interface RecordingRun {
  groupId: string;
  /** The directory handed to RHX as `Filename.Path`. */
  path: string;
  baseFilename: string;
  /**
   * RHX's own `YYMMDD_HHMMSS` suffix, read back after the recording started — it names the folder
   * and files RHX actually created.
   */
  fileTimestamp: string | null;
  fileFormat: string;
  sampleRate: number;
  startedAt: string | null;
  endedAt: string | null;
  boxes: RecordingBox[];
}

export interface SessionRecording {
  runs: RecordingRun[];
}

export interface RecordingBoxConfig {
  box: number;
  port: string;
  firstChannel: number;
  lastChannel: number;
  probeMapPath?: string | null;
}

export interface RecordingThreshold {
  /** `keep` leaves RHX's thresholds as the operator set them there. */
  mode: "keep" | "absolute" | "rms";
  /** Absolute threshold, −5000…5000 µV. */
  microvolts: number;
  /** 3.0…20.0 × each channel's RMS noise. */
  rmsMultiple: number;
  /** Polarity of the RMS-relative threshold. */
  negative: boolean;
}

/** Everything the recording walkthrough collects (`recording.md` §4). */
export interface RecordingConfig {
  saveDirectory: string;
  fileFormat: "Traditional" | "OneFilePerSignalType" | "OneFilePerChannel";
  saveWideband: boolean;
  saveSpikes: boolean;
  saveSpikeSnapshots: boolean;
  /** 0…3, stored positive; RHX takes it negated. */
  snapshotPreMs: number;
  /** 1…6. */
  snapshotPostMs: number;
  saveLowpass: boolean;
  /** 1, 2, 4 … 128. */
  lowpassDownsample: number;
  saveHighpass: boolean;
  /** Traditional format only; 1…999. */
  newFileMinutes?: number;
  threshold: RecordingThreshold;
  boxes: RecordingBoxConfig[];
}

export type IntanState = "disconnected" | "idle" | "configured" | "recording" | "stopping" | "error";

/**
 * How well a box's sync edges are pairing with its strobes. A climbing `unmatchedStrobes` with
 * zero `matched` is a sync line that is not connected.
 */
export interface IntanSyncStat {
  box: number;
  matched: number;
  spuriousEdges: number;
  unmatchedStrobes: number;
}

export interface IntanStatus {
  state: IntanState;
  /** Why, when the state alone does not say. */
  message: string | null;
  connected: boolean;
  /** RHX's `Type`, e.g. ControllerRecordUSB3. */
  controller: string | null;
  version: string | null;
  sampleRate: number | null;
  /** RHX is generating data; no controller is attached. */
  synthetic: boolean;
  headstagePresent: boolean;
  runMode: string | null;
  /** Port letter → amplifier channels present. */
  ports: Record<string, number>;
  /**
   * False when this RHX does not answer a `get` that rides a batch, so a refused command cannot
   * be detected (`recording.md` §2).
   */
  confirmsWrites: boolean | null;
  /** This rig's wiring declares a `sync` channel. */
  rigHasSync: boolean;
  /** The waveform and spike sockets are both open. */
  liveStreams: boolean;
  recording: RecordingRun | null;
  /** While `stopping`: boxes still finishing their trial. */
  waitingOn: number[];
  sync: IntanSyncStat[];
}

export type ScopeKind = "spikescope" | "psth" | "isi" | "probemap";

export interface ScopeData {
  scopeId: string;
  kind: ScopeKind;
  box: number;
  channel: string | null;
  /** Per kind; see `recording.md` §7. */
  data: unknown;
}

// --- Per-command and per-event payload maps --------------------------------

/** Args each command takes; `Record<string, never>` = none. */
export interface CommandArgsMap {
  "auth": { token: string };
  "settings.push": { settings: EphymerisSettings };
  "sketches.refresh": Record<string, never>;
  "port.passthrough.open": { box: number; baud?: number };
  "port.passthrough.close": { box: number };
  "port.send": { box: number; text: string; lineEnding?: "none" | "lf" | "cr" | "crlf" };
  "port.sendStart": { box: number; sketchPath: string; config?: Record<string, unknown> };
  "port.flash": { box: number; sketchPath: string; suppressPassthroughResume?: boolean };
  "port.reset": { box: number };
  "port.error.ack": { box: number };
  "utility.ensure": { boxes?: number[]; force?: boolean };
  "utility.identify": { box: number; on: boolean };
  "cohorts.list": Record<string, never>;
  "cohorts.get": { id: string };
  "cohorts.create": { name: string; dataFolder?: string; animals?: Animal[]; groups?: Group[] };
  "cohorts.update": { id: string; patch: CohortPatch };
  "cohorts.archive": { id: string };
  "cohorts.restore": { id: string };
  "cohorts.delete": { id: string; confirm: boolean };
  "cohorts.setDataFolder": { id: string; path: string; moveExisting: boolean };
  "cohorts.suggestGroups": { id: string; groupCount?: number; maxGroupSize?: number; balanceBySex?: boolean };
  "prefixes.list": Record<string, never>;
  "prefixes.create": { name: string };
  "prefixes.delete": { id: string };
  "tasks.getProfile": { sketchPath: string };
  "tasks.list": Record<string, never>;
  "tasks.get": { taskId: string };
  "tasks.preview": { definition: unknown };
  "tasks.save": { definition: unknown };
  "tasks.delete": { taskId: string };
  "rig.strobes": Record<string, never>;
  "sessions.suggestNumber": { prefixId: string };
  "sessions.create": { cohortId: string; prefixId: string; sessionNumber: string; durationMinutes?: number; recording?: boolean };
  "sessions.abandon": { sessionId: string };
  "sessions.confirmMapping": { sessionId: string; groupId: string; boxes: SessionBoxMapping[] };
  "sessions.status": { sessionId: string };
  "sessions.startAll": { sessionId: string };
  "sessions.endGroup": { sessionId: string };
  "sessions.resume": { sessionId: string };
  "sessions.end": { sessionId: string };
  "sessions.active": Record<string, never>;
  "port.startSession": { box: number };
  "port.stopSession": { box: number };
  "backup.syncNow": Record<string, never>;
  "sessions.list": { cohortId: string; includeAborted?: boolean };
  "analytics.summary": { cohortId: string; sessionIds?: string[]; animalIds?: string[]; minCountedTrials?: number };
  "analytics.series": { runIds: string[]; mode?: "rolling" | "cumulative"; metricIds?: string[] };
  "analytics.rescan": { cohortId: string; adoptOrphans?: boolean };
  "analytics.recentSessions": { limit?: number };
  "sessions.recover": { cohortId: string };
  "sessions.tidy": { cohortId: string; apply?: boolean };
  "hardware.get": Record<string, never>;
  "hardware.preview": { document: unknown };
  "hardware.save": { document: unknown; confirm: boolean };
  "hardware.reset": Record<string, never>;
  "intan.status": Record<string, never>;
  "intan.connect": Record<string, never>;
  "intan.disconnect": Record<string, never>;
  "intan.configure": { sessionId: string; groupId: string; config: RecordingConfig };
  "intan.parseProbeMap": { path: string };
  "intan.probeMap": { box: number };
  "intan.setThreshold": { channel: string; microvolts: number };
  "intan.scope.open": { kind: ScopeKind; box: number; channel?: string | null; params?: Record<string, unknown> };
  "intan.scope.update": { scopeId: string; channel?: string | null; params?: Record<string, unknown> };
  "intan.scope.close": { scopeId: string };
  "intan.forceStop": Record<string, never>;
}

/** The `result` field of each command's ok-reply. */
export interface CommandResultMap {
  "auth": { authenticated: boolean };
  "settings.push": { library: SketchLibraryStatus };
  "sketches.refresh": SketchDiscovery;
  "port.passthrough.open": { state: PortStateName };
  "port.passthrough.close": { state: PortStateName };
  "port.send": { bytesWritten: number };
  "port.sendStart": { command: string; bytesWritten: number };
  "port.flash": { state: PortStateName; resumedPassthrough: boolean };
  "port.reset": { state: PortStateName; resumedPassthrough: boolean };
  "port.error.ack": { state: PortStateName };
  "utility.ensure": UtilityStatus;
  "utility.identify": { delivered: boolean; state: UtilityBoxState };
  "cohorts.list": { cohorts: CohortSummary[] };
  "cohorts.get": { cohort: Cohort };
  "cohorts.create": { cohort: Cohort };
  "cohorts.update": { cohort: Cohort };
  "cohorts.archive": { cohort: Cohort };
  "cohorts.restore": { cohort: Cohort };
  "cohorts.delete": { deleted: boolean };
  "cohorts.setDataFolder": { cohort: Cohort };
  "cohorts.suggestGroups": GroupProposal;
  "prefixes.list": { prefixes: Prefix[] };
  "prefixes.create": { prefix: Prefix };
  "prefixes.delete": { deleted: boolean };
  "tasks.getProfile": TaskProfile | { profile: null };
  "tasks.list": { tasks: TaskEntry[] };
  "tasks.get": { definition: unknown; diagnostics: TaskDiagnostic[] };
  "tasks.preview": TaskPreview;
  "tasks.save": TaskSaved;
  "tasks.delete": { deleted: boolean };
  "rig.strobes": StrobeVocabulary;
  "sessions.suggestNumber": { suggestion: string | null; sameDayNumbers: string[] };
  "sessions.create": { session: Session };
  "sessions.abandon": { session: Session };
  "sessions.confirmMapping": { ok: boolean };
  "sessions.status": { session: Session; groupId: string | null; boxes: SessionBox[] };
  "sessions.startAll": { session: Session };
  "sessions.endGroup": { session: Session };
  "sessions.resume": { session: Session };
  "sessions.end": { session: Session };
  "sessions.active": ActiveSessions;
  "port.startSession": { state: PortStateName };
  "port.stopSession": { state: PortStateName };
  "backup.syncNow": SyncResult;
  "sessions.list": { sessions: SessionListItem[] };
  "analytics.summary": AnalyticsSummary;
  "analytics.series": SeriesResult;
  "analytics.rescan": RescanResult;
  "analytics.recentSessions": { sessions: DiskSession[] };
  "sessions.recover": RecoverResult;
  "sessions.tidy": TidyPlan;
  "hardware.get": RigDocument;
  "hardware.preview": RigSaved;
  "hardware.save": RigSaved;
  "hardware.reset": RigDocument;
  "intan.status": IntanStatus;
  "intan.connect": IntanStatus;
  "intan.disconnect": IntanStatus;
  "intan.configure": IntanStatus;
  "intan.parseProbeMap": { probeMap: unknown };
  "intan.probeMap": { probeMap: unknown };
  "intan.setThreshold": { channel: string; microvolts: number };
  "intan.scope.open": { scopeId: string };
  "intan.scope.update": { ok: boolean };
  "intan.scope.close": { ok: boolean };
  "intan.forceStop": { ok: boolean };
}

/** The `data` field of each event. */
export interface EventDataMap {
  "server.hello": ServerHello;
  "port.state": PortStateData;
  "port.output": PortOutputData;
  "port.telemetry": PortTelemetry;
  "boards.presence": BoardsPresenceData;
  "flash.progress": FlashProgressData;
  "sketches.updated": SketchDiscovery;
  "cohorts.updated": CohortsUpdatedData;
  "prefixes.updated": PrefixesUpdatedData;
  "session.telemetry": BoxTelemetry;
  "session.animalEnded": AnimalEnded;
  "session.lifecycle": ActiveSessions;
  "hardware.updated": RigStatus;
  "utility.updated": UtilityStatus;
  "backup.status": BackupStatus;
  "analytics.progress": AnalyticsProgress;
  "sidecar.error": SidecarErrorData;
  "tasks.updated": TasksUpdatedData;
  "intan.status": IntanStatus;
  "intan.scope.data": ScopeData;
}

// --- Envelopes -------------------------------------------------------------

export interface CommandMessage {
  v: number;
  id: string;
  cmd: string;
  args: Record<string, unknown>;
}

export interface ProtocolError {
  code: ErrorCode | string;
  message: string;
  detail?: unknown;
}

export interface ReplyOk {
  v: number;
  corr: string;
  ok: true;
  result: unknown;
}

export interface ReplyErr {
  v: number;
  corr: string;
  ok: false;
  error: ProtocolError;
}

export type Reply = ReplyOk | ReplyErr;

export interface EventMessage {
  v: number;
  evt: string;
  ts: number;
  data: unknown;
  corr?: string;
}

export type ServerMessage = Reply | EventMessage;

export function isEvent(msg: ServerMessage): msg is EventMessage {
  return "evt" in msg;
}

export function isReply(msg: ServerMessage): msg is Reply {
  return "corr" in msg && "ok" in msg;
}

/** Thrown by `SidecarClient.call` when the sidecar rejects a command. */
export class SidecarCommandError extends Error {
  readonly code: string;
  readonly detail: unknown;

  constructor(error: ProtocolError) {
    super(error.message);
    this.name = "SidecarCommandError";
    this.code = error.code;
    this.detail = error.detail;
  }
}
