"""Canonical wire protocol between the frontend and this sidecar.

GENERATED by protocol/generate.py from protocol/schema.py — DO NOT EDIT.
Regenerate with `npm run gen:protocol` (or `python protocol/generate.py`).

`docs/websocket-protocol.md` carries the prose (rationale, lifecycle,
invariants); `protocol/schema.py` is the shape authority this module and
`src/lib/ws/protocol.ts` are generated from.

Envelope shapes:

    client -> server   {"v", "id", "cmd", "args"}
    server -> client   {"v", "corr", "ok": true,  "result"}      (reply)
                       {"v", "corr", "ok": false, "error"}       (reply)
                       {"v", "evt", "ts", "data", "corr"?}       (event)
"""

from __future__ import annotations

import os
import time
from typing import Any, Final

PROTOCOL_VERSION: Final = 1


# --- Commands (client -> server) ------------------------------------------

class Cmd:
    # Connection & hardware
    AUTH: Final = "auth"
    PING: Final = "ping"
    SETTINGS_PUSH: Final = "settings.push"
    SKETCHES_REFRESH: Final = "sketches.refresh"
    PORT_PASSTHROUGH_OPEN: Final = "port.passthrough.open"
    PORT_PASSTHROUGH_CLOSE: Final = "port.passthrough.close"
    PORT_SEND: Final = "port.send"
    PORT_FLASH: Final = "port.flash"
    PORT_RESET: Final = "port.reset"
    PORT_ERROR_ACK: Final = "port.error.ack"

    # Hardware utility baseline (settings.md §8)
    UTILITY_STATUS: Final = "utility.status"
    UTILITY_ENSURE: Final = "utility.ensure"
    UTILITY_IDENTIFY: Final = "utility.identify"

    # Cohorts (cohorts.md)
    COHORTS_LIST: Final = "cohorts.list"
    COHORTS_GET: Final = "cohorts.get"
    COHORTS_CREATE: Final = "cohorts.create"
    COHORTS_UPDATE: Final = "cohorts.update"
    COHORTS_ARCHIVE: Final = "cohorts.archive"
    COHORTS_RESTORE: Final = "cohorts.restore"
    COHORTS_DELETE: Final = "cohorts.delete"
    COHORTS_SET_DATA_FOLDER: Final = "cohorts.setDataFolder"
    COHORTS_SUGGEST_GROUPS: Final = "cohorts.suggestGroups"

    # Prefixes, Task Profiles & sessions
    PREFIXES_LIST: Final = "prefixes.list"
    PREFIXES_CREATE: Final = "prefixes.create"
    PREFIXES_DELETE: Final = "prefixes.delete"
    TASKS_GET_PROFILE: Final = "tasks.getProfile"
    SESSIONS_SUGGEST_NUMBER: Final = "sessions.suggestNumber"
    SESSIONS_CREATE: Final = "sessions.create"
    SESSIONS_ABANDON: Final = "sessions.abandon"
    SESSIONS_CONFIRM_MAPPING: Final = "sessions.confirmMapping"
    SESSIONS_STATUS: Final = "sessions.status"
    SESSIONS_START_ALL: Final = "sessions.startAll"
    SESSIONS_SWITCH_GROUP: Final = "sessions.switchGroup"
    SESSIONS_END: Final = "sessions.end"
    SESSIONS_ACTIVE: Final = "sessions.active"
    PORT_START_SESSION: Final = "port.startSession"
    PORT_STOP_SESSION: Final = "port.stopSession"

    # Backup (data.md §7)
    BACKUP_SYNC_NOW: Final = "backup.syncNow"

    # Analytics (websocket-protocol.md §3.4)
    SESSIONS_LIST: Final = "sessions.list"
    ANALYTICS_SUMMARY: Final = "analytics.summary"
    ANALYTICS_SERIES: Final = "analytics.series"
    ANALYTICS_RESCAN: Final = "analytics.rescan"
    ANALYTICS_RECENT_SESSIONS: Final = "analytics.recentSessions"

    # Crash recovery (data.md §12, §11)
    SESSIONS_RECOVER: Final = "sessions.recover"

    # Task specs (specs.md)
    SPECS_LIST: Final = "specs.list"
    SPECS_GET: Final = "specs.get"
    SPECS_SCHEMA: Final = "specs.schema"
    SPECS_COMPILE: Final = "specs.compile"
    SPECS_CAPABILITIES: Final = "specs.capabilities"
    SPECS_PARADIGMS: Final = "specs.paradigms"
    SPECS_SKELETON: Final = "specs.skeleton"
    SPECS_SAVE: Final = "specs.save"
    SPECS_DELETE: Final = "specs.delete"
    SPECS_DIFF: Final = "specs.diff"
    SPECS_EXPORT: Final = "specs.export"

    # Bench boxes (specs.md)
    BOARD_CAPABILITIES: Final = "board.capabilities"
    BOARD_UPLOAD_TABLE: Final = "board.uploadTable"
    UTILITY_BENCH_HOLD: Final = "utility.benchHold"


ALL_COMMANDS: Final[frozenset[str]] = frozenset(
    v for k, v in vars(Cmd).items() if not k.startswith("_") and isinstance(v, str)
)


# --- Events (server -> client) --------------------------------------------

class Evt:
    SERVER_HELLO: Final = "server.hello"
    PORT_STATE: Final = "port.state"
    PORT_OUTPUT: Final = "port.output"
    BOARDS_PRESENCE: Final = "boards.presence"
    FLASH_PROGRESS: Final = "flash.progress"
    SKETCHES_UPDATED: Final = "sketches.updated"
    COHORTS_UPDATED: Final = "cohorts.updated"
    PREFIXES_UPDATED: Final = "prefixes.updated"
    SESSION_TELEMETRY: Final = "session.telemetry"
    SESSION_ANIMAL_ENDED: Final = "session.animalEnded"
    SESSION_LIFECYCLE: Final = "session.lifecycle"
    UTILITY_UPDATED: Final = "utility.updated"
    BACKUP_STATUS: Final = "backup.status"
    ANALYTICS_PROGRESS: Final = "analytics.progress"
    SIDECAR_ERROR: Final = "sidecar.error"
    SPECS_UPDATED: Final = "specs.updated"
    UPLOAD_PROGRESS: Final = "upload.progress"


ALL_EVENTS: Final[frozenset[str]] = frozenset(
    v for k, v in vars(Evt).items() if not k.startswith("_") and isinstance(v, str)
)


# --- Error codes ----------------------------------------------------------

class ErrCode:
    BAD_MESSAGE: Final = "BAD_MESSAGE"
    UNKNOWN_COMMAND: Final = "UNKNOWN_COMMAND"
    UNAUTHORIZED: Final = "UNAUTHORIZED"
    PROTOCOL_VERSION_MISMATCH: Final = "PROTOCOL_VERSION_MISMATCH"
    ILLEGAL_TRANSITION: Final = "ILLEGAL_TRANSITION"
    SEND_NOT_PASSTHROUGH: Final = "SEND_NOT_PASSTHROUGH"
    PORT_NOT_BOUND: Final = "PORT_NOT_BOUND"
    PORT_OPEN_FAILED: Final = "PORT_OPEN_FAILED"
    FLASH_FAILED: Final = "FLASH_FAILED"
    SKETCH_UNKNOWN: Final = "SKETCH_UNKNOWN"
    COHORT_NOT_FOUND: Final = "COHORT_NOT_FOUND"
    COHORT_NAME_TAKEN: Final = "COHORT_NAME_TAKEN"
    COHORT_INVALID: Final = "COHORT_INVALID"
    COHORT_NOT_ARCHIVED: Final = "COHORT_NOT_ARCHIVED"
    DATA_FOLDER_INVALID: Final = "DATA_FOLDER_INVALID"
    PREFIX_NAME_TAKEN: Final = "PREFIX_NAME_TAKEN"
    SESSION_INVALID: Final = "SESSION_INVALID"
    SESSION_NOT_READY: Final = "SESSION_NOT_READY"
    TASK_PROFILE_INVALID: Final = "TASK_PROFILE_INVALID"
    BACKUP_UNAVAILABLE: Final = "BACKUP_UNAVAILABLE"
    UTILITY_UNAVAILABLE: Final = "UTILITY_UNAVAILABLE"
    SPEC_NOT_FOUND: Final = "SPEC_NOT_FOUND"
    SPEC_INVALID: Final = "SPEC_INVALID"
    SPEC_COMPILER_UNAVAILABLE: Final = "SPEC_COMPILER_UNAVAILABLE"
    UPLOAD_REFUSED: Final = "UPLOAD_REFUSED"
    UPLOAD_FAILED: Final = "UPLOAD_FAILED"
    INTERNAL: Final = "INTERNAL"


ALL_ERROR_CODES: Final[frozenset[str]] = frozenset(
    v for k, v in vars(ErrCode).items() if not k.startswith("_") and isinstance(v, str)
)


# --- Payload shape specs --------------------------------------------------
#
# Runtime data for `validate()`. Encoding: a primitive is its name; every
# composite is a ("tag", ...) tuple — ("lit", values), ("list", item),
# ("map", value), ("union", options), ("ref", shape_name), and
# ("obj", ((field, spec, optional), ...)).

SHAPES: Final[dict[str, Any]] = {
    "PortStateName": ('lit', ('IDLE', 'PASSTHROUGH', 'FLASHING', 'UPLOADING', 'RESETTING', 'IN_SESSION', 'ERROR')),
    "OutputLine": ('obj', (('dir', ('lit', ('rx', 'tx')), False), ('text', 'str', False), ('ts', 'float', False))),
    "DetectedBoard": ('obj', (('hardwareId', 'str', False), ('address', 'str', False), ('fqbn', ('union', ('str', 'null')), False), ('boxId', ('union', ('int', 'null')), False))),
    "LibraryState": ('lit', ('ok', 'empty', 'damaged')),
    "SketchLibraryStatus": ('obj', (('state', ('ref', 'LibraryState'), False), ('path', ('union', ('str', 'null')), False), ('message', ('union', ('str', 'null')), False), ('source', ('lit', ('bundled', 'override')), False))),
    "SketchEntry": ('obj', (('category', 'str', False), ('name', 'str', False), ('path', 'str', False))),
    "SkippedEntry": ('obj', (('path', 'str', False), ('reason', 'str', False))),
    "SketchDiscovery": ('obj', (('library', ('ref', 'SketchLibraryStatus'), False), ('sketches', ('list', ('ref', 'SketchEntry')), False), ('skipped', ('list', ('ref', 'SkippedEntry')), False), ('skippedCount', 'int', False), ('libraries', ('list', 'str'), False), ('librariesPath', ('union', ('str', 'null')), False))),
    "BoxBinding": ('obj', (('box', 'int', False), ('hardwareId', ('union', ('str', 'null')), False), ('label', 'str', False))),
    "EphymerisSettings": ('obj', (('dataDirectory', ('union', ('str', 'null')), False), ('backupDirectory', ('union', ('str', 'null')), False), ('arduinoCliPath', ('union', ('str', 'null')), False), ('utilitySketchName', ('union', ('str', 'null')), False), ('defaultBaud', 'int', False), ('boxes', ('list', ('ref', 'BoxBinding')), False), ('reducedMotion', 'bool', False), ('constellation', ('union', ('str', 'null')), False), ('constellationSlots', ('map', 'int'), False), ('boxSetupComplete', 'bool', False), ('taskDefaults', ('map', ('map', 'any')), False))),
    "UtilityBaselineState": ('lit', ('unknown', 'restoring', 'ready', 'busy', 'held', 'unavailable', 'failed')),
    "UtilityBoxState": ('obj', (('box', 'int', False), ('state', ('ref', 'UtilityBaselineState'), False), ('detail', ('union', ('str', 'null')), False), ('identifying', 'bool', False))),
    "UtilityStatus": ('obj', (('configured', 'bool', False), ('sketchPath', ('union', ('str', 'null')), False), ('sketchName', ('union', ('str', 'null')), False), ('canIdentify', 'bool', False), ('held', 'bool', False), ('message', ('union', ('str', 'null')), False), ('boxes', ('list', ('ref', 'UtilityBoxState')), False))),
    "BackupState": ('lit', ('disabled', 'pending', 'ok', 'failed')),
    "BackupStatus": ('obj', (('configured', 'bool', False), ('directory', ('union', ('str', 'null')), False), ('state', ('ref', 'BackupState'), False), ('pending', 'int', False), ('tracking', 'int', False), ('mirroredFiles', 'int', False), ('lastSuccessAt', ('union', ('str', 'null')), False), ('lastError', ('union', ('str', 'null')), False), ('syncing', 'bool', False), ('intervalSeconds', 'float', False))),
    "SyncResult": ('obj', (('copied', 'int', False), ('skipped', 'int', False), ('failed', 'int', False), ('errors', ('list', 'str'), False), ('directory', 'str', False))),
    "Sex": ('lit', ('M', 'F', 'unknown')),
    "Group": ('obj', (('id', 'str', False), ('name', 'str', False), ('order', 'int', False))),
    "Animal": ('obj', (('id', 'str', False), ('name', 'str', False), ('groupId', 'str', False), ('boxNumber', ('union', ('int', 'null')), False), ('cage', ('union', ('int', 'null')), False), ('sex', ('union', (('ref', 'Sex'), 'null')), False), ('idNumber', ('union', ('str', 'null')), False), ('notes', ('union', ('str', 'null')), False))),
    "Cohort": ('obj', (('id', 'str', False), ('name', 'str', False), ('dataFolder', 'str', False), ('animals', ('list', ('ref', 'Animal')), False), ('groups', ('list', ('ref', 'Group')), False), ('archivedAt', ('union', ('str', 'null')), False), ('createdAt', 'str', False), ('updatedAt', 'str', False))),
    "CohortSummary": ('obj', (('id', 'str', False), ('name', 'str', False), ('animalCount', 'int', False), ('groupCount', 'int', False), ('assignedBoxes', ('list', 'int'), False), ('archived', 'bool', False), ('createdAt', 'str', False), ('updatedAt', 'str', False))),
    "CohortPatch": ('obj', (('name', 'str', True), ('animals', ('list', ('ref', 'Animal')), True), ('groups', ('list', ('ref', 'Group')), True))),
    "ProposedAnimal": ('obj', (('animalId', 'str', False), ('boxNumber', 'int', False))),
    "ProposedGroup": ('obj', (('name', 'str', False), ('order', 'int', False), ('animals', ('list', ('ref', 'ProposedAnimal')), False))),
    "GroupRejection": ('obj', (('reason', 'str', False), ('minimumGroups', 'int', False))),
    "GroupProposal": ('obj', (('groups', ('list', ('ref', 'ProposedGroup')), False), ('rejected', ('union', (('ref', 'GroupRejection'), 'null')), False))),
    "Prefix": ('obj', (('id', 'str', False), ('name', 'str', False))),
    "SessionStatus": ('lit', ('configuring', 'running', 'completed', 'aborted')),
    "GroupRun": ('obj', (('groupId', 'str', False), ('order', 'int', False), ('startedAt', 'str', False), ('endedAt', ('union', ('str', 'null')), False))),
    "Session": ('obj', (('id', 'str', False), ('cohortId', 'str', False), ('prefixId', 'str', False), ('prefixName', 'str', False), ('sessionNumber', 'str', False), ('date', 'str', False), ('startedAt', 'str', False), ('endedAt', ('union', ('str', 'null')), False), ('status', ('ref', 'SessionStatus'), False), ('folderPath', 'str', False), ('groupRuns', ('list', ('ref', 'GroupRun')), False), ('durationMinutes', ('union', ('int', 'null')), False))),
    "ConfigFieldType": ('lit', ('int', 'float', 'bool', 'string')),
    "ConfigField": ('obj', (('metadataKey', 'str', False), ('wireKey', 'str', False), ('label', 'str', False), ('type', ('ref', 'ConfigFieldType'), False), ('default', 'any', False), ('group', 'str', True), ('unit', 'str', True), ('min', ('union', ('int', 'float')), True), ('max', ('union', ('int', 'float')), True), ('step', ('union', ('int', 'float')), True), ('help', 'str', True), ('advanced', 'bool', True))),
    "LiveMetric": ('obj', (('id', 'str', False), ('label', 'str', False), ('triggerCode', 'int', False), ('successCode', 'int', False), ('alternateCode', 'int', False), ('windowSize', 'int', False))),
    "ProfileKind": ('lit', ('behavior', 'utility')),
    "ControlOption": ('obj', (('label', 'str', False), ('command', 'str', False))),
    "ControlChannel": ('obj', (('label', 'str', False), ('state', 'str', True), ('toggle', 'str', True), ('pulse', 'str', True))),
    "Control": ('obj', (('id', 'str', False), ('label', 'str', False), ('type', ('lit', ('button', 'select', 'grid')), False), ('command', 'str', True), ('options', ('list', ('ref', 'ControlOption')), True), ('channels', ('list', ('ref', 'ControlChannel')), True))),
    "TelemetryField": ('obj', (('key', 'str', False), ('label', 'str', False))),
    "TelemetrySpec": ('obj', (('match', 'str', False), ('fields', ('list', ('ref', 'TelemetryField')), False))),
    "IdentifySpec": ('obj', (('on', 'str', False), ('off', 'str', False))),
    "TaskProfile": ('obj', (('taskName', 'str', False), ('kind', ('ref', 'ProfileKind'), False), ('config', ('list', ('ref', 'ConfigField')), False), ('strobes', ('map', 'str'), False), ('liveMetrics', ('list', ('ref', 'LiveMetric')), False), ('controls', ('list', ('ref', 'Control')), False), ('legacyNames', ('list', 'str'), False), ('telemetry', ('ref', 'TelemetrySpec'), True), ('identify', ('ref', 'IdentifySpec'), True))),
    "SessionBoxMapping": ('obj', (('box', 'int', False), ('animalId', 'str', False), ('sketchPath', 'str', False), ('config', ('map', 'any'), False))),
    "SessionBox": ('obj', (('box', 'int', False), ('animalId', 'str', False), ('animalName', 'str', False), ('sketchName', 'str', False), ('sketchPath', 'str', False), ('running', 'bool', False), ('startedAt', ('union', ('str', 'null')), False))),
    "TelemetryMetric": ('obj', (('id', 'str', False), ('value', ('union', ('float', 'null')), False), ('n', 'int', False))),
    "BoxTelemetry": ('obj', (('box', 'int', False), ('animalId', 'str', False), ('metrics', ('list', ('ref', 'TelemetryMetric')), False))),
    "AnimalEnded": ('obj', (('box', 'int', False), ('animalId', 'str', False), ('stopReason', 'str', False), ('filePath', ('union', ('str', 'null')), False))),
    "RunnerSession": ('obj', (('session', ('ref', 'Session'), False), ('groupId', ('union', ('str', 'null')), False), ('boxes', ('list', ('ref', 'SessionBox')), False))),
    "ActiveSessions": ('obj', (('running', ('union', (('ref', 'RunnerSession'), 'null')), False), ('configuring', ('list', ('ref', 'Session')), False), ('stale', ('list', ('ref', 'Session')), False))),
    "SessionListItem": ('obj', (('id', 'str', False), ('cohortId', 'str', False), ('prefixName', 'str', False), ('sessionNumber', 'str', False), ('date', 'str', False), ('startedAt', 'str', False), ('endedAt', ('union', ('str', 'null')), False), ('status', ('ref', 'SessionStatus'), False), ('folderPath', 'str', False), ('ordinal', 'int', False), ('runCount', 'int', True))),
    "DiskSession": ('obj', (('cohortId', 'str', False), ('cohortName', 'str', False), ('prefixName', 'str', False), ('sessionNumber', 'str', False), ('date', 'str', False), ('folderPath', 'str', False), ('recorded', 'bool', False))),
    "MetricSummary": ('obj', (('id', 'str', False), ('label', 'str', False), ('pSession', ('union', ('float', 'null')), False), ('pWindow', ('union', ('float', 'null')), False), ('counted', 'int', False), ('triggered', 'int', False), ('excluded', 'int', False), ('windowSize', 'int', False), ('wilsonLow', ('union', ('float', 'null')), False), ('wilsonHigh', ('union', ('float', 'null')), False), ('lowConfidence', 'bool', False))),
    "TrialOutcomes": ('obj', (('trials', 'int', False), ('administered', 'int', False), ('rewarded', 'int', False), ('holdFailed', 'int', False), ('wrongWell', 'int', False), ('noResponse', 'int', False), ('aborted', 'int', False), ('pRewarded', ('union', ('float', 'null')), False), ('pSide', ('union', ('float', 'null')), False), ('rewardedLow', ('union', ('float', 'null')), False), ('rewardedHigh', ('union', ('float', 'null')), False), ('sideLow', ('union', ('float', 'null')), False), ('sideHigh', ('union', ('float', 'null')), False))),
    "TrialEngagement": ('obj', (('presented', 'int', False), ('poked', 'int', False), ('odorDelivered', 'int', False), ('noPoke', 'int', False), ('pokeAborted', 'int', False), ('pEngaged', ('union', ('float', 'null')), False), ('pDelivered', ('union', ('float', 'null')), False), ('engagedLow', ('union', ('float', 'null')), False), ('engagedHigh', ('union', ('float', 'null')), False))),
    "ConditionOutcomes": ('obj', (('metricId', 'str', False), ('label', 'str', False), ('triggerCode', 'int', False), ('outcomes', ('ref', 'TrialOutcomes'), False))),
    "RunStatus": ('lit', ('ok', 'no-metrics', 'missing', 'unreadable')),
    "ProfileSource": ('lit', ('snapshot', 'sketch-current', 'unavailable')),
    "RunSummary": ('obj', (('runId', 'str', False), ('sessionId', 'str', False), ('animalId', 'str', False), ('boxNumber', ('union', ('int', 'null')), False), ('startedAt', 'str', False), ('endedAt', ('union', ('str', 'null')), False), ('sketchPath', 'str', False), ('profileHash', ('union', ('str', 'null')), False), ('paramsHash', ('union', ('str', 'null')), False), ('profileSource', ('ref', 'ProfileSource'), False), ('stale', 'bool', False), ('status', ('ref', 'RunStatus'), False), ('metrics', ('list', ('ref', 'MetricSummary')), False), ('overall', ('union', (('ref', 'MetricSummary'), 'null')), False), ('outcomes', ('union', (('ref', 'TrialOutcomes'), 'null')), False), ('conditions', ('list', ('ref', 'ConditionOutcomes')), False), ('engagement', ('union', (('ref', 'TrialEngagement'), 'null')), False), ('totalEvents', 'int', False), ('durationMs', ('union', ('float', 'null')), False), ('stopReason', ('union', ('str', 'null')), False), ('clean', 'bool', False), ('seed', ('union', ('int', 'null')), False), ('detail', ('union', ('str', 'null')), False), ('excludedByDefault', 'bool', False))),
    "AnalyticsAnimal": ('obj', (('id', 'str', False), ('name', 'str', False), ('groupId', 'str', False), ('boxNumber', ('union', ('int', 'null')), False), ('cage', ('union', ('int', 'null')), False))),
    "ProfileMetricInfo": ('obj', (('id', 'str', False), ('label', 'str', False), ('windowSize', 'int', False))),
    "ProfileGroup": ('obj', (('hash', 'str', False), ('taskName', ('union', ('str', 'null')), False), ('kind', ('union', ('str', 'null')), False), ('metrics', ('list', ('ref', 'ProfileMetricInfo')), False), ('runCount', 'int', False))),
    "AnalyticsWarning": ('obj', (('code', 'str', False), ('runId', 'str', False), ('message', 'str', False))),
    "AnalyticsCounts": ('obj', (('runs', 'int', False), ('decoded', 'int', False), ('noProfile', 'int', False), ('missing', 'int', False), ('unreadable', 'int', False))),
    "AnalyticsSummary": ('obj', (('cohortId', 'str', False), ('sessions', ('list', ('ref', 'SessionListItem')), False), ('animals', ('list', ('ref', 'AnalyticsAnimal')), False), ('groups', ('list', ('ref', 'Group')), False), ('runs', ('list', ('ref', 'RunSummary')), False), ('profileGroups', ('list', ('ref', 'ProfileGroup')), False), ('counts', ('ref', 'AnalyticsCounts'), False), ('warnings', ('list', ('ref', 'AnalyticsWarning')), False), ('minCountedTrials', 'int', False))),
    "MetricSeries": ('obj', (('id', 'str', False), ('label', 'str', False), ('values', ('list', 'float'), False), ('n', ('list', 'int'), False), ('windowSize', 'int', False))),
    "StrategyPoint": ('obj', (('trial', 'int', False), ('x', 'float', False), ('y', 'float', False), ('n', 'int', False))),
    "RunSeries": ('obj', (('runId', 'str', False), ('mode', ('lit', ('rolling', 'cumulative')), False), ('metrics', ('list', ('ref', 'MetricSeries')), False), ('trail', ('list', ('ref', 'StrategyPoint')), False))),
    "SeriesResult": ('obj', (('series', ('list', ('ref', 'RunSeries')), False), ('warnings', ('list', ('ref', 'AnalyticsWarning')), False))),
    "RescanOrphan": ('obj', (('path', 'str', False), ('animalId', ('union', ('str', 'null')), False), ('animalName', ('union', ('str', 'null')), False), ('animalSource', ('union', (('lit', ('document', 'filename')), 'null')), False), ('date', ('union', ('str', 'null')), False), ('status', 'str', False), ('reason', ('union', ('str', 'null')), False))),
    "RescanResult": ('obj', (('scanned', 'int', False), ('adopted', 'int', False), ('duplicates', 'int', False), ('orphans', ('list', ('ref', 'RescanOrphan')), False), ('cohortId', 'str', False), ('dataFolder', 'str', False), ('folderMissing', 'bool', False))),
    "AnalyticsProgress": ('obj', (('cohortId', 'str', False), ('phase', ('lit', ('reading', 'walking')), False), ('done', 'int', False), ('total', 'int', False))),
    "RecoveredTsv": ('obj', (('tsvPath', 'str', False), ('jsonPath', ('union', ('str', 'null')), False), ('status', ('lit', ('recovered', 'failed')), False), ('nEvents', 'int', False), ('stopReason', ('union', ('str', 'null')), False), ('reason', ('union', ('str', 'null')), False))),
    "RecoverResult": ('obj', (('scanned', 'int', False), ('recovered', 'int', False), ('failed', 'int', False), ('entries', ('list', ('ref', 'RecoveredTsv')), False), ('cohortId', 'str', False), ('dataFolder', 'str', False), ('folderMissing', 'bool', False))),
    "ServerHello": ('obj', (('protocolVersion', 'int', False), ('sidecarVersion', 'str', False))),
    "PortStateData": ('obj', (('box', 'int', False), ('state', ('ref', 'PortStateName'), False), ('prev', ('ref', 'PortStateName'), False), ('reason', 'str', False))),
    "PortOutputData": ('obj', (('box', 'int', False), ('lines', ('list', ('ref', 'OutputLine')), False))),
    "BoardsPresenceData": ('obj', (('boards', ('list', ('ref', 'DetectedBoard')), False),)),
    "FlashProgressData": ('obj', (('box', 'int', False), ('phase', ('lit', ('compile', 'upload')), False), ('stream', ('lit', ('stdout', 'stderr')), False), ('text', 'str', False))),
    "CohortsUpdatedData": ('obj', (('cohorts', ('list', ('ref', 'CohortSummary')), False),)),
    "PrefixesUpdatedData": ('obj', (('prefixes', ('list', ('ref', 'Prefix')), False),)),
    "SidecarErrorData": ('obj', (('code', 'str', False), ('message', 'str', False), ('detail', 'any', False))),
    "ParadigmQuestion": ('obj', (('id', 'str', False), ('label', 'str', False), ('path', 'str', False), ('help', ('union', ('str', 'null')), False), ('source', ('lit', ('value', 'channel', 'stimulus', 'trial_type', 'strobe')), False), ('kind', ('union', ('str', 'null')), False), ('required', 'bool', False))),
    "ParadigmSummary": ('obj', (('id', 'str', False), ('name', 'str', False), ('affords', 'str', False), ('order', 'int', False), ('template', 'str', False), ('templateVersion', 'int', False), ('fixes', 'any', False), ('questions', ('list', ('ref', 'ParadigmQuestion')), False))),
    "SpecOrigin": ('lit', ('user',)),
    "SpecEntry": ('obj', (('specId', 'str', False), ('label', ('union', ('str', 'null')), False), ('description', ('union', ('str', 'null')), False), ('origin', ('ref', 'SpecOrigin'), False), ('template', ('union', ('str', 'null')), False), ('templateVersion', ('union', ('int', 'null')), False), ('paradigmId', ('union', ('str', 'null')), False), ('editedAt', ('union', ('str', 'null')), False))),
    "SpecOverlayField": ('obj', (('label', 'str', False), ('widget', 'str', False), ('group', 'str', True), ('order', 'int', True), ('unit', 'str', True), ('step', ('union', ('int', 'float')), True), ('help', 'str', True), ('advanced', 'bool', True), ('readOnly', 'bool', True), ('nullable', 'bool', True), ('multiple', 'bool', True), ('channelKind', 'str', True), ('options', ('list', ('obj', (('value', 'str', False), ('label', 'str', False), ('help', 'str', True)))), True))),
    "SpecOverlayGroup": ('obj', (('id', 'str', False), ('label', 'str', False), ('order', 'int', False), ('help', 'str', True))),
    "SpecOverlay": ('obj', (('presentation_version', 'int', False), ('groups', ('list', ('ref', 'SpecOverlayGroup')), False), ('sections', ('map', ('obj', (('group', 'str', False), ('rows', ('lit', ('indexed', 'by_id', 'by_key', 'object')), False), ('gatedBy', 'str', True)))), False), ('fields', ('map', ('ref', 'SpecOverlayField')), False))),
    "SpecDiagnostic": ('obj', (('code', 'str', False), ('severity', ('lit', ('INFO', 'WARN', 'ERROR')), False), ('message', 'str', False), ('location', ('union', ('str', 'null')), False), ('placement', ('lit', ('field', 'row', 'section', 'node', 'document')), False), ('anchor', ('union', ('str', 'null')), False), ('detail', ('union', ('str', 'null')), False), ('help', ('union', ('str', 'null')), False), ('decision', ('union', ('str', 'null')), False))),
    "SpecGraphNode": ('obj', (('index', 'int', False), ('symbol', 'str', False), ('label', 'str', False), ('band', 'int', False), ('type', ('lit', ('DELAY', 'WAIT_ENTRY', 'HOLD', 'WAIT_EXIT', 'PULSE', 'TERMINAL')), False), ('durationId', ('union', ('str', 'null')), False), ('durationMs', ('union', ('int', 'null')), False), ('strobeName', ('union', ('str', 'null')), False), ('strobe', ('union', ('int', 'null')), False), ('silentByDesign', 'bool', False), ('watch', ('list', 'str'), False))),
    "SpecGraphEdge": ('obj', (('index', 'int', False), ('src', 'int', False), ('dst', 'int', False), ('trigger', ('lit', ('TIMEOUT', 'ENTER', 'HELD', 'BROKEN', 'EXIT', 'DONE', 'ADVANCE', 'REPEAT')), False), ('guard', ('union', ('str', 'null')), False), ('channel', ('union', ('str', 'null')), False), ('effect', ('union', ('str', 'null')), False))),
    "SpecGraph": ('obj', (('nodes', ('list', ('ref', 'SpecGraphNode')), False), ('edges', ('list', ('ref', 'SpecGraphEdge')), False), ('entry', 'int', False))),
    "SpecTableSummary": ('obj', (('specId', 'str', False), ('specHash', 'str', False), ('specVersion', 'int', False), ('vocabVersion', 'int', False), ('template', 'str', False), ('templateVersion', 'int', False), ('templateHash', 'str', False), ('nNodes', 'int', False), ('nEdges', 'int', False), ('nTiming', 'int', False), ('nTrialTypes', 'int', False), ('sizeBytes', 'int', False), ('crc32', 'str', False))),
    "SpecCompileResult": ('obj', (('ok', 'bool', False), ('diagnostics', ('list', ('ref', 'SpecDiagnostic')), False), ('table', ('union', (('ref', 'SpecTableSummary'), 'null')), False), ('graph', ('union', (('ref', 'SpecGraph'), 'null')), False), ('listing', ('union', ('str', 'null')), False), ('elapsedMs', 'float', False))),
    "SpecCapabilities": ('obj', (('outcomeClasses', ('list', 'str'), False), ('requiredTiming', ('list', 'str'), False), ('knobs', ('list', 'str'), False), ('template', 'str', False), ('templateVersion', 'int', False))),
    "SpecsUpdatedData": ('obj', (('specs', ('list', ('ref', 'SpecEntry')), False),)),
    "DiffLine": ('obj', (('op', ('lit', (' ', '+', '-')), False), ('text', 'str', False))),
    "DiffHunk": ('obj', (('section', 'str', False), ('lines', ('list', ('ref', 'DiffLine')), False))),
    "SpecListingDiff": ('obj', (('specId', 'str', False), ('baseline', ('lit', ('saved', 'spec')), False), ('changed', 'bool', False), ('before', ('union', (('ref', 'SpecTableSummary'), 'null')), False), ('after', ('union', (('ref', 'SpecTableSummary'), 'null')), False), ('hunks', ('list', ('ref', 'DiffHunk')), False), ('added', 'int', False), ('removed', 'int', False))),
    "SpecArtifact": ('obj', (('kind', ('lit', ('spec', 'listing', 'lint', 'table_json', 'table_bin', 'bench')), False), ('filename', 'str', False), ('text', ('union', ('str', 'null')), False), ('base64', ('union', ('str', 'null')), False))),
    "BoardCapabilities": ('obj', (('box', 'int', False), ('present', 'bool', False), ('baud', 'int', False), ('values', ('map', 'int'), False), ('text', ('map', 'str'), False), ('banner', ('list', 'str'), False))),
    "UploadProgressData": ('obj', (('box', 'int', False), ('phase', ('lit', ('detect', 'probe', 'transfer', 'verify')), False), ('chunk', ('union', ('int', 'null')), False), ('chunks', ('union', ('int', 'null')), False), ('text', ('union', ('str', 'null')), False))),
    "UploadResult": ('obj', (('box', 'int', False), ('specId', 'str', False), ('specHash', 'str', False), ('nBytes', 'int', False), ('chunks', 'int', False), ('crc32', 'str', False), ('digest', 'str', False), ('seconds', 'float', False), ('notes', ('list', 'str'), False), ('caps', ('ref', 'BoardCapabilities'), False))),
}

COMMAND_ARGS: Final[dict[str, Any]] = {
    "auth": ('obj', (('token', 'str', False),)),
    "ping": ('obj', ()),
    "settings.push": ('obj', (('settings', ('ref', 'EphymerisSettings'), False),)),
    "sketches.refresh": ('obj', ()),
    "port.passthrough.open": ('obj', (('box', 'int', False), ('baud', 'int', True))),
    "port.passthrough.close": ('obj', (('box', 'int', False),)),
    "port.send": ('obj', (('box', 'int', False), ('text', 'str', False), ('lineEnding', ('lit', ('none', 'lf', 'cr', 'crlf')), True))),
    "port.flash": ('obj', (('box', 'int', False), ('sketchPath', 'str', False), ('suppressPassthroughResume', 'bool', True))),
    "port.reset": ('obj', (('box', 'int', False),)),
    "port.error.ack": ('obj', (('box', 'int', False),)),
    "utility.status": ('obj', ()),
    "utility.ensure": ('obj', (('boxes', ('list', 'int'), True), ('force', 'bool', True))),
    "utility.identify": ('obj', (('box', 'int', False), ('on', 'bool', False))),
    "cohorts.list": ('obj', ()),
    "cohorts.get": ('obj', (('id', 'str', False),)),
    "cohorts.create": ('obj', (('name', 'str', False), ('dataFolder', 'str', True), ('animals', ('list', ('ref', 'Animal')), True), ('groups', ('list', ('ref', 'Group')), True))),
    "cohorts.update": ('obj', (('id', 'str', False), ('patch', ('ref', 'CohortPatch'), False))),
    "cohorts.archive": ('obj', (('id', 'str', False),)),
    "cohorts.restore": ('obj', (('id', 'str', False),)),
    "cohorts.delete": ('obj', (('id', 'str', False), ('confirm', 'bool', False))),
    "cohorts.setDataFolder": ('obj', (('id', 'str', False), ('path', 'str', False), ('moveExisting', 'bool', False))),
    "cohorts.suggestGroups": ('obj', (('id', 'str', False), ('groupCount', 'int', True), ('maxGroupSize', 'int', True), ('balanceBySex', 'bool', True))),
    "prefixes.list": ('obj', ()),
    "prefixes.create": ('obj', (('name', 'str', False),)),
    "prefixes.delete": ('obj', (('id', 'str', False),)),
    "tasks.getProfile": ('obj', (('sketchPath', 'str', False),)),
    "sessions.suggestNumber": ('obj', (('prefixId', 'str', False),)),
    "sessions.create": ('obj', (('cohortId', 'str', False), ('prefixId', 'str', False), ('sessionNumber', 'str', False), ('durationMinutes', 'int', True))),
    "sessions.abandon": ('obj', (('sessionId', 'str', False),)),
    "sessions.confirmMapping": ('obj', (('sessionId', 'str', False), ('groupId', 'str', False), ('boxes', ('list', ('ref', 'SessionBoxMapping')), False))),
    "sessions.status": ('obj', (('sessionId', 'str', False),)),
    "sessions.startAll": ('obj', (('sessionId', 'str', False),)),
    "sessions.switchGroup": ('obj', (('sessionId', 'str', False),)),
    "sessions.end": ('obj', (('sessionId', 'str', False),)),
    "sessions.active": ('obj', ()),
    "port.startSession": ('obj', (('box', 'int', False),)),
    "port.stopSession": ('obj', (('box', 'int', False),)),
    "backup.syncNow": ('obj', ()),
    "sessions.list": ('obj', (('cohortId', 'str', False), ('includeAborted', 'bool', True))),
    "analytics.summary": ('obj', (('cohortId', 'str', False), ('sessionIds', ('list', 'str'), True), ('animalIds', ('list', 'str'), True), ('minCountedTrials', 'int', True))),
    "analytics.series": ('obj', (('runIds', ('list', 'str'), False), ('mode', ('lit', ('rolling', 'cumulative')), True), ('metricIds', ('list', 'str'), True))),
    "analytics.rescan": ('obj', (('cohortId', 'str', False), ('adoptOrphans', 'bool', True))),
    "analytics.recentSessions": ('obj', (('limit', 'int', True),)),
    "sessions.recover": ('obj', (('cohortId', 'str', False),)),
    "specs.list": ('obj', ()),
    "specs.get": ('obj', (('specId', 'str', False),)),
    "specs.schema": ('obj', ()),
    "specs.compile": ('obj', (('text', 'str', False), ('specId', 'str', True))),
    "specs.capabilities": ('obj', (('topology', 'any', False),)),
    "specs.paradigms": ('obj', ()),
    "specs.skeleton": ('obj', (('paradigmId', 'str', False), ('specId', 'str', False), ('answers', 'any', False), ('label', ('union', ('str', 'null')), True), ('description', ('union', ('str', 'null')), True))),
    "specs.save": ('obj', (('specId', 'str', False), ('text', 'str', False))),
    "specs.delete": ('obj', (('specId', 'str', False),)),
    "specs.diff": ('obj', (('specId', 'str', False), ('text', 'str', True), ('againstSpecId', 'str', True))),
    "specs.export": ('obj', (('specId', 'str', False), ('text', 'str', True), ('artifacts', ('list', 'str'), False))),
    "board.capabilities": ('obj', (('box', 'int', False), ('baud', 'int', True))),
    "board.uploadTable": ('obj', (('box', 'int', False), ('specId', 'str', False), ('text', 'str', True))),
    "utility.benchHold": ('obj', (('held', 'bool', False),)),
}

COMMAND_RESULTS: Final[dict[str, Any]] = {
    "auth": ('obj', (('authenticated', 'bool', False),)),
    "ping": ('obj', (('pong', 'bool', False), ('sidecarVersion', 'str', False))),
    "settings.push": ('obj', (('library', ('ref', 'SketchLibraryStatus'), False),)),
    "sketches.refresh": ('ref', 'SketchDiscovery'),
    "port.passthrough.open": ('obj', (('state', ('ref', 'PortStateName'), False),)),
    "port.passthrough.close": ('obj', (('state', ('ref', 'PortStateName'), False),)),
    "port.send": ('obj', (('bytesWritten', 'int', False),)),
    "port.flash": ('obj', (('state', ('ref', 'PortStateName'), False), ('resumedPassthrough', 'bool', False))),
    "port.reset": ('obj', (('state', ('ref', 'PortStateName'), False), ('resumedPassthrough', 'bool', False))),
    "port.error.ack": ('obj', (('state', ('ref', 'PortStateName'), False),)),
    "utility.status": ('ref', 'UtilityStatus'),
    "utility.ensure": ('ref', 'UtilityStatus'),
    "utility.identify": ('obj', (('delivered', 'bool', False), ('state', ('ref', 'UtilityBoxState'), False))),
    "cohorts.list": ('obj', (('cohorts', ('list', ('ref', 'CohortSummary')), False),)),
    "cohorts.get": ('obj', (('cohort', ('ref', 'Cohort'), False),)),
    "cohorts.create": ('obj', (('cohort', ('ref', 'Cohort'), False),)),
    "cohorts.update": ('obj', (('cohort', ('ref', 'Cohort'), False),)),
    "cohorts.archive": ('obj', (('cohort', ('ref', 'Cohort'), False),)),
    "cohorts.restore": ('obj', (('cohort', ('ref', 'Cohort'), False),)),
    "cohorts.delete": ('obj', (('deleted', 'bool', False),)),
    "cohorts.setDataFolder": ('obj', (('cohort', ('ref', 'Cohort'), False),)),
    "cohorts.suggestGroups": ('ref', 'GroupProposal'),
    "prefixes.list": ('obj', (('prefixes', ('list', ('ref', 'Prefix')), False),)),
    "prefixes.create": ('obj', (('prefix', ('ref', 'Prefix'), False),)),
    "prefixes.delete": ('obj', (('deleted', 'bool', False),)),
    "tasks.getProfile": ('union', (('ref', 'TaskProfile'), ('obj', (('profile', 'null', False),)))),
    "sessions.suggestNumber": ('obj', (('suggestion', ('union', ('str', 'null')), False), ('sameDayNumbers', ('list', 'str'), False))),
    "sessions.create": ('obj', (('session', ('ref', 'Session'), False),)),
    "sessions.abandon": ('obj', (('session', ('ref', 'Session'), False),)),
    "sessions.confirmMapping": ('obj', (('ok', 'bool', False),)),
    "sessions.status": ('obj', (('session', ('ref', 'Session'), False), ('groupId', ('union', ('str', 'null')), False), ('boxes', ('list', ('ref', 'SessionBox')), False))),
    "sessions.startAll": ('obj', (('session', ('ref', 'Session'), False),)),
    "sessions.switchGroup": ('obj', (('nextGroupId', ('union', ('str', 'null')), False),)),
    "sessions.end": ('obj', (('session', ('ref', 'Session'), False),)),
    "sessions.active": ('ref', 'ActiveSessions'),
    "port.startSession": ('obj', (('state', ('ref', 'PortStateName'), False),)),
    "port.stopSession": ('obj', (('state', ('ref', 'PortStateName'), False),)),
    "backup.syncNow": ('ref', 'SyncResult'),
    "sessions.list": ('obj', (('sessions', ('list', ('ref', 'SessionListItem')), False),)),
    "analytics.summary": ('ref', 'AnalyticsSummary'),
    "analytics.series": ('ref', 'SeriesResult'),
    "analytics.rescan": ('ref', 'RescanResult'),
    "analytics.recentSessions": ('obj', (('sessions', ('list', ('ref', 'DiskSession')), False),)),
    "sessions.recover": ('ref', 'RecoverResult'),
    "specs.list": ('obj', (('specs', ('list', ('ref', 'SpecEntry')), False),)),
    "specs.get": ('obj', (('specId', 'str', False), ('origin', ('ref', 'SpecOrigin'), False), ('text', 'str', False), ('raw', 'any', False))),
    "specs.schema": ('obj', (('schema', 'any', False), ('overlay', ('ref', 'SpecOverlay'), False), ('strobes', 'any', False), ('channels', 'any', False), ('limits', 'any', False), ('templates', ('list', ('obj', (('name', 'str', False), ('version', 'int', False), ('sourceHash', 'str', False)))), False))),
    "specs.compile": ('ref', 'SpecCompileResult'),
    "specs.capabilities": ('ref', 'SpecCapabilities'),
    "specs.paradigms": ('obj', (('paradigms', ('list', ('ref', 'ParadigmSummary')), False),)),
    "specs.skeleton": ('obj', (('text', 'str', False), ('result', ('ref', 'SpecCompileResult'), False))),
    "specs.save": ('obj', (('entry', ('ref', 'SpecEntry'), False), ('result', ('ref', 'SpecCompileResult'), False))),
    "specs.delete": ('obj', (('entry', ('union', (('ref', 'SpecEntry'), 'null')), False),)),
    "specs.diff": ('ref', 'SpecListingDiff'),
    "specs.export": ('obj', (('artifacts', ('list', ('ref', 'SpecArtifact')), False),)),
    "board.capabilities": ('ref', 'BoardCapabilities'),
    "board.uploadTable": ('ref', 'UploadResult'),
    "utility.benchHold": ('ref', 'UtilityStatus'),
}

EVENT_DATA: Final[dict[str, Any]] = {
    "server.hello": ('ref', 'ServerHello'),
    "port.state": ('ref', 'PortStateData'),
    "port.output": ('ref', 'PortOutputData'),
    "boards.presence": ('ref', 'BoardsPresenceData'),
    "flash.progress": ('ref', 'FlashProgressData'),
    "sketches.updated": ('ref', 'SketchDiscovery'),
    "cohorts.updated": ('ref', 'CohortsUpdatedData'),
    "prefixes.updated": ('ref', 'PrefixesUpdatedData'),
    "session.telemetry": ('ref', 'BoxTelemetry'),
    "session.animalEnded": ('ref', 'AnimalEnded'),
    "session.lifecycle": ('ref', 'ActiveSessions'),
    "utility.updated": ('ref', 'UtilityStatus'),
    "backup.status": ('ref', 'BackupStatus'),
    "analytics.progress": ('ref', 'AnalyticsProgress'),
    "sidecar.error": ('ref', 'SidecarErrorData'),
    "specs.updated": ('ref', 'SpecsUpdatedData'),
    "upload.progress": ('ref', 'UploadProgressData'),
}


# --- Shape validation -------------------------------------------------------

class WireShapeError(AssertionError):
    """A payload does not match the shape `protocol/schema.py` declares."""


def wire_validation_enabled() -> bool:
    """Opt-in via EPHYMERIS_WIRE_VALIDATE=1 — the test suite turns it on.

    Off by default in production: a benign schema lag must never take down a
    live session over a payload the frontend would have rendered fine.
    """
    return os.environ.get("EPHYMERIS_WIRE_VALIDATE") == "1"


def validate(spec: Any, value: Any, path: str = "$") -> list[str]:
    """Structural check of `value` against a spec; returns problems, [] if ok.

    Deliberately strict in both directions: a *missing* required field and an
    *unknown* field are both errors, because either one is exactly the
    one-sided drift this exists to catch (TODO item 8).
    """
    errors: list[str] = []
    _check(spec, value, path, errors)
    return errors


def validate_command_args(cmd: str, args: Any) -> list[str]:
    spec = COMMAND_ARGS.get(cmd)
    if spec is None:
        return [f"unknown command: {cmd}"]
    return validate(spec, args if args is not None else {}, f"{cmd}.args")


def validate_command_result(cmd: str, result: Any) -> list[str]:
    spec = COMMAND_RESULTS.get(cmd)
    if spec is None:
        return [f"unknown command: {cmd}"]
    return validate(spec, result, f"{cmd}.result")


def validate_event_data(name: str, data: Any) -> list[str]:
    spec = EVENT_DATA.get(name)
    if spec is None:
        return [f"unknown event: {name}"]
    return validate(spec, data, f"{name}.data")


def _describe(value: Any) -> str:
    return "null" if value is None else type(value).__name__


def _check(spec: Any, value: Any, path: str, errors: list[str]) -> None:
    if isinstance(spec, str):
        if spec == "any":
            return
        ok = {
            "null": value is None,
            "str": isinstance(value, str),
            "bool": isinstance(value, bool),
            # bool is an int subclass, and a True on the wire where a count
            # belongs is exactly the sort of bug worth failing on.
            "int": isinstance(value, int) and not isinstance(value, bool),
            "float": isinstance(value, (int, float)) and not isinstance(value, bool),
        }[spec]
        if not ok:
            errors.append(f"{path}: expected {spec}, got {_describe(value)}")
        return

    tag = spec[0]
    if tag == "lit":
        if value not in spec[1]:
            errors.append(f"{path}: {value!r} not one of {list(spec[1])}")
    elif tag == "list":
        if not isinstance(value, list):
            errors.append(f"{path}: expected list, got {_describe(value)}")
            return
        for index, item in enumerate(value):
            _check(spec[1], item, f"{path}[{index}]", errors)
    elif tag == "map":
        if not isinstance(value, dict):
            errors.append(f"{path}: expected object, got {_describe(value)}")
            return
        for key, item in value.items():
            if not isinstance(key, str):
                errors.append(f"{path}: non-string key {key!r}")
                continue
            _check(spec[1], item, f"{path}.{key}", errors)
    elif tag == "union":
        # Valid if any arm accepts; report the closest-fitting arm's problems.
        best: list[str] | None = None
        for option in spec[1]:
            attempt: list[str] = []
            _check(option, value, path, attempt)
            if not attempt:
                return
            if best is None or len(attempt) < len(best):
                best = attempt
        errors.extend(best or [f"{path}: matches no union arm"])
    elif tag == "ref":
        _check(SHAPES[spec[1]], value, path, errors)
    elif tag == "obj":
        if not isinstance(value, dict):
            errors.append(f"{path}: expected object, got {_describe(value)}")
            return
        fields = {name: (field_spec, optional) for name, field_spec, optional in spec[1]}
        for name, (field_spec, optional) in fields.items():
            if name not in value:
                if not optional:
                    errors.append(f"{path}: missing required field `{name}`")
                continue
            _check(field_spec, value[name], f"{path}.{name}", errors)
        for name in value:
            if name not in fields:
                errors.append(f"{path}: unknown field `{name}`")
    else:  # pragma: no cover - unreachable with generated specs
        errors.append(f"{path}: malformed spec {spec!r}")


# --- Envelope builders ----------------------------------------------------

def reply_ok(corr: str, result: Any = None) -> dict[str, Any]:
    return {"v": PROTOCOL_VERSION, "corr": corr, "ok": True, "result": result}


def reply_err(
    corr: str, code: str, message: str, detail: Any = None
) -> dict[str, Any]:
    return {
        "v": PROTOCOL_VERSION,
        "corr": corr,
        "ok": False,
        "error": {"code": code, "message": message, "detail": detail},
    }


def event(name: str, data: Any = None, corr: str | None = None) -> dict[str, Any]:
    if wire_validation_enabled():
        problems = validate_event_data(name, data)
        if problems:
            raise WireShapeError(
                f"event `{name}` payload violates protocol/schema.py:\n  "
                + "\n  ".join(problems)
            )
    msg: dict[str, Any] = {
        "v": PROTOCOL_VERSION,
        "evt": name,
        "ts": time.time(),
        "data": data,
    }
    if corr is not None:
        msg["corr"] = corr
    return msg
