"""Canonical wire protocol between the frontend and this sidecar.

GENERATED by protocol/generate.py from protocol/schema.py — DO NOT EDIT.
Regenerate with `npm run gen:protocol` (or `python protocol/generate.py`).

`docs/ARCHITECTURE.md` carries the prose (rationale, lifecycle,
invariants); `protocol/schema.py` is the shape authority this module,
`src/lib/ws/protocol.ts` and `docs/PROTOCOL.md` are generated from.

Envelope shapes:

    client -> server   {"v", "id", "cmd", "args"}
    server -> client   {"v", "corr", "ok": true,  "result"}      (reply)
                       {"v", "corr", "ok": false, "error"}       (reply)
                       {"v", "evt", "ts", "data", "corr"?}       (event)
"""

from __future__ import annotations

import os
import time
from typing import Any, Final

PROTOCOL_VERSION: Final = 1


# --- Commands (client -> server) ------------------------------------------

class Cmd:
    # Connection and settings
    AUTH: Final = "auth"
    SETTINGS_PUSH: Final = "settings.push"
    SKETCHES_REFRESH: Final = "sketches.refresh"

    # Ports
    PORT_PASSTHROUGH_OPEN: Final = "port.passthrough.open"
    PORT_PASSTHROUGH_CLOSE: Final = "port.passthrough.close"
    PORT_SEND: Final = "port.send"
    PORT_SEND_START: Final = "port.sendStart"
    PORT_FLASH: Final = "port.flash"
    PORT_RESET: Final = "port.reset"
    PORT_ERROR_ACK: Final = "port.error.ack"
    PORT_START_SESSION: Final = "port.startSession"
    PORT_STOP_SESSION: Final = "port.stopSession"

    # Utility baseline
    UTILITY_ENSURE: Final = "utility.ensure"
    UTILITY_IDENTIFY: Final = "utility.identify"

    # Rig wiring
    HARDWARE_GET: Final = "hardware.get"
    HARDWARE_PREVIEW: Final = "hardware.preview"
    HARDWARE_SAVE: Final = "hardware.save"
    HARDWARE_RESET: Final = "hardware.reset"

    # Strobe vocabulary
    STROBES_GET: Final = "strobes.get"
    STROBES_USAGE: Final = "strobes.usage"
    STROBES_ADD: Final = "strobes.add"
    STROBES_EDIT: Final = "strobes.edit"
    STROBES_RETIRE: Final = "strobes.retire"
    STROBES_REINSTATE: Final = "strobes.reinstate"
    STROBES_REMOVE: Final = "strobes.remove"
    STROBES_EXPORT: Final = "strobes.export"
    STROBES_IMPORT: Final = "strobes.import"

    # Cohorts
    COHORTS_LIST: Final = "cohorts.list"
    COHORTS_GET: Final = "cohorts.get"
    COHORTS_CREATE: Final = "cohorts.create"
    COHORTS_UPDATE: Final = "cohorts.update"
    COHORTS_ARCHIVE: Final = "cohorts.archive"
    COHORTS_RESTORE: Final = "cohorts.restore"
    COHORTS_DELETE: Final = "cohorts.delete"
    COHORTS_SET_DATA_FOLDER: Final = "cohorts.setDataFolder"
    COHORTS_SUGGEST_GROUPS: Final = "cohorts.suggestGroups"

    # Prefixes and sessions
    PREFIXES_LIST: Final = "prefixes.list"
    PREFIXES_CREATE: Final = "prefixes.create"
    PREFIXES_DELETE: Final = "prefixes.delete"
    SESSIONS_SUGGEST_NUMBER: Final = "sessions.suggestNumber"
    SESSIONS_CREATE: Final = "sessions.create"
    SESSIONS_ABANDON: Final = "sessions.abandon"
    SESSIONS_CONFIRM_MAPPING: Final = "sessions.confirmMapping"
    SESSIONS_STATUS: Final = "sessions.status"
    SESSIONS_START_ALL: Final = "sessions.startAll"
    SESSIONS_END_GROUP: Final = "sessions.endGroup"
    SESSIONS_RESUME: Final = "sessions.resume"
    SESSIONS_END: Final = "sessions.end"
    SESSIONS_ACTIVE: Final = "sessions.active"

    # Task profiles
    TASKS_GET_PROFILE: Final = "tasks.getProfile"
    TASKS_LIST: Final = "tasks.list"
    TASKS_GET: Final = "tasks.get"
    TASKS_PREVIEW: Final = "tasks.preview"
    TASKS_SAVE: Final = "tasks.save"
    TASKS_DELETE: Final = "tasks.delete"

    # Backup
    BACKUP_SYNC_NOW: Final = "backup.syncNow"

    # Analytics
    SESSIONS_LIST: Final = "sessions.list"
    ANALYTICS_SUMMARY: Final = "analytics.summary"
    ANALYTICS_SET_FALSE_START: Final = "analytics.setFalseStart"
    ANALYTICS_SERIES: Final = "analytics.series"
    ANALYTICS_RESCAN: Final = "analytics.rescan"
    ANALYTICS_RECENT_SESSIONS: Final = "analytics.recentSessions"
    SESSIONS_RECOVER: Final = "sessions.recover"
    SESSIONS_TIDY: Final = "sessions.tidy"

    # Intan recording
    INTAN_STATUS: Final = "intan.status"
    INTAN_CONNECT: Final = "intan.connect"
    INTAN_DISCONNECT: Final = "intan.disconnect"
    INTAN_CONFIGURE: Final = "intan.configure"
    INTAN_PARSE_PROBE_MAP: Final = "intan.parseProbeMap"
    INTAN_PROBE_MAP: Final = "intan.probeMap"
    INTAN_SET_THRESHOLD: Final = "intan.setThreshold"
    INTAN_SCOPE_OPEN: Final = "intan.scope.open"
    INTAN_SCOPE_UPDATE: Final = "intan.scope.update"
    INTAN_SCOPE_CLOSE: Final = "intan.scope.close"
    INTAN_FORCE_STOP: Final = "intan.forceStop"

    # Session log
    LOGBOOK_COHORT: Final = "logbook.cohort"
    LOGBOOK_ADD_NOTE: Final = "logbook.addNote"
    LOGBOOK_EDIT_NOTE: Final = "logbook.editNote"
    LOGBOOK_DELETE_NOTE: Final = "logbook.deleteNote"
    LOGBOOK_RESOLVE_FLAG: Final = "logbook.resolveFlag"
    LOGBOOK_SET_SESSION_LOG: Final = "logbook.setSessionLog"
    LOGBOOK_OPEN_FLAGS: Final = "logbook.openFlags"


ALL_COMMANDS: Final[frozenset[str]] = frozenset(
    v for k, v in vars(Cmd).items() if not k.startswith("_") and isinstance(v, str)
)


# --- Events (server -> client) --------------------------------------------

class Evt:
    SERVER_HELLO: Final = "server.hello"
    PORT_STATE: Final = "port.state"
    PORT_OUTPUT: Final = "port.output"
    PORT_TELEMETRY: Final = "port.telemetry"
    BOARDS_PRESENCE: Final = "boards.presence"
    FLASH_PROGRESS: Final = "flash.progress"
    SKETCHES_UPDATED: Final = "sketches.updated"
    COHORTS_UPDATED: Final = "cohorts.updated"
    PREFIXES_UPDATED: Final = "prefixes.updated"
    SESSION_TELEMETRY: Final = "session.telemetry"
    SESSION_ANIMAL_ENDED: Final = "session.animalEnded"
    LOGBOOK_UPDATED: Final = "logbook.updated"
    SESSION_LIFECYCLE: Final = "session.lifecycle"
    HARDWARE_UPDATED: Final = "hardware.updated"
    STROBES_UPDATED: Final = "strobes.updated"
    STROBES_SCAN_PROGRESS: Final = "strobes.scanProgress"
    UTILITY_UPDATED: Final = "utility.updated"
    BACKUP_STATUS: Final = "backup.status"
    ANALYTICS_PROGRESS: Final = "analytics.progress"
    SIDECAR_ERROR: Final = "sidecar.error"
    TASKS_UPDATED: Final = "tasks.updated"
    INTAN_STATUS: Final = "intan.status"
    INTAN_SCOPE_DATA: Final = "intan.scope.data"


ALL_EVENTS: Final[frozenset[str]] = frozenset(
    v for k, v in vars(Evt).items() if not k.startswith("_") and isinstance(v, str)
)


# --- Error codes ----------------------------------------------------------

class ErrCode:
    BAD_MESSAGE: Final = "BAD_MESSAGE"
    UNKNOWN_COMMAND: Final = "UNKNOWN_COMMAND"
    UNAUTHORIZED: Final = "UNAUTHORIZED"
    PROTOCOL_VERSION_MISMATCH: Final = "PROTOCOL_VERSION_MISMATCH"
    ILLEGAL_TRANSITION: Final = "ILLEGAL_TRANSITION"
    SEND_NOT_PASSTHROUGH: Final = "SEND_NOT_PASSTHROUGH"
    PORT_NOT_BOUND: Final = "PORT_NOT_BOUND"
    PORT_OPEN_FAILED: Final = "PORT_OPEN_FAILED"
    FLASH_FAILED: Final = "FLASH_FAILED"
    SKETCH_UNKNOWN: Final = "SKETCH_UNKNOWN"
    COHORT_NOT_FOUND: Final = "COHORT_NOT_FOUND"
    COHORT_NAME_TAKEN: Final = "COHORT_NAME_TAKEN"
    COHORT_INVALID: Final = "COHORT_INVALID"
    COHORT_NOT_ARCHIVED: Final = "COHORT_NOT_ARCHIVED"
    DATA_FOLDER_INVALID: Final = "DATA_FOLDER_INVALID"
    PREFIX_NAME_TAKEN: Final = "PREFIX_NAME_TAKEN"
    SESSION_INVALID: Final = "SESSION_INVALID"
    SESSION_NOT_READY: Final = "SESSION_NOT_READY"
    TASK_PROFILE_INVALID: Final = "TASK_PROFILE_INVALID"
    BACKUP_UNAVAILABLE: Final = "BACKUP_UNAVAILABLE"
    UTILITY_UNAVAILABLE: Final = "UTILITY_UNAVAILABLE"
    RIG_INVALID: Final = "RIG_INVALID"
    RIG_WOULD_BREAK_TASKS: Final = "RIG_WOULD_BREAK_TASKS"
    STROBE_INVALID: Final = "STROBE_INVALID"
    STROBE_REQUIRED: Final = "STROBE_REQUIRED"
    STROBE_IN_RECORDED_SESSION: Final = "STROBE_IN_RECORDED_SESSION"
    STROBE_WOULD_BREAK_TASKS: Final = "STROBE_WOULD_BREAK_TASKS"
    STROBE_IMPORT_CONFLICT: Final = "STROBE_IMPORT_CONFLICT"
    STROBE_VOCABULARY_UNREADABLE: Final = "STROBE_VOCABULARY_UNREADABLE"
    STROBE_SESSION_RUNNING: Final = "STROBE_SESSION_RUNNING"
    TASK_NOT_FOUND: Final = "TASK_NOT_FOUND"
    TASK_INVALID: Final = "TASK_INVALID"
    INTAN_UNAVAILABLE: Final = "INTAN_UNAVAILABLE"
    INTAN_NOT_READY: Final = "INTAN_NOT_READY"
    INTAN_COMMAND_FAILED: Final = "INTAN_COMMAND_FAILED"
    INTERNAL: Final = "INTERNAL"


ALL_ERROR_CODES: Final[frozenset[str]] = frozenset(
    v for k, v in vars(ErrCode).items() if not k.startswith("_") and isinstance(v, str)
)


# --- Payload shape specs --------------------------------------------------
#
# Runtime data for `validate()`. Encoding: a primitive is its name; every
# composite is a ("tag", ...) tuple — ("lit", values), ("list", item),
# ("map", value), ("union", options), ("ref", shape_name), and
# ("obj", ((field, spec, optional), ...)).

SHAPES: Final[dict[str, Any]] = {
    "PortStateName": ('lit', ('IDLE', 'PASSTHROUGH', 'FLASHING', 'RESETTING', 'IN_SESSION', 'ERROR')),
    "OutputLine": ('obj', (('dir', ('lit', ('rx', 'tx')), False), ('text', 'str', False), ('ts', 'float', False))),
    "DetectedBoard": ('obj', (('hardwareId', 'str', False), ('address', 'str', False), ('fqbn', ('union', ('str', 'null')), False), ('boxId', ('union', ('int', 'null')), False))),
    "LibraryState": ('lit', ('ok', 'empty', 'damaged')),
    "SketchLibraryStatus": ('obj', (('state', ('ref', 'LibraryState'), False), ('path', ('union', ('str', 'null')), False), ('message', ('union', ('str', 'null')), False), ('source', ('lit', ('bundled', 'override')), False))),
    "SketchEntry": ('obj', (('category', 'str', False), ('name', 'str', False), ('path', 'str', False))),
    "SkippedEntry": ('obj', (('path', 'str', False), ('reason', 'str', False))),
    "SketchDiscovery": ('obj', (('library', ('ref', 'SketchLibraryStatus'), False), ('sketches', ('list', ('ref', 'SketchEntry')), False), ('skipped', ('list', ('ref', 'SkippedEntry')), False), ('skippedCount', 'int', False), ('libraries', ('list', 'str'), False), ('librariesPath', ('union', ('str', 'null')), False))),
    "BoxBinding": ('obj', (('box', 'int', False), ('hardwareId', ('union', ('str', 'null')), False), ('label', 'str', False), ('intanDigitalIn', ('union', ('int', 'null')), True))),
    "IntanSettings": ('obj', (('commandPort', 'int', False), ('waveformPort', 'int', False), ('spikePort', 'int', False))),
    "EphymerisSettings": ('obj', (('dataDirectory', ('union', ('str', 'null')), False), ('backupDirectory', ('union', ('str', 'null')), False), ('arduinoCliPath', ('union', ('str', 'null')), False), ('defaultBaud', 'int', False), ('boxes', ('list', ('ref', 'BoxBinding')), False), ('intan', ('ref', 'IntanSettings'), True), ('recordingDefaults', ('map', 'any'), True), ('reducedMotion', 'bool', False), ('constellation', ('union', ('str', 'null')), False), ('constellationSlots', ('map', 'int'), False), ('taskDefaults', ('map', ('map', 'any')), False))),
    "UtilityBaselineState": ('lit', ('unknown', 'restoring', 'ready', 'busy', 'held', 'pinned', 'unavailable', 'failed')),
    "UtilityBoxState": ('obj', (('box', 'int', False), ('state', ('ref', 'UtilityBaselineState'), False), ('detail', ('union', ('str', 'null')), False), ('identifying', 'bool', False))),
    "UtilityStatus": ('obj', (('configured', 'bool', False), ('sketchPath', ('union', ('str', 'null')), False), ('sketchName', ('union', ('str', 'null')), False), ('canIdentify', 'bool', False), ('held', 'bool', False), ('message', ('union', ('str', 'null')), False), ('boxes', ('list', ('ref', 'UtilityBoxState')), False))),
    "BackupState": ('lit', ('disabled', 'pending', 'ok', 'failed')),
    "BackupStatus": ('obj', (('configured', 'bool', False), ('directory', ('union', ('str', 'null')), False), ('state', ('ref', 'BackupState'), False), ('pending', 'int', False), ('tracking', 'int', False), ('mirroredFiles', 'int', False), ('lastSuccessAt', ('union', ('str', 'null')), False), ('lastError', ('union', ('str', 'null')), False), ('syncing', 'bool', False), ('intervalSeconds', 'float', False))),
    "SyncResult": ('obj', (('copied', 'int', False), ('skipped', 'int', False), ('failed', 'int', False), ('errors', ('list', 'str'), False), ('directory', 'str', False))),
    "Sex": ('lit', ('M', 'F', 'unknown')),
    "Group": ('obj', (('id', 'str', False), ('name', 'str', False), ('order', 'int', False))),
    "Animal": ('obj', (('id', 'str', False), ('name', 'str', False), ('groupId', 'str', False), ('boxNumber', ('union', ('int', 'null')), False), ('cage', ('union', ('int', 'null')), False), ('sex', ('union', (('ref', 'Sex'), 'null')), False), ('idNumber', ('union', ('str', 'null')), False), ('notes', ('union', ('str', 'null')), False))),
    "CohortAppearance": ('obj', (('type', 'str', False), ('hue', ('union', ('int', 'float')), False), ('ring', 'bool', False), ('seed', ('union', ('int', 'float')), False))),
    "Cohort": ('obj', (('id', 'str', False), ('name', 'str', False), ('dataFolder', 'str', False), ('animals', ('list', ('ref', 'Animal')), False), ('groups', ('list', ('ref', 'Group')), False), ('archivedAt', ('union', ('str', 'null')), False), ('createdAt', 'str', False), ('updatedAt', 'str', False), ('appearance', ('union', (('ref', 'CohortAppearance'), 'null')), False))),
    "CohortSummary": ('obj', (('id', 'str', False), ('name', 'str', False), ('animalCount', 'int', False), ('groupCount', 'int', False), ('assignedBoxes', ('list', 'int'), False), ('cageCount', 'int', False), ('archived', 'bool', False), ('createdAt', 'str', False), ('updatedAt', 'str', False), ('appearance', ('union', (('ref', 'CohortAppearance'), 'null')), False))),
    "CohortPatch": ('obj', (('name', 'str', True), ('animals', ('list', ('ref', 'Animal')), True), ('groups', ('list', ('ref', 'Group')), True), ('appearance', ('union', (('ref', 'CohortAppearance'), 'null')), True))),
    "ProposedAnimal": ('obj', (('animalId', 'str', False), ('boxNumber', 'int', False))),
    "ProposedGroup": ('obj', (('name', 'str', False), ('order', 'int', False), ('animals', ('list', ('ref', 'ProposedAnimal')), False))),
    "GroupRejection": ('obj', (('reason', 'str', False), ('minimumGroups', 'int', False))),
    "GroupProposal": ('obj', (('groups', ('list', ('ref', 'ProposedGroup')), False), ('rejected', ('union', (('ref', 'GroupRejection'), 'null')), False))),
    "Prefix": ('obj', (('id', 'str', False), ('name', 'str', False))),
    "SessionStatus": ('lit', ('configuring', 'running', 'completed', 'aborted')),
    "GroupRun": ('obj', (('groupId', 'str', False), ('order', 'int', False), ('startedAt', 'str', False), ('endedAt', ('union', ('str', 'null')), False))),
    "Session": ('obj', (('id', 'str', False), ('cohortId', 'str', False), ('prefixId', 'str', False), ('prefixName', 'str', False), ('sessionNumber', 'str', False), ('date', 'str', False), ('startedAt', 'str', False), ('endedAt', ('union', ('str', 'null')), False), ('clockStartedAt', 'str', False), ('clockEndedAt', ('union', ('str', 'null')), False), ('status', ('ref', 'SessionStatus'), False), ('folderPath', 'str', False), ('groupRuns', ('list', ('ref', 'GroupRun')), False), ('durationMinutes', ('union', ('int', 'null')), False), ('recording', ('union', (('ref', 'SessionRecording'), 'null')), False))),
    "ConfigFieldType": ('lit', ('int', 'float', 'bool', 'string')),
    "ConfigField": ('obj', (('metadataKey', 'str', False), ('wireKey', 'str', False), ('label', 'str', False), ('type', ('ref', 'ConfigFieldType'), False), ('default', 'any', False), ('group', 'str', True), ('unit', 'str', True), ('min', ('union', ('int', 'float')), True), ('max', ('union', ('int', 'float')), True), ('step', ('union', ('int', 'float')), True), ('help', 'str', True), ('advanced', 'bool', True))),
    "LiveMetric": ('obj', (('id', 'str', False), ('label', 'str', False), ('triggerCode', 'int', False), ('successCode', 'int', False), ('alternateCode', 'int', False), ('windowSize', 'int', False))),
    "ProfileKind": ('lit', ('behavior', 'utility')),
    "ControlOption": ('obj', (('label', 'str', False), ('command', 'str', False))),
    "ControlChannel": ('obj', (('label', 'str', False), ('state', 'str', True), ('toggle', 'str', True), ('pulse', 'str', True), ('kind', 'str', True))),
    "Control": ('obj', (('id', 'str', False), ('label', 'str', False), ('type', ('lit', ('button', 'select', 'grid')), False), ('command', 'str', True), ('options', ('list', ('ref', 'ControlOption')), True), ('channels', ('list', ('ref', 'ControlChannel')), True))),
    "TelemetryField": ('obj', (('key', 'str', False), ('label', 'str', False))),
    "TelemetrySpec": ('obj', (('match', 'str', False), ('fields', ('list', ('ref', 'TelemetryField')), False))),
    "IdentifySpec": ('obj', (('on', 'str', False), ('off', 'str', False))),
    "TaskProfile": ('obj', (('taskName', 'str', False), ('kind', ('ref', 'ProfileKind'), False), ('config', ('list', ('ref', 'ConfigField')), False), ('strobes', ('map', 'str'), False), ('liveMetrics', ('list', ('ref', 'LiveMetric')), False), ('controls', ('list', ('ref', 'Control')), False), ('legacyNames', ('list', 'str'), False), ('telemetry', ('ref', 'TelemetrySpec'), True), ('identify', ('ref', 'IdentifySpec'), True))),
    "SessionBoxMapping": ('obj', (('box', 'int', False), ('animalId', 'str', False), ('sketchPath', 'str', False), ('config', ('map', 'any'), False))),
    "SessionBox": ('obj', (('box', 'int', False), ('animalId', 'str', False), ('animalName', 'str', False), ('sketchName', 'str', False), ('sketchPath', 'str', False), ('running', 'bool', False), ('startedAt', ('union', ('str', 'null')), False))),
    "TelemetryMetric": ('obj', (('id', 'str', False), ('value', ('union', ('float', 'null')), False), ('n', 'int', False))),
    "BoxTelemetry": ('obj', (('box', 'int', False), ('animalId', 'str', False), ('metrics', ('list', ('ref', 'TelemetryMetric')), False))),
    "PortTelemetry": ('obj', (('box', 'int', False), ('running', 'bool', False), ('metrics', ('list', ('ref', 'TelemetryMetric')), False))),
    "AnimalEnded": ('obj', (('box', 'int', False), ('animalId', 'str', False), ('stopReason', 'str', False), ('filePath', ('union', ('str', 'null')), False))),
    "RunnerSession": ('obj', (('session', ('ref', 'Session'), False), ('groupId', ('union', ('str', 'null')), False), ('boxes', ('list', ('ref', 'SessionBox')), False))),
    "ActiveSessions": ('obj', (('running', ('union', (('ref', 'RunnerSession'), 'null')), False), ('configuring', ('list', ('ref', 'Session')), False), ('stale', ('list', ('ref', 'Session')), False))),
    "SessionListItem": ('obj', (('id', 'str', False), ('cohortId', 'str', False), ('prefixName', 'str', False), ('sessionNumber', 'str', False), ('date', 'str', False), ('startedAt', 'str', False), ('endedAt', ('union', ('str', 'null')), False), ('clockStartedAt', 'str', False), ('clockEndedAt', ('union', ('str', 'null')), False), ('status', ('ref', 'SessionStatus'), False), ('folderPath', 'str', False), ('ordinal', 'int', False), ('runCount', 'int', True), ('groupRuns', ('list', ('ref', 'GroupRun')), False))),
    "DiskSession": ('obj', (('cohortId', 'str', False), ('cohortName', 'str', False), ('prefixName', 'str', False), ('sessionNumber', 'str', False), ('date', 'str', False), ('folderPath', 'str', False), ('recorded', 'bool', False))),
    "MetricSummary": ('obj', (('id', 'str', False), ('label', 'str', False), ('pSession', ('union', ('float', 'null')), False), ('pWindow', ('union', ('float', 'null')), False), ('hits', 'int', False), ('counted', 'int', False), ('triggered', 'int', False), ('excluded', 'int', False), ('windowSize', 'int', False), ('wilsonLow', ('union', ('float', 'null')), False), ('wilsonHigh', ('union', ('float', 'null')), False), ('lowConfidence', 'bool', False), ('answerSide', ('union', (('ref', 'AnswerSide'), 'null')), False))),
    "TrialOutcomes": ('obj', (('trials', 'int', False), ('administered', 'int', False), ('rewarded', 'int', False), ('holdFailed', 'int', False), ('wrongWell', 'int', False), ('noResponse', 'int', False), ('aborted', 'int', False), ('pRewarded', ('union', ('float', 'null')), False), ('pSide', ('union', ('float', 'null')), False), ('rewardedLow', ('union', ('float', 'null')), False), ('rewardedHigh', ('union', ('float', 'null')), False), ('sideLow', ('union', ('float', 'null')), False), ('sideHigh', ('union', ('float', 'null')), False))),
    "TrialEngagement": ('obj', (('presented', 'int', False), ('poked', 'int', False), ('odorDelivered', 'int', False), ('noPoke', 'int', False), ('pokeAborted', 'int', False), ('pEngaged', ('union', ('float', 'null')), False), ('pDelivered', ('union', ('float', 'null')), False), ('engagedLow', ('union', ('float', 'null')), False), ('engagedHigh', ('union', ('float', 'null')), False))),
    "ConditionOutcomes": ('obj', (('metricId', 'str', False), ('label', 'str', False), ('triggerCode', 'int', False), ('outcomes', ('ref', 'TrialOutcomes'), False))),
    "RunStatus": ('lit', ('ok', 'no-metrics', 'missing', 'unreadable')),
    "ProfileSource": ('lit', ('snapshot', 'sketch-current', 'inferred', 'unavailable')),
    "RunSummary": ('obj', (('runId', 'str', False), ('sessionId', 'str', False), ('animalId', 'str', False), ('boxNumber', ('union', ('int', 'null')), False), ('startedAt', 'str', False), ('endedAt', ('union', ('str', 'null')), False), ('sketchPath', 'str', False), ('sketchName', 'str', False), ('profileHash', ('union', ('str', 'null')), False), ('paramsHash', ('union', ('str', 'null')), False), ('profileSource', ('ref', 'ProfileSource'), False), ('stale', 'bool', False), ('falseStart', 'bool', False), ('falseStartSource', ('union', (('lit', ('automatic', 'marked', 'restored')), 'null')), False), ('restartedBy', ('union', ('str', 'null')), False), ('status', ('ref', 'RunStatus'), False), ('metrics', ('list', ('ref', 'MetricSummary')), False), ('overall', ('union', (('ref', 'MetricSummary'), 'null')), False), ('outcomes', ('union', (('ref', 'TrialOutcomes'), 'null')), False), ('conditions', ('list', ('ref', 'ConditionOutcomes')), False), ('engagement', ('union', (('ref', 'TrialEngagement'), 'null')), False), ('totalEvents', 'int', False), ('durationMs', ('union', ('float', 'null')), False), ('stopReason', ('union', ('str', 'null')), False), ('clean', 'bool', False), ('seed', ('union', ('int', 'null')), False), ('detail', ('union', ('str', 'null')), False), ('excludedByDefault', 'bool', False))),
    "AnalyticsAnimal": ('obj', (('id', 'str', False), ('name', 'str', False), ('groupId', 'str', False), ('boxNumber', ('union', ('int', 'null')), False), ('cage', ('union', ('int', 'null')), False))),
    "AnswerSide": ('lit', ('left', 'right', 'withhold', 'port')),
    "ProfileMetricInfo": ('obj', (('id', 'str', False), ('label', 'str', False), ('windowSize', 'int', False), ('answerSide', ('union', (('ref', 'AnswerSide'), 'null')), False))),
    "ProfileGroup": ('obj', (('hash', 'str', False), ('taskName', ('union', ('str', 'null')), False), ('kind', ('union', ('str', 'null')), False), ('metrics', ('list', ('ref', 'ProfileMetricInfo')), False), ('runCount', 'int', False))),
    "AnalyticsWarning": ('obj', (('code', 'str', False), ('runId', 'str', False), ('message', 'str', False))),
    "AnalyticsCounts": ('obj', (('runs', 'int', False), ('decoded', 'int', False), ('noProfile', 'int', False), ('missing', 'int', False), ('unreadable', 'int', False), ('falseStarts', 'int', False))),
    "AnalyticsSummary": ('obj', (('cohortId', 'str', False), ('dataFolder', 'str', False), ('sessions', ('list', ('ref', 'SessionListItem')), False), ('animals', ('list', ('ref', 'AnalyticsAnimal')), False), ('groups', ('list', ('ref', 'Group')), False), ('runs', ('list', ('ref', 'RunSummary')), False), ('falseStarts', ('list', ('ref', 'RunSummary')), False), ('profileGroups', ('list', ('ref', 'ProfileGroup')), False), ('counts', ('ref', 'AnalyticsCounts'), False), ('warnings', ('list', ('ref', 'AnalyticsWarning')), False), ('minCountedTrials', 'int', False))),
    "MetricSeries": ('obj', (('id', 'str', False), ('label', 'str', False), ('values', ('list', 'float'), False), ('n', ('list', 'int'), False), ('windowSize', 'int', False))),
    "StrategyPoint": ('obj', (('trial', 'int', False), ('x', 'float', False), ('y', 'float', False), ('n', 'int', False))),
    "TrialRecord": ('obj', (('index', 'int', False), ('triggerCode', 'int', False), ('outcome', ('lit', ('rewarded', 'hold-failed', 'wrong-well', 'no-response', 'aborted')), False), ('atMs', ('union', ('int', 'null')), False), ('latencyMs', ('union', ('int', 'null')), False))),
    "RunSeries": ('obj', (('runId', 'str', False), ('mode', ('lit', ('rolling', 'cumulative')), False), ('metrics', ('list', ('ref', 'MetricSeries')), False), ('trail', ('list', ('ref', 'StrategyPoint')), False), ('trials', ('list', ('ref', 'TrialRecord')), False))),
    "SeriesResult": ('obj', (('series', ('list', ('ref', 'RunSeries')), False), ('warnings', ('list', ('ref', 'AnalyticsWarning')), False))),
    "RescanOrphan": ('obj', (('path', 'str', False), ('animalId', ('union', ('str', 'null')), False), ('animalName', ('union', ('str', 'null')), False), ('animalSource', ('union', (('lit', ('document', 'filename')), 'null')), False), ('date', ('union', ('str', 'null')), False), ('status', 'str', False), ('reason', ('union', ('str', 'null')), False))),
    "RescanPruned": ('obj', (('runs', 'int', False), ('sessions', 'int', False), ('adopted', 'int', False))),
    "RescanResult": ('obj', (('scanned', 'int', False), ('adopted', 'int', False), ('pruned', ('ref', 'RescanPruned'), False), ('duplicates', 'int', False), ('orphans', ('list', ('ref', 'RescanOrphan')), False), ('cohortId', 'str', False), ('dataFolder', 'str', False), ('folderMissing', 'bool', False))),
    "AnalyticsProgress": ('obj', (('cohortId', 'str', False), ('phase', ('lit', ('reading', 'walking')), False), ('done', 'int', False), ('total', 'int', False))),
    "RecoveredTsv": ('obj', (('tsvPath', 'str', False), ('jsonPath', ('union', ('str', 'null')), False), ('status', ('lit', ('recovered', 'failed')), False), ('nEvents', 'int', False), ('stopReason', ('union', ('str', 'null')), False), ('reason', ('union', ('str', 'null')), False))),
    "RecoverResult": ('obj', (('scanned', 'int', False), ('recovered', 'int', False), ('failed', 'int', False), ('entries', ('list', ('ref', 'RecoveredTsv')), False), ('cohortId', 'str', False), ('dataFolder', 'str', False), ('folderMissing', 'bool', False))),
    "TidySession": ('obj', (('sessionId', 'str', False), ('label', 'str', False), ('date', 'str', False), ('status', ('ref', 'SessionStatus'), False), ('startedAt', 'str', False), ('runCount', 'int', False), ('groupIds', ('list', 'str'), False))),
    "TidyMerge": ('obj', (('keep', ('ref', 'TidySession'), False), ('absorb', ('list', ('ref', 'TidySession')), False))),
    "TidyEmpty": ('obj', (('session', ('ref', 'TidySession'), False), ('removesFolder', 'bool', False))),
    "TidySkipped": ('obj', (('session', ('ref', 'TidySession'), False), ('reason', 'str', False))),
    "TidyPlan": ('obj', (('cohortId', 'str', False), ('applied', 'bool', False), ('merges', ('list', ('ref', 'TidyMerge')), False), ('empty', ('list', ('ref', 'TidyEmpty')), False), ('skipped', ('list', ('ref', 'TidySkipped')), False))),
    "ServerHello": ('obj', (('protocolVersion', 'int', False), ('sidecarVersion', 'str', False))),
    "PortStateData": ('obj', (('box', 'int', False), ('state', ('ref', 'PortStateName'), False), ('prev', ('ref', 'PortStateName'), False), ('reason', 'str', False))),
    "PortOutputData": ('obj', (('box', 'int', False), ('lines', ('list', ('ref', 'OutputLine')), False))),
    "BoardsPresenceData": ('obj', (('boards', ('list', ('ref', 'DetectedBoard')), False),)),
    "FlashProgressData": ('obj', (('box', 'int', False), ('phase', ('lit', ('compile', 'upload')), False), ('stream', ('lit', ('stdout', 'stderr')), False), ('text', 'str', False))),
    "CohortsUpdatedData": ('obj', (('cohorts', ('list', ('ref', 'CohortSummary')), False),)),
    "PrefixesUpdatedData": ('obj', (('prefixes', ('list', ('ref', 'Prefix')), False),)),
    "SidecarErrorData": ('obj', (('code', 'str', False), ('message', 'str', False), ('detail', 'any', False))),
    "RigProblem": ('obj', (('location', 'str', False), ('message', 'str', False), ('code', ('union', ('str', 'null')), False))),
    "RigStatus": ('obj', (('custom', 'bool', False), ('derivedFrom', 'str', False), ('board', 'str', False), ('editedAt', ('union', ('str', 'null')), False), ('pinoutHash', 'str', False))),
    "RigDocument": ('obj', (('document', 'any', False), ('status', ('ref', 'RigStatus'), False), ('problems', ('list', ('ref', 'RigProblem')), False))),
    "RigImpact": ('obj', (('specId', 'str', False), ('label', ('union', ('str', 'null')), False), ('codes', ('list', 'str'), False))),
    "RigSaved": ('obj', (('status', ('ref', 'RigStatus'), False), ('problems', ('list', ('ref', 'RigProblem')), False), ('breaks', ('list', ('ref', 'RigImpact')), False))),
    "TaskDiagnostic": ('obj', (('location', 'str', False), ('message', 'str', False), ('code', 'str', False))),
    "TaskEntry": ('obj', (('id', 'str', False), ('name', 'str', False), ('category', 'str', False), ('path', 'str', False), ('label', 'str', False), ('editedAt', ('union', ('str', 'null')), False), ('problems', 'int', False), ('trials', 'int', False), ('stages', 'int', False), ('selectionMode', ('lit', ('antibias', 'pool', 'weighted')), False))),
    "TaskSaved": ('obj', (('entry', ('ref', 'TaskEntry'), False), ('diagnostics', ('list', ('ref', 'TaskDiagnostic')), False), ('sketchPath', ('union', ('str', 'null')), False))),
    "TaskPreview": ('obj', (('diagnostics', ('list', ('ref', 'TaskDiagnostic')), False), ('startLineLength', 'int', False), ('startLineMax', 'int', False), ('profile', ('ref', 'TaskProfile'), False), ('catalogueDefaults', ('map', 'any'), False))),
    "TasksUpdatedData": ('obj', (('tasks', ('list', ('ref', 'TaskEntry')), False),)),
    "StrobeCode": ('obj', (('name', 'str', False), ('code', 'int', False), ('origin', 'str', False), ('emittedOn', 'str', True), ('rationale', 'str', True), ('portSlot', 'int', True))),
    "RetiredStrobe": ('obj', (('name', 'str', False), ('code', 'int', False), ('rationale', 'str', True), ('seenIn', 'str', True), ('retiredAt', 'str', True))),
    "StrobeVocabulary": ('obj', (('version', 'int', False), ('codeMin', 'int', False), ('codeMax', 'int', False), ('reserved', ('list', ('list', 'int')), False), ('freeRanges', ('list', ('list', 'int')), False), ('nextFree', ('union', ('int', 'null')), False), ('contentHash', 'str', False), ('codes', ('list', ('ref', 'StrobeCode')), False), ('retired', ('list', ('ref', 'RetiredStrobe')), False), ('portSlots', ('map', ('map', 'str')), False), ('editable', 'bool', False), ('problem', ('union', ('str', 'null')), False))),
    "StrobeFirmwareRef": ('obj', (('path', 'str', False), ('kind', ('lit', ('library', 'sketch', 'task')), False))),
    "StrobeArchiveCoverage": ('obj', (('files', 'int', False), ('unreadable', 'int', False), ('roots', ('list', 'str'), False), ('unreachableRoots', ('list', 'str'), False))),
    "StrobeSessions": ('obj', (('count', 'int', False), ('sample', ('list', 'str'), False), ('scanned', ('ref', 'StrobeArchiveCoverage'), False))),
    "StrobeUsage": ('obj', (('name', 'str', False), ('code', 'int', False), ('status', ('lit', ('live', 'retired')), False), ('firmware', ('list', ('ref', 'StrobeFirmwareRef')), False), ('portSlot', ('union', ('int', 'null')), False), ('breaks', ('list', ('ref', 'RigImpact')), False), ('sessions', ('union', (('ref', 'StrobeSessions'), 'null')), False), ('retireBlocker', ('union', ('str', 'null')), False), ('removeBlocker', ('union', ('str', 'null')), False))),
    "StrobeImportPlan": ('obj', (('adds', ('list', ('obj', (('name', 'str', False), ('code', 'int', False), ('retired', 'bool', False)))), False), ('retires', ('list', ('obj', (('name', 'str', False), ('code', 'int', False)))), False), ('conflicts', ('list', ('obj', (('name', 'str', False), ('code', 'int', False), ('message', 'str', False)))), False), ('onlyHere', ('list', 'str'), False))),
    "StrobeScanProgress": ('obj', (('done', 'int', False), ('total', 'int', False))),
    "RecordingBox": ('obj', (('box', 'int', False), ('digitalIn', 'int', False), ('port', 'str', False), ('channels', ('list', 'str'), False), ('probeMap', ('union', ('str', 'null')), False))),
    "RecordingRun": ('obj', (('groupId', 'str', False), ('path', 'str', False), ('baseFilename', 'str', False), ('fileTimestamp', ('union', ('str', 'null')), False), ('fileFormat', 'str', False), ('sampleRate', 'int', False), ('startedAt', ('union', ('str', 'null')), False), ('endedAt', ('union', ('str', 'null')), False), ('boxes', ('list', ('ref', 'RecordingBox')), False))),
    "SessionRecording": ('obj', (('runs', ('list', ('ref', 'RecordingRun')), False),)),
    "RecordingBoxConfig": ('obj', (('box', 'int', False), ('port', 'str', False), ('firstChannel', 'int', False), ('lastChannel', 'int', False), ('probeMapPath', ('union', ('str', 'null')), True))),
    "RecordingThreshold": ('obj', (('mode', ('lit', ('keep', 'absolute', 'rms')), False), ('microvolts', 'int', False), ('rmsMultiple', 'float', False), ('negative', 'bool', False))),
    "RecordingConfig": ('obj', (('saveDirectory', 'str', False), ('fileFormat', ('lit', ('Traditional', 'OneFilePerSignalType', 'OneFilePerChannel')), False), ('saveWideband', 'bool', False), ('saveSpikes', 'bool', False), ('saveSpikeSnapshots', 'bool', False), ('snapshotPreMs', 'int', False), ('snapshotPostMs', 'int', False), ('saveLowpass', 'bool', False), ('lowpassDownsample', 'int', False), ('saveHighpass', 'bool', False), ('newFileMinutes', 'int', True), ('threshold', ('ref', 'RecordingThreshold'), False), ('boxes', ('list', ('ref', 'RecordingBoxConfig')), False))),
    "IntanState": ('lit', ('disconnected', 'idle', 'configured', 'recording', 'stopping', 'error')),
    "IntanSyncStat": ('obj', (('box', 'int', False), ('matched', 'int', False), ('spuriousEdges', 'int', False), ('unmatchedStrobes', 'int', False))),
    "IntanStatus": ('obj', (('state', ('ref', 'IntanState'), False), ('message', ('union', ('str', 'null')), False), ('connected', 'bool', False), ('controller', ('union', ('str', 'null')), False), ('version', ('union', ('str', 'null')), False), ('sampleRate', ('union', ('int', 'null')), False), ('synthetic', 'bool', False), ('headstagePresent', 'bool', False), ('runMode', ('union', ('str', 'null')), False), ('ports', ('map', 'int'), False), ('confirmsWrites', ('union', ('bool', 'null')), False), ('rigHasSync', 'bool', False), ('liveStreams', 'bool', False), ('recording', ('union', (('ref', 'RecordingRun'), 'null')), False), ('waitingOn', ('list', 'int'), False), ('sync', ('list', ('ref', 'IntanSyncStat')), False))),
    "ScopeKind": ('lit', ('spikescope', 'psth', 'isi', 'probemap')),
    "ScopeData": ('obj', (('scopeId', 'str', False), ('kind', ('ref', 'ScopeKind'), False), ('box', 'int', False), ('channel', ('union', ('str', 'null')), False), ('data', 'any', False))),
    "NoteTag": ('lit', ('observation', 'intervention', 'hardware', 'animal-health', 'protocol-deviation')),
    "NoteScope": ('obj', (('kind', ('lit', ('session', 'animal', 'box')), False), ('animalId', ('union', ('str', 'null')), False), ('box', ('union', ('int', 'null')), False))),
    "SessionNote": ('obj', (('id', 'str', False), ('sessionId', 'str', False), ('cohortId', 'str', False), ('at', 'str', False), ('createdAt', 'str', False), ('editedAt', ('union', ('str', 'null')), False), ('tag', ('ref', 'NoteTag'), False), ('scope', ('ref', 'NoteScope'), False), ('body', 'str', False), ('offsetMs', ('union', ('int', 'null')), False), ('carryForward', 'bool', False), ('resolvedAt', ('union', ('str', 'null')), False), ('resolvedInSessionId', ('union', ('str', 'null')), False))),
    "SessionLog": ('obj', (('sessionId', 'str', False), ('operator', ('union', ('str', 'null')), False), ('summary', ('union', ('str', 'null')), False), ('updatedAt', ('union', ('str', 'null')), False))),
    "ValueChange": ('obj', (('from', 'any', False), ('to', 'any', False))),
    "ParamChange": ('obj', (('key', 'str', False), ('from', 'any', False), ('to', 'any', False))),
    "RunChange": ('obj', (('runId', 'str', False), ('sessionId', 'str', False), ('animalId', 'str', False), ('box', ('union', ('int', 'null')), False), ('task', 'str', False), ('recovered', 'bool', False), ('previousRunId', ('union', ('str', 'null')), False), ('previousSessionId', ('union', ('str', 'null')), False), ('first', 'bool', False), ('taskChange', ('union', (('ref', 'ValueChange'), 'null')), False), ('boxChange', ('union', (('ref', 'ValueChange'), 'null')), False), ('params', ('list', ('ref', 'ParamChange')), False), ('paramsKnown', 'bool', False), ('falseStart', 'bool', False), ('falseStartSource', ('union', (('lit', ('automatic', 'marked', 'restored')), 'null')), False))),
    "LogbookCohort": ('obj', (('cohortId', 'str', False), ('logs', ('list', ('ref', 'SessionLog')), False), ('notes', ('list', ('ref', 'SessionNote')), False), ('changes', ('list', ('ref', 'RunChange')), False))),
    "LogbookUpdated": ('obj', (('cohortId', 'str', False), ('sessionIds', ('list', 'str'), False))),
}

COMMAND_ARGS: Final[dict[str, Any]] = {
    "auth": ('obj', (('token', 'str', False),)),
    "settings.push": ('obj', (('settings', ('ref', 'EphymerisSettings'), False),)),
    "sketches.refresh": ('obj', ()),
    "port.passthrough.open": ('obj', (('box', 'int', False), ('baud', 'int', True))),
    "port.passthrough.close": ('obj', (('box', 'int', False),)),
    "port.send": ('obj', (('box', 'int', False), ('text', 'str', False), ('lineEnding', ('lit', ('none', 'lf', 'cr', 'crlf')), True))),
    "port.sendStart": ('obj', (('box', 'int', False), ('sketchPath', 'str', False), ('config', ('map', 'any'), True))),
    "port.flash": ('obj', (('box', 'int', False), ('sketchPath', 'str', False), ('suppressPassthroughResume', 'bool', True))),
    "port.reset": ('obj', (('box', 'int', False),)),
    "port.error.ack": ('obj', (('box', 'int', False),)),
    "port.startSession": ('obj', (('box', 'int', False),)),
    "port.stopSession": ('obj', (('box', 'int', False),)),
    "utility.ensure": ('obj', (('boxes', ('list', 'int'), True), ('force', 'bool', True))),
    "utility.identify": ('obj', (('box', 'int', False), ('on', 'bool', False))),
    "hardware.get": ('obj', ()),
    "hardware.preview": ('obj', (('document', 'any', False),)),
    "hardware.save": ('obj', (('document', 'any', False), ('confirm', 'bool', False))),
    "hardware.reset": ('obj', ()),
    "strobes.get": ('obj', ()),
    "strobes.usage": ('obj', (('name', 'str', False), ('scan', 'bool', True))),
    "strobes.add": ('obj', (('name', 'str', False), ('code', 'int', False), ('rationale', 'str', False), ('emittedOn', 'str', True))),
    "strobes.edit": ('obj', (('name', 'str', False), ('rationale', 'str', False), ('emittedOn', 'str', True))),
    "strobes.retire": ('obj', (('name', 'str', False), ('confirm', 'bool', False))),
    "strobes.reinstate": ('obj', (('name', 'str', False),)),
    "strobes.remove": ('obj', (('name', 'str', False), ('confirm', 'bool', False))),
    "strobes.export": ('obj', ()),
    "strobes.import": ('obj', (('document', 'any', False), ('apply', 'bool', False))),
    "cohorts.list": ('obj', ()),
    "cohorts.get": ('obj', (('id', 'str', False),)),
    "cohorts.create": ('obj', (('name', 'str', False), ('dataFolder', 'str', True), ('animals', ('list', ('ref', 'Animal')), True), ('groups', ('list', ('ref', 'Group')), True))),
    "cohorts.update": ('obj', (('id', 'str', False), ('patch', ('ref', 'CohortPatch'), False))),
    "cohorts.archive": ('obj', (('id', 'str', False),)),
    "cohorts.restore": ('obj', (('id', 'str', False),)),
    "cohorts.delete": ('obj', (('id', 'str', False), ('confirm', 'bool', False))),
    "cohorts.setDataFolder": ('obj', (('id', 'str', False), ('path', 'str', False), ('moveExisting', 'bool', False))),
    "cohorts.suggestGroups": ('obj', (('id', 'str', False), ('groupCount', 'int', True), ('maxGroupSize', 'int', True), ('balanceBySex', 'bool', True))),
    "prefixes.list": ('obj', ()),
    "prefixes.create": ('obj', (('name', 'str', False),)),
    "prefixes.delete": ('obj', (('id', 'str', False),)),
    "sessions.suggestNumber": ('obj', (('prefixId', 'str', False),)),
    "sessions.create": ('obj', (('cohortId', 'str', False), ('prefixId', 'str', False), ('sessionNumber', 'str', False), ('durationMinutes', 'int', True), ('recording', 'bool', True))),
    "sessions.abandon": ('obj', (('sessionId', 'str', False),)),
    "sessions.confirmMapping": ('obj', (('sessionId', 'str', False), ('groupId', 'str', False), ('boxes', ('list', ('ref', 'SessionBoxMapping')), False))),
    "sessions.status": ('obj', (('sessionId', 'str', False),)),
    "sessions.startAll": ('obj', (('sessionId', 'str', False),)),
    "sessions.endGroup": ('obj', (('sessionId', 'str', False),)),
    "sessions.resume": ('obj', (('sessionId', 'str', False),)),
    "sessions.end": ('obj', (('sessionId', 'str', False),)),
    "sessions.active": ('obj', ()),
    "tasks.getProfile": ('obj', (('sketchPath', 'str', False),)),
    "tasks.list": ('obj', ()),
    "tasks.get": ('obj', (('taskId', 'str', False),)),
    "tasks.preview": ('obj', (('definition', 'any', False),)),
    "tasks.save": ('obj', (('definition', 'any', False),)),
    "tasks.delete": ('obj', (('taskId', 'str', False),)),
    "backup.syncNow": ('obj', ()),
    "sessions.list": ('obj', (('cohortId', 'str', False), ('includeAborted', 'bool', True))),
    "analytics.summary": ('obj', (('cohortId', 'str', False), ('sessionIds', ('list', 'str'), True), ('animalIds', ('list', 'str'), True), ('minCountedTrials', 'int', True))),
    "analytics.setFalseStart": ('obj', (('cohortId', 'str', False), ('runId', 'str', False), ('falseStart', ('union', ('bool', 'null')), False))),
    "analytics.series": ('obj', (('runIds', ('list', 'str'), False), ('mode', ('lit', ('rolling', 'cumulative')), True), ('metricIds', ('list', 'str'), True))),
    "analytics.rescan": ('obj', (('cohortId', 'str', False), ('adoptOrphans', 'bool', True))),
    "analytics.recentSessions": ('obj', (('limit', 'int', True),)),
    "sessions.recover": ('obj', (('cohortId', 'str', False),)),
    "sessions.tidy": ('obj', (('cohortId', 'str', False), ('apply', 'bool', True))),
    "intan.status": ('obj', ()),
    "intan.connect": ('obj', ()),
    "intan.disconnect": ('obj', ()),
    "intan.configure": ('obj', (('sessionId', 'str', False), ('groupId', 'str', False), ('config', ('ref', 'RecordingConfig'), False))),
    "intan.parseProbeMap": ('obj', (('path', 'str', False),)),
    "intan.probeMap": ('obj', (('box', 'int', False),)),
    "intan.setThreshold": ('obj', (('channel', 'str', False), ('microvolts', 'int', False))),
    "intan.scope.open": ('obj', (('kind', ('ref', 'ScopeKind'), False), ('box', 'int', False), ('channel', ('union', ('str', 'null')), True), ('params', ('map', 'any'), True))),
    "intan.scope.update": ('obj', (('scopeId', 'str', False), ('channel', ('union', ('str', 'null')), True), ('params', ('map', 'any'), True))),
    "intan.scope.close": ('obj', (('scopeId', 'str', False),)),
    "intan.forceStop": ('obj', ()),
    "logbook.cohort": ('obj', (('cohortId', 'str', False),)),
    "logbook.addNote": ('obj', (('sessionId', 'str', False), ('tag', ('ref', 'NoteTag'), False), ('body', 'str', False), ('scope', ('ref', 'NoteScope'), True), ('carryForward', 'bool', True), ('at', 'str', True))),
    "logbook.editNote": ('obj', (('noteId', 'str', False), ('tag', ('ref', 'NoteTag'), True), ('body', 'str', True), ('scope', ('ref', 'NoteScope'), True), ('carryForward', 'bool', True), ('at', 'str', True))),
    "logbook.deleteNote": ('obj', (('noteId', 'str', False),)),
    "logbook.resolveFlag": ('obj', (('noteId', 'str', False), ('resolved', 'bool', False), ('sessionId', ('union', ('str', 'null')), True))),
    "logbook.setSessionLog": ('obj', (('sessionId', 'str', False), ('operator', ('union', ('str', 'null')), True), ('summary', ('union', ('str', 'null')), True))),
    "logbook.openFlags": ('obj', (('cohortId', 'str', False),)),
}

COMMAND_RESULTS: Final[dict[str, Any]] = {
    "auth": ('obj', (('authenticated', 'bool', False),)),
    "settings.push": ('obj', (('library', ('ref', 'SketchLibraryStatus'), False),)),
    "sketches.refresh": ('ref', 'SketchDiscovery'),
    "port.passthrough.open": ('obj', (('state', ('ref', 'PortStateName'), False),)),
    "port.passthrough.close": ('obj', (('state', ('ref', 'PortStateName'), False),)),
    "port.send": ('obj', (('bytesWritten', 'int', False),)),
    "port.sendStart": ('obj', (('command', 'str', False), ('bytesWritten', 'int', False))),
    "port.flash": ('obj', (('state', ('ref', 'PortStateName'), False), ('resumedPassthrough', 'bool', False))),
    "port.reset": ('obj', (('state', ('ref', 'PortStateName'), False), ('resumedPassthrough', 'bool', False))),
    "port.error.ack": ('obj', (('state', ('ref', 'PortStateName'), False),)),
    "port.startSession": ('obj', (('state', ('ref', 'PortStateName'), False),)),
    "port.stopSession": ('obj', (('state', ('ref', 'PortStateName'), False),)),
    "utility.ensure": ('ref', 'UtilityStatus'),
    "utility.identify": ('obj', (('delivered', 'bool', False), ('state', ('ref', 'UtilityBoxState'), False))),
    "hardware.get": ('ref', 'RigDocument'),
    "hardware.preview": ('ref', 'RigSaved'),
    "hardware.save": ('ref', 'RigSaved'),
    "hardware.reset": ('ref', 'RigDocument'),
    "strobes.get": ('ref', 'StrobeVocabulary'),
    "strobes.usage": ('ref', 'StrobeUsage'),
    "strobes.add": ('ref', 'StrobeVocabulary'),
    "strobes.edit": ('ref', 'StrobeVocabulary'),
    "strobes.retire": ('ref', 'StrobeVocabulary'),
    "strobes.reinstate": ('ref', 'StrobeVocabulary'),
    "strobes.remove": ('ref', 'StrobeVocabulary'),
    "strobes.export": ('obj', (('document', 'any', False), ('filename', 'str', False))),
    "strobes.import": ('obj', (('plan', ('ref', 'StrobeImportPlan'), False), ('vocabulary', ('union', (('ref', 'StrobeVocabulary'), 'null')), False))),
    "cohorts.list": ('obj', (('cohorts', ('list', ('ref', 'CohortSummary')), False),)),
    "cohorts.get": ('obj', (('cohort', ('ref', 'Cohort'), False),)),
    "cohorts.create": ('obj', (('cohort', ('ref', 'Cohort'), False),)),
    "cohorts.update": ('obj', (('cohort', ('ref', 'Cohort'), False),)),
    "cohorts.archive": ('obj', (('cohort', ('ref', 'Cohort'), False),)),
    "cohorts.restore": ('obj', (('cohort', ('ref', 'Cohort'), False),)),
    "cohorts.delete": ('obj', (('deleted', 'bool', False),)),
    "cohorts.setDataFolder": ('obj', (('cohort', ('ref', 'Cohort'), False),)),
    "cohorts.suggestGroups": ('ref', 'GroupProposal'),
    "prefixes.list": ('obj', (('prefixes', ('list', ('ref', 'Prefix')), False),)),
    "prefixes.create": ('obj', (('prefix', ('ref', 'Prefix'), False),)),
    "prefixes.delete": ('obj', (('deleted', 'bool', False),)),
    "sessions.suggestNumber": ('obj', (('suggestion', ('union', ('str', 'null')), False), ('sameDayNumbers', ('list', 'str'), False))),
    "sessions.create": ('obj', (('session', ('ref', 'Session'), False),)),
    "sessions.abandon": ('obj', (('session', ('ref', 'Session'), False),)),
    "sessions.confirmMapping": ('obj', (('ok', 'bool', False),)),
    "sessions.status": ('obj', (('session', ('ref', 'Session'), False), ('groupId', ('union', ('str', 'null')), False), ('boxes', ('list', ('ref', 'SessionBox')), False))),
    "sessions.startAll": ('obj', (('session', ('ref', 'Session'), False),)),
    "sessions.endGroup": ('obj', (('session', ('ref', 'Session'), False),)),
    "sessions.resume": ('obj', (('session', ('ref', 'Session'), False),)),
    "sessions.end": ('obj', (('session', ('ref', 'Session'), False),)),
    "sessions.active": ('ref', 'ActiveSessions'),
    "tasks.getProfile": ('union', (('ref', 'TaskProfile'), ('obj', (('profile', 'null', False),)))),
    "tasks.list": ('obj', (('tasks', ('list', ('ref', 'TaskEntry')), False),)),
    "tasks.get": ('obj', (('definition', 'any', False), ('diagnostics', ('list', ('ref', 'TaskDiagnostic')), False))),
    "tasks.preview": ('ref', 'TaskPreview'),
    "tasks.save": ('ref', 'TaskSaved'),
    "tasks.delete": ('obj', (('deleted', 'bool', False),)),
    "backup.syncNow": ('ref', 'SyncResult'),
    "sessions.list": ('obj', (('sessions', ('list', ('ref', 'SessionListItem')), False),)),
    "analytics.summary": ('ref', 'AnalyticsSummary'),
    "analytics.setFalseStart": ('obj', (('runId', 'str', False),)),
    "analytics.series": ('ref', 'SeriesResult'),
    "analytics.rescan": ('ref', 'RescanResult'),
    "analytics.recentSessions": ('obj', (('sessions', ('list', ('ref', 'DiskSession')), False),)),
    "sessions.recover": ('ref', 'RecoverResult'),
    "sessions.tidy": ('ref', 'TidyPlan'),
    "intan.status": ('ref', 'IntanStatus'),
    "intan.connect": ('ref', 'IntanStatus'),
    "intan.disconnect": ('ref', 'IntanStatus'),
    "intan.configure": ('ref', 'IntanStatus'),
    "intan.parseProbeMap": ('obj', (('probeMap', 'any', False),)),
    "intan.probeMap": ('obj', (('probeMap', 'any', False),)),
    "intan.setThreshold": ('obj', (('channel', 'str', False), ('microvolts', 'int', False))),
    "intan.scope.open": ('obj', (('scopeId', 'str', False),)),
    "intan.scope.update": ('obj', (('ok', 'bool', False),)),
    "intan.scope.close": ('obj', (('ok', 'bool', False),)),
    "intan.forceStop": ('obj', (('ok', 'bool', False),)),
    "logbook.cohort": ('ref', 'LogbookCohort'),
    "logbook.addNote": ('obj', (('note', ('ref', 'SessionNote'), False),)),
    "logbook.editNote": ('obj', (('note', ('ref', 'SessionNote'), False),)),
    "logbook.deleteNote": ('obj', ()),
    "logbook.resolveFlag": ('obj', (('note', ('ref', 'SessionNote'), False),)),
    "logbook.setSessionLog": ('obj', (('log', ('ref', 'SessionLog'), False),)),
    "logbook.openFlags": ('obj', (('notes', ('list', ('ref', 'SessionNote')), False),)),
}

EVENT_DATA: Final[dict[str, Any]] = {
    "server.hello": ('ref', 'ServerHello'),
    "port.state": ('ref', 'PortStateData'),
    "port.output": ('ref', 'PortOutputData'),
    "port.telemetry": ('ref', 'PortTelemetry'),
    "boards.presence": ('ref', 'BoardsPresenceData'),
    "flash.progress": ('ref', 'FlashProgressData'),
    "sketches.updated": ('ref', 'SketchDiscovery'),
    "cohorts.updated": ('ref', 'CohortsUpdatedData'),
    "prefixes.updated": ('ref', 'PrefixesUpdatedData'),
    "session.telemetry": ('ref', 'BoxTelemetry'),
    "session.animalEnded": ('ref', 'AnimalEnded'),
    "logbook.updated": ('ref', 'LogbookUpdated'),
    "session.lifecycle": ('ref', 'ActiveSessions'),
    "hardware.updated": ('ref', 'RigStatus'),
    "strobes.updated": ('ref', 'StrobeVocabulary'),
    "strobes.scanProgress": ('ref', 'StrobeScanProgress'),
    "utility.updated": ('ref', 'UtilityStatus'),
    "backup.status": ('ref', 'BackupStatus'),
    "analytics.progress": ('ref', 'AnalyticsProgress'),
    "sidecar.error": ('ref', 'SidecarErrorData'),
    "tasks.updated": ('ref', 'TasksUpdatedData'),
    "intan.status": ('ref', 'IntanStatus'),
    "intan.scope.data": ('ref', 'ScopeData'),
}


# --- Shape validation -------------------------------------------------------

class WireShapeError(AssertionError):
    """A payload does not match the shape `protocol/schema.py` declares."""


def wire_validation_enabled() -> bool:
    """Opt-in via EPHYMERIS_WIRE_VALIDATE=1 — the test suite turns it on.

    Off by default in production: a benign schema lag must never take down a
    live session over a payload the frontend would have rendered fine.
    """
    return os.environ.get("EPHYMERIS_WIRE_VALIDATE") == "1"


def validate(spec: Any, value: Any, path: str = "$") -> list[str]:
    """Structural check of `value` against a spec; returns problems, [] if ok.

    Deliberately strict in both directions: a *missing* required field and an
    *unknown* field are both errors, because either one is exactly the
    one-sided drift this exists to catch (TODO item 8).
    """
    errors: list[str] = []
    _check(spec, value, path, errors)
    return errors


def validate_command_args(cmd: str, args: Any) -> list[str]:
    spec = COMMAND_ARGS.get(cmd)
    if spec is None:
        return [f"unknown command: {cmd}"]
    return validate(spec, args if args is not None else {}, f"{cmd}.args")


def validate_command_result(cmd: str, result: Any) -> list[str]:
    spec = COMMAND_RESULTS.get(cmd)
    if spec is None:
        return [f"unknown command: {cmd}"]
    return validate(spec, result, f"{cmd}.result")


def validate_event_data(name: str, data: Any) -> list[str]:
    spec = EVENT_DATA.get(name)
    if spec is None:
        return [f"unknown event: {name}"]
    return validate(spec, data, f"{name}.data")


def _describe(value: Any) -> str:
    return "null" if value is None else type(value).__name__


def _check(spec: Any, value: Any, path: str, errors: list[str]) -> None:
    if isinstance(spec, str):
        if spec == "any":
            return
        ok = {
            "null": value is None,
            "str": isinstance(value, str),
            "bool": isinstance(value, bool),
            # bool is an int subclass, and a True on the wire where a count
            # belongs is exactly the sort of bug worth failing on.
            "int": isinstance(value, int) and not isinstance(value, bool),
            "float": isinstance(value, (int, float)) and not isinstance(value, bool),
        }[spec]
        if not ok:
            errors.append(f"{path}: expected {spec}, got {_describe(value)}")
        return

    tag = spec[0]
    if tag == "lit":
        if value not in spec[1]:
            errors.append(f"{path}: {value!r} not one of {list(spec[1])}")
    elif tag == "list":
        if not isinstance(value, list):
            errors.append(f"{path}: expected list, got {_describe(value)}")
            return
        for index, item in enumerate(value):
            _check(spec[1], item, f"{path}[{index}]", errors)
    elif tag == "map":
        if not isinstance(value, dict):
            errors.append(f"{path}: expected object, got {_describe(value)}")
            return
        for key, item in value.items():
            if not isinstance(key, str):
                errors.append(f"{path}: non-string key {key!r}")
                continue
            _check(spec[1], item, f"{path}.{key}", errors)
    elif tag == "union":
        # Valid if any arm accepts; report the closest-fitting arm's problems.
        best: list[str] | None = None
        for option in spec[1]:
            attempt: list[str] = []
            _check(option, value, path, attempt)
            if not attempt:
                return
            if best is None or len(attempt) < len(best):
                best = attempt
        errors.extend(best or [f"{path}: matches no union arm"])
    elif tag == "ref":
        _check(SHAPES[spec[1]], value, path, errors)
    elif tag == "obj":
        if not isinstance(value, dict):
            errors.append(f"{path}: expected object, got {_describe(value)}")
            return
        fields = {name: (field_spec, optional) for name, field_spec, optional in spec[1]}
        for name, (field_spec, optional) in fields.items():
            if name not in value:
                if not optional:
                    errors.append(f"{path}: missing required field `{name}`")
                continue
            _check(field_spec, value[name], f"{path}.{name}", errors)
        for name in value:
            if name not in fields:
                errors.append(f"{path}: unknown field `{name}`")
    else:  # pragma: no cover - unreachable with generated specs
        errors.append(f"{path}: malformed spec {spec!r}")


# --- Envelope builders ----------------------------------------------------

def reply_ok(corr: str, result: Any = None) -> dict[str, Any]:
    return {"v": PROTOCOL_VERSION, "corr": corr, "ok": True, "result": result}


def reply_err(
    corr: str, code: str, message: str, detail: Any = None
) -> dict[str, Any]:
    return {
        "v": PROTOCOL_VERSION,
        "corr": corr,
        "ok": False,
        "error": {"code": code, "message": message, "detail": detail},
    }


def event(name: str, data: Any = None, corr: str | None = None) -> dict[str, Any]:
    if wire_validation_enabled():
        problems = validate_event_data(name, data)
        if problems:
            raise WireShapeError(
                f"event `{name}` payload violates protocol/schema.py:\n  "
                + "\n  ".join(problems)
            )
    msg: dict[str, Any] = {
        "v": PROTOCOL_VERSION,
        "evt": name,
        "ts": time.time(),
        "data": data,
    }
    if corr is not None:
        msg["corr"] = corr
    return msg
